### ISSUE TITLE
calc_sc branch calculation error

### ISSUE THREAD

**Issue by apetros** [e2nIEE/pandapower#1004]
I have been investigating the calc_sc function with and without a fault impedance and met with a behavior I cannot easily explain. I know this is still in beta mode.

I used the tutorial on SC analysis from [here](https://github.com/e2nIEE/pandapower/blob/master/tutorials/shortcircuit.ipynb).

I compute the 3ph short circuit with fault impedance Z_F=0 and then again with Z_F=5+j10 Ohm. While the max fault currents at the nodes are decreasing as expected, the max fault currents on the branches are many times higher. 

As I understand, the currents are computed based on the post-fault voltages and the Ybus matrix. However, I expected when the short-circuit currents on each node are decreasing so would the max short-circuit current on the branches (roughly based on Kirchoff's law). Is this a bug or something I don't understand?

<img width="844" alt="pp_sc_issue" src="https://user-images.githubusercontent.com/10074820/99818234-a1671000-2b56-11eb-82ac-2668f9aaa92b.png">

**Comment by lthurner** [comment]
Thanks for reporting, this definitly looks like a bug. There is an open PR about SC branch currents #914. Maybe it already fixes the issue? I haven't gotten around to reviewing yet...

**Comment by wangzhenassd** [comment]
I tried the example with the implementation on branch single_sc, it seems to work correctly. On develop, the bug can still be recreated.
![image](https://user-images.githubusercontent.com/17849882/102194972-3f33cd80-3ebe-11eb-8454-3f1502c23f77.png)

**Comment by lthurner** [comment]
Great, then I suggest integrating this as a test?

**Comment by wangzhenassd** [comment]
> Great, then I suggest integrating this as a test?

Yes, i can do it
