### ISSUE TITLE
Reopen an Issue: Warning due to impedance - unbalanced powerflow

### ISSUE THREAD

**Issue by AdrienGougeon** [e2nIEE/pandapower#1012]
Hello,
I opened an issue that was closed later for inactivity: https://github.com/e2nIEE/pandapower/issues/968
One of my colleague added some information on this issue but I don't know how to reopen it, can someone reopen it for me please (and delete this one) ?

Thank you

**Comment by rbolgaryn** [comment]
Hi @AdrienGougeon ,

thank you for the update, the old issue is reopened.
