### ISSUE TITLE
Huge Bug in the class IRWLSAlgorithm() 

### ISSUE THREAD

**Issue by FrankYinXF** [e2nIEE/pandapower#1022]
IRWLSAlgorithm() line 201 https://github.com/e2nIEE/pandapower/blob/develop/pandapower/estimation/algorithm/base.py

NameError: name 'r_inv' is not defined

**Comment by wangzhenassd** [comment]
It's not a bug, but in IRWLS user does not use r_inv but phi, because it updates the original weight "r_inv" iteratively.

**Comment by wangzhenassd** [comment]
Using the kind of word "huge bug" is not polite for discussion, it's better to simply say "A question about 'r_inv' in IRWLS algorithm"

**Comment by FrankYinXF** [comment]
Sorry for the unsuitable words.
Thank you very much for your contribution.

Cheers.
