### ISSUE TITLE
Bug in pandapower\plotting\collections.py

### ISSUE THREAD

**Issue by tulguur** [e2nIEE/pandapower#1032]
I found a bug in line 945:
gens = get_index_array(sgens, net.sgen.index)
It shoud be :
sgens = get_index_array(sgens, net.sgen.index)
thx！

**Comment by rbolgaryn** [comment]
Thank you @tulguur ! Would you like to open a pull request?

**Comment by tulguur** [comment]
You are welcome.I am very sorry.I am very busy these days. I would like to pull request in future.

**Comment by rbolgaryn** [comment]
I just checked, it was fixed 3 months ago.
