### ISSUE TITLE
Wrong Lat/Lon when plotting on map with plotly

### ISSUE THREAD

**Issue by fgonzalezvenegas** [e2nIEE/pandapower#1038]
I have a net with geodata already in WGS84 format. When I plot using simply_plotly(net, on_map=True), the Lat/Lon get crossed (i.e. Latitude in Longitude and vice versa), not obtaining the plot in the desired location and rotated 90 degrees.

If I plot using plotly without map, there is no problem.

I'm using pandapower 2.4.0 and plotly 4.5.0

**Comment by jwiemer112** [comment]
Hey, 

sorry for the late responce! However thanks for your post and your interest in pandapower. I digged into the problem. Checkout Issue #1118 and pull request #1122.

Feedl free to give me feedback.

Greetz Jan
