### ISSUE TITLE
KeyError: 'continue_on_divergence' using run_control

### ISSUE THREAD

**Issue by SteffenMeinecke** [e2nIEE/pandapower#1067]
Using the following code, the attached error occur. It seems that with some changes in the code, the key `continue_on_divergence` got lost.

```
import pandapower as pp
from pandapower.control import run_control

net = pp.from_json("testnet.json")
run_control(net, calculate_voltage_anlges=True, max_iter=100)
```
![Error Message](https://user-images.githubusercontent.com/23652187/102343273-9f983d00-3f9a-11eb-9417-01635e778897.jpg)
[testnet.zip](https://github.com/e2nIEE/pandapower/files/5702349/testnet.zip)

**Comment by SimonRubenDrauz** [comment]
should be solved. Could you check it!

**Comment by rbolgaryn** [comment]
Hi @SteffenMeinecke , can the Issue be closed?

**Comment by SteffenMeinecke** [comment]
No, nothing has been done yet :(
