### ISSUE TITLE
Does pandapower have a single phase simulator?

### ISSUE THREAD

**Issue by gus0k** [e2nIEE/pandapower#1068]
Hello, 

I'm trying to understand how to read the parameters of the different data structures.

I am currently writing the optimization problem of a market with gird constraints and later I am using pandapower to simulate the grid with the values obtained from my optimization problem to get the real voltage deviations, line loadings, line losses, etc.

I am having some trouble with the maximum current bound. My optimization problem is single phase, and I understood that the parameter `max_i_ka` was for a single phase network. Nevertheless, I did not get good results until I tried to use sqrt(3) * `max_i_ka` as the bound (in my optimization problem). 

Is this the expected transformation from pandapower data to a single phase system?

If that is indeed the case, is the pandapower simulation always a three phase one (albeit balanced)?

Best,

**Comment by rbolgaryn** [comment]
Hi @gus0k ,

this seems to be a question about using pandapower, and not a specific issue with a bug.
We started to use the discussions tab for such questions. 
Please reopen your question in the discussions Tab!

Roman
