### ISSUE TITLE
OPF and timeseries

### ISSUE THREAD

**Issue by m-shak** [e2nIEE/pandapower#1096]
Hi,

Can I run OPF and timeseries in the same program?

I have the demand profiles and the RE profiles, and I want to generate the other power plant profiles, it this possible with Pandapower?
Thanks
Mohammad

**Comment by rbolgaryn** [comment]
Hi Mohammad, 

you should be able to pass a function to replace pp.runpp as a keyword argument of pp.run_timeseries, e.g. run = pp.runopp

**Comment by rbolgaryn** [comment]
Closing for now, but feel free to reopen if it doesn't solve it for you.
