### ISSUE TITLE
run_control: Configurable condition when to raise ControllerNotConverged

### ISSUE THREAD

**Issue by rbolgaryn** [e2nIEE/pandapower#1103]
There can be a use-case when it doesn't matter whether all controllers converged in all levels, as long as the controllers in the last level have converged. At the moment, the control loop requires all controllers to be converged in a level before it proceeds to the next level. 

I suggest adding a parameter whether the user expects every controller level to converge or just the last one.

**Comment by SimonRubenDrauz** [comment]
Can be closed, @rbolgaryn ?

**Comment by rbolgaryn** [comment]
Yes, can be closed.

To document it here, a keyword parameter "check_each_level" (default True) can be passed to ignore convergence in every level but the last one.
