### ISSUE TITLE
Calling one bis Information 

### ISSUE THREAD

**Issue by mohammadswaiti** [e2nIEE/pandapower#1133]
Hallo,  if i have a Networking with ten Busse und i wann to get the Information öffnen just one bus what Schuld i do 

Like the folwing example 
import pandapower as pp
S = pp.create(pp.create_bus(net,  vn_kv 110)
X = pp.create(pp.create_bus(net,  vn_kv 110)
How to get just the Info of bus x 

With best regardes

**Comment by wangzhenassd** [comment]
Please reformulate your question in english, in a way that people can understand, as well as code example which is supposed to recreate the problem
