### ISSUE TITLE
Load Flow Convergence Issue

### ISSUE THREAD

**Issue by prakash-kr1993** [e2nIEE/pandapower#1153]
Since the load flow convergence is a very sensitive task, is there any way the pandapower users can input the initial conditions from other simulation environments (e.g., input the PSSE load flow results as initial conditions in pandapower to achieve convergence)?

**Comment by rbolgaryn** [comment]
HI @prakash-kr1993 ,

you could manually set the values in the result tables and then use the parameter init='results' with pp.runpp
