### ISSUE TITLE
Multiple external girds

### ISSUE THREAD

**Issue by AlemsegedWeldeyesus** [e2nIEE/pandapower#1163]
We want to model a network that involves many transmission lines and multiple external grids, and then run OPF. Is having multiple external grids still an issue?

**Comment by rbolgaryn** [comment]
Hi @AlemsegedWeldeyesus ,

pandapower supports having multiple ext_grid elements in the grid.

Also, take a look at #771 

Roman

**Comment by lthurner** [comment]
In power flow calculation, it is definetly supported and well tested.

In OPF, it should work as well, but I am not sure if it es thouroughly tested yet. Did you try to put together a minimal example to check if it works @AlemsegedWeldeyesus ?

**Comment by AlemsegedWeldeyesus** [comment]
I have tried to put a minimal example. The power flow calculation is fine. But when I try to run OPF, I get the following message at the end. "Multiple connected slacks in one area found. This would probably lead to non-convergence of the OPF. I'll change all but one slack (ext_grid) to gens. To avoid undesired behaviour, rather convert the slacks to gens yourself and set slack=True for one of them."

**Comment by rbolgaryn** [comment]
have you tried converting all slacks to gen elements with the parameter slack=True?

**Comment by rbolgaryn** [comment]
Closing the issue due to inactivity.

@AlemsegedWeldeyesus , please reopen if you have any updates about the issue.

Roman

**Comment by PB-vines** [comment]
RE even if you change the external grids to gens with slack = True, you get the same warning.
