### ISSUE TITLE
Is there any way to change all loads at one time in cases? 

### ISSUE THREAD

**Issue by ChengweiLou** [e2nIEE/pandapower#1166]
e.g There is a standard case33bw.
I want to two times every load and see the result again.
Are there any way better to change load rather than changing each load in json file?
Thank you.

**Comment by ascheidl** [comment]
like all other elements, loads are stored in a pandas DataFrame

all methods to alter a DataFrame will work

for example:

net.load.loc[:, "p_mw"] *= 2

**Comment by ChengweiLou** [comment]
Thank you. It works.
