### ISSUE TITLE
Question: Power flow problems with CIGRE LV network

### ISSUE THREAD

**Issue by Pimpussorn** [e2nIEE/pandapower#1176]
Hello everyone!

I'm new to github and just beginning a project with pandapower. In my project, I will create some EMS logics to manage power flow between a village and CIGRE network. Each time when I simulate one EMS, a new CIGRE net will be created pandapower.networks.create_cigre_network_lv() and the power exchange to grid will be passed to the net through ConstControl(). My problem is that when I run my simulation consecutively by for-loop , the net somehow doesn't reset and the power flow/ load of the later run EMS logic increases drastically. Below is a part of my code, run_type represents each EMS logic I want to test. The CIGRE network will be created in run_grid().

`
for r in run_type:
    for scenario in test_scenario:
        if scenario == 1:

            # Prosumer(name, house_type, scenario, days, resolution, el_loads, th_loads)
            for i in range(0,len(house_index)):

            # data = np.hstack((h.EMS.P_feedin_neg_icl for h in house_list))*(-1) # due to sign convention of CIGRE model
            '''Prepare houses at each node'''
            column_names = ['Node_{}'.format(i + 1) for i in range(0, 5)]
            power_hh_to_grid = pd.DataFrame(columns=column_names) #pd.DataFrame(data, columns=column_names)

            for i in range(0,5): # Node number
                power_hh_to_grid.loc[:, 'Node_{}'.format(i+1)] = sum((-house_combination[i][m]) * house_list[m].EMS.P_feedin_neg_icl for m in range(0,len(house_list))).flatten()

            '''Save power flow'''
            save = pd.DataFrame(power_hh_to_grid.to_numpy(),index=house_list[0].index,columns=['R11','R15','R16','R17','R18'])
            save.to_csv('power_exchange2grid_winter_run{}_{}.csv'.format(r,day_now))
            '''Change file/folder name'''
            #tempfile.gettempdir()
            output_dir = os.path.join(output_dir_grid, "time_series_run{}_scenario{}_v4_{}".format(r,scenario,day_now))
            print("Results can be found in your local temp folder: {}".format(output_dir))
            if not os.path.exists(output_dir):
                os.mkdir(output_dir)
            # net_end = run_grid(output_dir, power_hh_to_grid, datapoints_test)
            run_grid(output_dir, power_hh_to_grid, datapoints_test)`

Here is how my run_grid() looks like:`
def run_grid(output_dir, data, datapoints):
    # 1. create test net
    #net = simple_test_net()
    net = nw.create_cigre_network_lv()

    # 2. create (random) data source
    n_timesteps = datapoints
    profiles, ds = load_input(data=data)
    # profiles, ds = create_data_source(n_timesteps) # n_timesteps
    # 3. create controllers (to control P values of the load and the sgen)
    net = create_controllers(net, ds)

    # time steps to be calculated. Could also be a list with non-consecutive time steps
    time_steps = range(0, n_timesteps)

    # 4. the output writer with the desired results to be stored to files.
    ow = create_output_writer(net, time_steps, output_dir)

    # 5. the main time series function
    run_timeseries(net, time_steps)

    '''Try to clear memory'''
    # for element in dir():
    #     if element[0:2] != "__":
    #         del globals()[element]
    # del element
    del n_timesteps
    del profiles
    del ds
    del time_steps
    del ow
    del net
    gc.collect()
`
This is to assign load to each residential node of CIGRE network

`def create_controllers(net, ds):
    ConstControl(net, element='load', variable='p_mw', element_index=[1],
                 data_source=ds, profile_name=["load1_p"])
    ConstControl(net, element='load', variable='p_mw', element_index=[2],
                 data_source=ds, profile_name=["load2_p"])
    ConstControl(net, element='load', variable='p_mw', element_index=[3],
                 data_source=ds, profile_name=["load3_p"])
    ConstControl(net, element='load', variable='p_mw', element_index=[4],
                 data_source=ds, profile_name=["load4_p"])
    ConstControl(net, element='load', variable='p_mw', element_index=[5],
                 data_source=ds, profile_name=["load5_p"])
    # ConstControl(net, element='sgen', variable='p_mw', element_index=[0],
    #              data_source=ds, profile_name=["sgen1_p"])
    return net
`
And here, these are my results. I expected that by doing the for-loop, it should not effect the results of the next EMS. But it seems to matter which EMS is called first. The first picture, I set run_type = ['Run0',Run4'].
![image](https://user-images.githubusercontent.com/81357072/112489354-a810c880-8d7e-11eb-8bab-99f4754ac915.png)
Here, I set run_type = ['Run4',Run0']
![image](https://user-images.githubusercontent.com/81357072/112489445-bb239880-8d7e-11eb-9fff-8b9ba08a9ea5.png)

Thank you if you read this far. I would be appreciated by any idea or recommendation.

**Comment by rbolgaryn** [comment]
Hi @Pimpussorn ,

we can help you if you can isolate the issue with pandapower and provide a very minimal example. Given the way you described the problem, we would need to debug the code from your project, which we cannot offer.
If you can reduce the example and narrow down the issue, feel free to re-open. 

Best regards,
Roman
