### ISSUE TITLE
Question: Are there Include Lagrange multipliers in results from AC OPF using PowerModels.jl?

### ISSUE THREAD

**Issue by Crueda96** [e2nIEE/pandapower#1182]
Is it possible to calculate the nodal LMP prices for each bus in the AC OPF case with PowerModels?

**Comment by MMajidi137** [comment]
@wangzhenassd  please check the available objective function from powermodels in [here](https://lanl-ansi.github.io/PowerModels.jl/stable/objective/). if the model is not available then u need to define it as a new model of powermodels via [PandaModels.jl](https://github.com/e2nIEE/PandaModels.jl) then call it from pandapower.

**Comment by wangzhenassd** [comment]
@Crueda96

**Comment by SteffenMeinecke** [comment]
closed due to inactivity
