### ISSUE TITLE
Some inconsistencies in the example grids

### ISSUE THREAD

**Issue by suschhapg** [e2nIEE/pandapower#1195]
Dear all,
we found a few inconsistencies in the example grid library:
* in the mv_oberrhein grid the external grid has a deprecated parameter 'sk_min'
* in several grids the switches have no names, e.g. in mv_oberrhein and example_simple (NAN values in the dataframe)
Hope this helps keeping the example library up to date.

**Comment by SteffenMeinecke** [comment]
@suschhapg Thanks for your suggestions for improvement!
