### ISSUE TITLE
parameters and keyword arguments in runpp

### ISSUE THREAD

**Issue by lthurner** [e2nIEE/pandapower#122]
Issue #117 lead to the discussion how many arguments we should provide in runpp and how they should be organized to guarantee flexibility while still maintaining clarity for the user. The idea was to move some of the more specialized runpp options to **kwargs:

- numba
- r_switch
- delta_q
- trafo3w_losses
- potential new parameter for #117

**Comment by jhmenke** [comment]
maybe we can use a parameter object (python dict)?

http://principles-wiki.net/patterns:parameter_object

**Comment by lthurner** [comment]
We have discussed this option before and decided against it. The main reason is that Python already offers the possibility to define options in a dictionary by default. This:

>options["pf_method"] ="..."
>pp.runpp(net, **options)

already works if one preferrs setting the options in a dictionary, so I don't see the benefit of explicitely introducing this. Changing to a dictionary would however remove all options from the runpp functions, so that the available parameters are not directly clear when inspecting the function.

Also, we already have the set_user_pf_options function that allows to store individual parameters that a re stored in a dictionary.

**Comment by jhmenke** [comment]
ah yes, i think i even was at that discussion.

**Comment by lthurner** [comment]
Implemented as discussed with #156. init_vm_pu and init_va_degree where added to the **kwargs as per #113
