### ISSUE TITLE
Power flow from PowerModels.

### ISSUE THREAD

**Issue by hitchenzhe** [e2nIEE/pandapower#1225]
Dear pandapower group,

I installed the julia and powermodel. I could also run opf in pandapower, it is nice.

I want to know, how to run power flow (not OPF) by calling the PowerModel.jl in Pandapower frame. I want to make everything in python.

**Comment by nlswn** [comment]
Sorry for reopening this issue, but are there any news in this regard? I'm also very interested in this feature.
