### ISSUE TITLE
Building a Controller- error in the code

### ISSUE THREAD

**Issue by angelinasyrri** [e2nIEE/pandapower#1245]
Dear pandapower team, 

I am trying to replicate the code given in the tutorials section named 'building a controller' and while I am using the exact same code as presented in the tutorial, the script is not running properly and I receive the following error. Any ideas what is it about? I am new to pandapower and though it might be a simple solution I cannot spot it at the moment. Any help would be much appreciated!

deprecated: output_writer should not be given to run_timeseries(). This overwrites the stored one in net.output_writer.
Progress: |████████------------------------------------------| 16.7% CompleteC:\Users\...\anaconda3\envs\work_env\lib\site-packages\pandapower\control\util\auxiliary.py:130: FutureWarning: Index.__and__ operating as a set operation is deprecated, in the future this will be a logical operation matching Series.__and__.  Use index.intersection(other) instead
  idx &= net.controller.index[net.controller[df_key] == parameters[df_key]]
Traceback (most recent call last):

  File "C:\...\development\python scripts\storage_controller_github.py", line 119, in <module>
    ts.run_timeseries(net, time_steps=range(0, 6), output_writer=ow)

  File "C:\..l\anaconda3\envs\work_env\lib\site-packages\pandapower\timeseries\run_time_series.py", line 346, in run_timeseries
    run_loop(net, ts_variables, **kwargs)

  File "C:\..\anaconda3\envs\work_env\lib\site-packages\pandapower\timeseries\run_time_series.py", line 318, in run_loop
    run_time_step(net, time_step, ts_variables, run_control_fct, output_writer_fct, **kwargs)

  File "C:\..\anaconda3\envs\work_env\lib\site-packages\pandapower\timeseries\run_time_series.py", line 117, in run_time_step
    control_time_step(ts_variables['controller_order'], time_step)

  File "C:\..\anaconda3\envs\work_env\lib\site-packages\pandapower\timeseries\run_time_series.py", line 84, in control_time_step
    ctrl.time_step(net, time_step)

TypeError: time_step() takes 2 positional arguments but 3 were given

**Comment by rbolgaryn** [comment]
Hi @angelinasyrri ,

this particular warning is fixed in the latest version on develop:

FutureWarning: Index.and operating as a set operation is deprecated, in the future this will be a logical operation matching Series.and. Use index.intersection(other) instead
idx &= net.controller.index[net.controller[df_key] == parameters[df_key]]

The other bug was due to the outdated code in the tutorial, it will be fixed soon.

Best regards,
Roman
