### ISSUE TITLE
Generator type for volt/var control

### ISSUE THREAD

**Issue by kosmylo** [e2nIEE/pandapower#1259]
What kind of generator type should I use if I want to simulate a Photovoltaic, which is controlled externally by a volt/var smart inverter?

**Comment by rbolgaryn** [comment]
Hi @kosmylo ,

I suggest using an sgen element and then writing a controller around it that adjusts Q values based on the desired characteristic.

**Comment by rbolgaryn** [comment]
You can check the characteristic control and see if it is useful for you:

https://github.com/e2nIEE/pandapower/blob/develop/pandapower/control/controller/characteristic_control.py
