### ISSUE TITLE
Order of Ybus matrix

### ISSUE THREAD

**Issue by hitchenzhe** [e2nIEE/pandapower#1284]
Hello, 

I have a question on Order of Ybus matrix when I get it.
`vol_phasor = net.res_bus`
`Ybus = net._ppc['internal']['Ybus'].toarray()`

The results are order in 0, 1, 10, 11...19, 2, 20, 21.....

How to get results with natural order0, 1, 2, 3...., easy to do with `vol_phasor = net.res_bus.sort_index(ascending=True)`, but how about Ybus matrix? The row and colunm are all in the first type of order.

**Comment by lthurner** [comment]
The mapping to internal data structures is explained in detail in this tutorial: https://github.com/e2nIEE/pandapower/blob/develop/tutorials/internal_datastructure.ipynb
