### ISSUE TITLE
Piecewise constant functions

### ISSUE THREAD

**Issue by kalsheh2** [e2nIEE/pandapower#131]
piecewise constant functions are piecewise linear, but couldn't define them using create_piecewise_linear_cost, is it possible?

**Comment by friederikemeier** [comment]
Hi, 

This should be possible. Can you give an example of your failing code? Kind regards!

**Comment by kalsheh2** [comment]
I'm trying to test the following function: 

pp.create_piecewise_linear_cost(net, 1, "gen", np.array([[-1e5, 0], [-1e5/2, 50], [0, 120]]))

And the goal is to define a staircase function with marginal costs 0, 50, and 120. This is interpreted as a bidding process where market participants (generators) bid marginal costs for some ranges (block bidding). 

Thanks!

**Comment by friederikemeier** [comment]
With this you would create two linear functions. You need two ending points for each segment of a constant function!
You need to define it like this:
pp.create_piecewise_linear_cost(net, 1, "gen", np.array([[-1e5, 0], [-1e5/2, 0], [-1e5/2, 50], ,[0, 50], [0, 120], [1e9, 120]])) 

I assumed that you mean a staircase function like this:

f(x) = 
0, -1e5 <x< -1e5/2 
50, -1e5/2 < x < 0
120, 0<x<1e9

I assumed 1e9 to be high enough to make it seem like 120, 0<x.

Does this help?

**Comment by kalsheh2** [comment]
Thanks! That helps understand the situation, but I still get an error. 
I am trying to modify opf_basic.ipynb to test a simple staircase function. Tried the following (2 blocks) 

pp.create_piecewise_linear_cost(net, 1, "gen", np.array([[-10e5, 0],[(-10e5)/2, 0],[(-10e5)/2, 50],[0, 50]]))

but got the following error: "Piecewise linear costs need to be defined in ascending order: p0 < p1 < ... < pn". Changed it to something like this 

pp.create_piecewise_linear_cost(net, 1, "gen", np.array([[-10e5, 0],[(-10e5)/2, 0],[(-10e5)/2+0.00001, 50],[0, 50]]))

and it was defined correctly. However, now OPF doesn't converge! And I'm suspecting it's because there is something missing in the range (-10e5)/2 <x < (-10e5)/2+0.00001. 

If there are working examples, that would be great. As a user, I think the ability to conveniently define staircase functions is important. Nearly most real deregulated electricity markets accept staircase bids. Also, I notice that it is required to have the same number of blocks for all generators, it would be great if that can be relaxed. I'm not trying to sound needy/demanding here, and I appreciate all of your great efforts, but I'm trying to use the tool and these are the things I'm facing. I'll be happy to help/discuss things too. 

Thanks again for your help!

**Comment by friederikemeier** [comment]
I guess that this is not possible with the pypower/matpower OPF that we use internally, as the gradients are zero which makes it seem like there is no enhancement of the cost function with variation of the feed in. The pypower/matpower OPF is based on an interior point solver, which is not ideal for this kind of optimization problem. I experienced problems with unsteady cost functions earlier. A workaround might be to seperate the generator for each segment of the cost function as it was done in #99.

So to speak

1 generator with p_min_kw =  -1e5/2 and piecewise constant costs 0
1 generator with p_min_kw =  -1e5/2 and piecewise constant costs 50
p_max_kw is 0 for both.

The the OPF will always use the one with the costs 0 first before using the one with the higher costs. I am not sure if this will work, but this approach worked unexpectedly in #99 so it's worth a try.

**Comment by friederikemeier** [comment]
One question: Does the dcopf converge for this problem? This could give us a valid starting solution which enhances convergence.

**Comment by kalsheh2** [comment]
Thanks for the useful insights. Are you asking about dcopf before splitting the generator or after?

**Comment by friederikemeier** [comment]
Both would be interesting as it could give us some starting points for the ac opf. you can as well experiment with the tolerances, you can find a documentation of the tolerances in the matpower documentation.

**Comment by kalsheh2** [comment]
Will get back to you on this.

**Comment by kalsheh2** [comment]
I think what happened is that I mixed the actual cost "in $" (which is typically quadratic or piecewise-linear) with incremental cost "$/MWh" (which is typically a staircase). Thus, my staircase function "$/MWh" can be represented as  piecewise-linear "in $". 

Going back to our example, with incremental cost "$/MWh" being 

f(x) =
0, -1e5 <x< -1e5/2
50, -1e5/2 < x < 0
120, 0<x<1e9

The function we actually need to define is its integral, which is piecewise linear and should work. Regarding #99, I guess it didn't work in the beginning because the solver is expecting an increasing function, and having uneven slopes breaks that.

**Comment by friederikemeier** [comment]
Uneven slopes is not working if one is negative and the other positive. In your case, both of your segments do have positive slopes, that should work! 
I think your initial definition was right then:
pp.create_piecewise_linear_cost(net, 1, "gen", np.array([[-1e5, 0], [-1e5/2, 50], [0, 120]]))
and I can't see any reason why this should not work. Try broaden the constraints and tolerances.

Please have a look at the file pandapower/test/opf/test_cost_pwl.py and at the function test_cost_piecewise_linear_sgen_uneven_slopes() where this case is tested. You can use this as an example code.

**Comment by friederikemeier** [comment]
I think this can be closed now.
