### ISSUE TITLE
'plot_gens' unexpected in simple_plot()

### ISSUE THREAD

**Issue by ivanightingale** [e2nIEE/pandapower#1322]
It seems that `plot_gens` is an argument in `simple_plot()`, but is not documented. When attempting to set `plot_gens` when calling `simple_plot()`, I get the following error:

> TypeError: simple_plot() got an unexpected keyword argument 'plot_gens'

Version: 2.7.0

**Comment by rbolgaryn** [comment]
I added the docstring for the parameter.

@ivanightingale can you please check if you are using the develop branch?

Roman

**Comment by ivanightingale** [comment]
@rbolgaryn That reminds me. No, I was using the release 2.7.0.

**Comment by rbolgaryn** [comment]
Thanks for the update @ivanightingale !

OK, then I'm closing.
