### ISSUE TITLE
Inquiries related to the power flow results of DC lines

### ISSUE THREAD

**Issue by chochon** [e2nIEE/pandapower#1340]
Hello,
I am a new user of pandapower.
I am inquiring related with the power flow result of HVDC in my designed network. 

I modeled HVDC line in AC transmission network like this example network. 

![13](https://user-images.githubusercontent.com/87401337/131936784-d7154da0-9a57-423e-88c1-4d11d70d4b5c.png)

Then, I simulated power flow. 

`pp.runpp(net, algorithm ='nr', init='auto', calculate_voltage_angles='auto', enforce_q_lims='True', max_iteration=20, trafo_loading="power")`

However, only the reactive power of generators are considered of their q_limit but dc lines are not as following:

<initial values>
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/user/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/user/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>

p_mw | loss_percent | loss_mw | vm_from_pu | vm_to_pu | max_p_mw | min_q_from_mvar | min_q_to_mvar | max_q_from_mvar | max_q_to_mvar | in_service
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
75 | 0.25 | 0.185 | 1.0395 | 1.0003 | 86.25 | 20.09619 | 31.83561 | 77.48224 | 79.26167 | TRUE
75 | 0.25 | 0.185 | 1.0395 | 1.0003 | 86.25 | 20.09619 | 31.83561 | 77.48224 | 79.26167 | TRUE
150.6 | 0.99 | 1.485 | 1.04 | 1.006 | 173.19 | 26.44905 | 57.57961 | 139.2162 | 150.1418 | TRUE
150.6 | 0.99 | 1.485 | 1.04 | 1.006 | 173.19 | 26.44905 | 57.57961 | 139.2162 | 150.1418 | TRUE
150.5 | 3.83 | 5.765 | 1.04 | 1 | 173.075 | 0 | 0 | 50 | 50 | TRUE

</body>

</html>

<power flow results>
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/user/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/user/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link=blue vlink=purple>

  | p_from_mw | q_from_mvar | p_to_mw | q_to_mvar | pl_mw | vm_from_pu | va_from_degree | vm_to_pu | va_to_degree
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
0 | 75 | -23.63533598 | -74.6275 | -31.83561 | 0.3725 | 1.0395 | -4.947572169 | 1.013501057 | 0.302699112
1 | 75 | -23.63533598 | -74.6275 | -31.83561 | 0.3725 | 1.0395 | -4.947572169 | 1.013501057 | 0.302699112
2 | 150.6 | -26.44905 | -147.62406 | -57.57961 | 2.97594 | 1.043751783 | -6.871542803 | 1.030790042 | 1.237667109
3 | 150.6 | -26.44905 | -147.62406 | -57.57961 | 2.97594 | 1.043751783 | -6.871542803 | 1.030790042 | 1.237667109
4 | 150.5 | 0 | -138.97085 | 0 | 11.52915 | 1.041071558 | -5.367258667 | 1.00725528 | 2.545249391

</body>

</html>

I hope dc lines are also operating within their reactive power limits. How can I solve this problem?
Please help me.

Thanks,

**Comment by SteffenMeinecke** [comment]
Hi @chochon 
you should use `enforce_q_lims=True` instead of `enforce_q_lims='True'`. If it still doesn't work properly, you could state here the grid data for a complete minimal example.

**Comment by SteffenMeinecke** [comment]
closed due to no further questions
