### ISSUE TITLE
Branch short-circuit currents for 1ph fault

### ISSUE THREAD

**Issue by msgr1** [e2nIEE/pandapower#1341]
Hi guys, 

is it somehow possible to get short-circuit currents for each-phase (L1, L2, L3 or "sick/healthy" phases)  for contributing branches (lines, trafos) in case of 1ph short-circuit?
I am running pandapower 2.7.0.

Thanks :)

**Comment by rbolgaryn** [comment]
Hi @msgr1 ,

unfortunately no, it is not possible at the moment.

Roman
