### ISSUE TITLE
How to divide net to two subnets and run `rundcpp` in each subnet.

### ISSUE THREAD

**Issue by eendru** [e2nIEE/pandapower#1342]
For example, if I drop some buses and lines from original net and obtain two subnet, Which are no connected.
How to run `rundcpp` in each subnetwork ?

My pipeline looks like:

1. Load some of default case-s (case30 for example).
2. Drop some buses (and lines).
2. call `pandapower.topology.connected_components(...)` for obtain connected clusters.
3. Add for each subnet external grid (or if there generator is in subnet, convert generator to external grid)
4. Call rundcpp() for each subnet.

But I recieve an error: 

```
Ext grids with different voltage angle setpoints connected to the same bus
```

What am I doing wrong ?

**Comment by ascheidl** [comment]
use can use pandapower.select_subnet to cut a part of a grid
