### ISSUE TITLE
Apparent bug in simply_plotly(), where trafo3w overrides the traces for trafo

### ISSUE THREAD

**Issue by junmuz** [e2nIEE/pandapower#1346]
It appears that there is a bug inside the `simple_plotly` method (https://github.com/e2nIEE/pandapower/blob/develop/pandapower/plotting/plotly/simple_plotly.py#L201). Traces for `trafo3w` will always override the traces for `trafo`

**Comment by SteffenMeinecke** [comment]
Thanks @junmuz for raising this issue and also fixing it directly
