### ISSUE TITLE
Scaling included in OPF? Documentation unclear

### ISSUE THREAD

**Issue by thomaswolgast** [e2nIEE/pandapower#1353]
I have a small question how the scaling is considered in the OPF.

Is the scaling automatically considered or not? Is it `net.res_sgen.p_mw < net.sgen.max_p_mw` or is it `net.res_sgen.p_mw < net.sgen.max_p_mw * net.sgen.scaling`?

Or in other words, do I need to consider the scaling myself when I define the constraints? 
Say I want to use the current `p_mw` as `max_p_mw`.

Is it `net.sgen.max_p_mw = net.sgen.p_mw` or should I use `net.sgen.p_mw * net.sgen.scaling` instead?

I could not find this explicitly stated in the docs. I hope I did not oversee it.

**Comment by SteffenMeinecke** [comment]
`scaling` multiplys with `p_mw` and `q_mvar` but not with limits. I am concretizing this in the documentation.
