### ISSUE TITLE
std_type in create_lines

### ISSUE THREAD

**Issue by SimonRubenDrauz** [e2nIEE/pandapower#1375]
Why is it in create_lines not possible to pass a list of std_types? Instead it is only possible to pass one std_type for all lines.

**Comment by SteffenMeinecke** [comment]
True issue, imho.
Can you fix it?

**Comment by SimonRubenDrauz** [comment]
Guess I fixed it. Please check out #1388 !

**Comment by SteffenMeinecke** [comment]
perfect looks good. thanks
