### ISSUE TITLE
Need to example for time simulation

### ISSUE THREAD

**Issue by chochon** [e2nIEE/pandapower#1376]
Hello,

I am a beginner of pandapower. 
I want to make a code for time simulation using pandapower as following:

 `t_init = 0 sec
t_step = 1.0/120 sec
t_stop = 10 sec

while t_init <= t_stop:
t_init = t_init + t_step`

I have already read the documents in pandapower and I have to use 'ConstControl' and 'timeseries.run_timeseries(net)' function.

However, I can't clearly understand the definition of time step in time series simulation of Pandapower.
Is it just time step or end time?
If I want to make like above, how should I do?

In addition, I want to get some template or example (CSV file) for element and time step excluding the provided example in Jupyter notebook viewer. Please help me. 

Oh, How can I measure and monitor the system frequency during the time-series simulation?

Thanks,

**Comment by rbolgaryn** [comment]
Dear @chochon ,

you can take a look at pandapower tutorials for timeseries simulation:

https://github.com/e2nIEE/pandapower/tree/develop/tutorials

As for the frequency, the timeseries simulation is still a static simulation and does not provide the possibility to calculate frequency.

Best regards,
Roman
