### ISSUE TITLE
AC power flow converge but ACOPF not converge

### ISSUE THREAD

**Issue by xfangnrel** [e2nIEE/pandapower#1387]
Hi,
I have a case which can have a converged AC power flow but the AC OPF can't converge. Do you know what might be the reason?

--> 357     _optimal_powerflow(net, verbose, suppress_warnings, **kwargs)
    358 
    359 

c:\users\xfang\gitrepos\pandapower-master\pandapower\optimal_powerflow.py in _optimal_powerflow(net, verbose, suppress_warnings, **kwargs)
     68 
     69     if not result["success"]:
---> 70         raise OPFNotConverged("Optimal Power Flow did not converge!")
     71 
     72     # ppci doesn't contain out of service elements, but ppc does -> copy results accordingly

OPFNotConverged: Optimal Power Flow did not converge!

Thanks a lot,
Xin

**Comment by xfangnrel** [comment]
This issue has been solved. Thanks.

**Comment by fgo97** [comment]
How did you solve this? 
Thanks a lot, Franz
