### ISSUE TITLE
The problem of node label mismatch caused by the wrong format of geographic data.

### ISSUE THREAD

**Issue by roki1031** [e2nIEE/pandapower#1436]
Hi~
 On the journey of learning pandapower, I found that the Bus id in the grid structure diagram drawn by the function `plot.create_annotation_collection` does not seem to match the actual bus.
![image](https://user-images.githubusercontent.com/52522880/147330906-41293ccc-2b71-4dc2-bce8-011d8951d3fd.png)
![image](https://user-images.githubusercontent.com/52522880/147330966-c838c9d0-5c5e-4990-90e4-670bfaeb37c8.png)
     As you can see, the beginning and end nodes of line 1 should be bus 0 and bus 4, but in the grid diagram they are bus 0 and bus 8.  So i digged into the source code and found that it was caused by the wrong format of geographic data.
After running this line of code, the grid diagram is correct. 
`net.bus_geodata.sort_index(inplace=True)`
     
![image](https://user-images.githubusercontent.com/52522880/147331410-471b2800-d26d-4fcf-aaa3-36ecc7fbdb7a.png)

**Comment by rbolgaryn** [comment]
Thank you for finding this problem, @roki1031 !

I think the solution should not be sort_index, for the case if the bus indices in net.bus are not sorted. I think a better solution would be to use the indices of net.bus when using net.bus_geodata:

net.bus_geodata.loc[net.bus.index]

Best regards,
Roman

**Comment by rbolgaryn** [comment]
I looked at the source code of create_annotation_collection, and it just takes texts and coords as arguments.

So it is entirely the responsibility of the user to make sure that the order of texts and coordinates match.

Roman
