### ISSUE TITLE
Why does Panda Power not converge?

### ISSUE THREAD

**Issue by Ilyass-A** [e2nIEE/pandapower#1439]
Hi Guys,
I have a problem with the conversion of my electrical grid, when I want to add a new line from a generation point to a consumption point. The GOAL and Reason to add this new line is that the generator and the consumptions points have to meet the N-1 criterion. I tried different approaches but couldn't find my mistakes. My original electrical grid in the figure down below converts, but as I said when I try for example to add another line from Bus 5 to Bus 3 it doesn't converge. 

This is my CODE: https://github.com/Ilyass-A/PandaPower/blob/main/Grid_Github.ipynb

This my grid:

![System_phase_1](https://user-images.githubusercontent.com/75802671/147600387-8df9219f-fb60-4743-9703-b687a4044add.jpg)

**Comment by rbolgaryn** [comment]
Hi @Ilyass-A ,

there can be many reasons for why a power flow calculation does not converge. 

You can use the pandapower.diagnostic function to check for the most common reasons. Hopefully, it will point you in the right direction.

Roman
