### ISSUE TITLE
drop pandas < 1.0

### ISSUE THREAD

**Issue by rbolgaryn** [e2nIEE/pandapower#1481]
pandas 1.0 was released 2 years ago, and we still have multiple checks for pandas versions for even 0.2

For context:

v0.20.3 (July 7, 2017)

v0.23.0 (May 15, 2018)

1.0.0 (January 29, 2020)

Latest: 1.4.0 (Jan 22, 2022)

I think requiring pandas >=1.0 is reasonable because 1.0 dropped many of announced deprecations, and was released long enough ago. This would simplify code by allowing to drop checking of multiple pandas versions. Besides, we do not really test pandapower with older pandas versions, which is also a potential risk.

**Comment by jkisse** [comment]
now, pandas >= 1.0 is required
