### ISSUE TITLE
Result Sgen in Oberrhein network after powerflow is zero

### ISSUE THREAD

**Issue by Arjunayodya** [e2nIEE/pandapower#1489]
I tried some power flow calculations using Oberrhein network. after doing a power flow the result of Sgen is zero for all active and reactive power
![Capture](https://user-images.githubusercontent.com/65343360/153019682-3837174f-74c8-4d0e-b2b7-b23c80043386.PNG)

kindly assist with why this happens?

**Comment by jkisse** [comment]
This is because the `net.sgen.scaling` column is `0` by default. If you set  `net.sgen.scaling = 1` you should get the expected results in `net.res_sgen`

**Comment by Arjunayodya** [comment]
Thank you for the quick reply and the solution worked

**Comment by jkisse** [comment]
You're welcome. Just one more note: This is not a bug but a feature ;-) when you load the MV Oberrhein network, you can pass the argument "scenario". `net = nw.mv_oberrhein(scenario="load")` is the default and has all sgens scaled to 0. `scenario="generation"` would scale all loads to 0.1 and the sgens to 0.8 (more details [here](https://pandapower.readthedocs.io/en/latest/networks/mv_oberrhein.html))
