### ISSUE TITLE
time series power flow analysis with N-1 Ccntingency

### ISSUE THREAD

**Issue by EngHailu** [e2nIEE/pandapower#1527]
Hell Pandapower Community,
I want to run a time series power flow analysis with N-1 contingency taking line outage information as time series information together with Sgen and load variability. I would like to know how to produce a controller with boolean value.
your help is appreciated.
EngHailu

**Comment by rbolgaryn** [comment]
you can write a custom function to replace pp.runpp and pass it to run_timeseries as an argument: run=custom_runpp
