### ISSUE TITLE
Handling multiple slack buses

### ISSUE THREAD

**Issue by AnkurArohi** [e2nIEE/pandapower#1531]
Is it possible for pandapower to handle multiple slack buses?
For example as a network operator it is very common problem to not know the P value at the network boundary.

Is it possible for pandapower to be able to run power flow with multiple such units in the same network?

**Comment by rbolgaryn** [comment]
Hi @AnkurArohi ,

I am assuming this issue is related to this one:

https://github.com/e2nIEE/pandapower/issues/1523

**Comment by rbolgaryn** [comment]
pandapower can have multiple slack buses, here a discussion from a different issue:

https://github.com/e2nIEE/pandapower/issues/1408

**Comment by rbolgaryn** [comment]
For the distributed slack functionality, refer to the tutorial:

https://github.com/e2nIEE/pandapower/blob/develop/tutorials/distributed_slack.ipynb
