### ISSUE TITLE
Simple Time Series Example

### ISSUE THREAD

**Issue by shashankm20** [e2nIEE/pandapower#1547]
Hi

I am trying to implement the time series for the loads with the help of the profile 
I used the constant controller to scale the loads but as I have two different profiles for the load I put profile_name = ['profile1','profile2']
when I am running time-series I am getting an error 
ValueError: Must have equal len keys and value when setting with an iterable

**Comment by rbolgaryn** [comment]
The element_index and profile_name must have equal lengths
