### ISSUE TITLE
Powerflow direction

### ISSUE THREAD

**Issue by yasirroni** [e2nIEE/pandapower#1555]
It is nice to see [load loading in color map](https://github.com/e2nIEE/pandapower/blob/dde080ba1a86bb042085852c9bcd3546e0fee6f5/tutorials/plotting_colormaps.ipynb)

Based on [basic plotting](https://github.com/e2nIEE/pandapower/blob/dde080ba1a86bb042085852c9bcd3546e0fee6f5/tutorials/plotting_basic.ipynb), we can add bus indexing.

Can you show an indexing showing the direction of power flow and their value? Thank you.

**Comment by rbolgaryn** [comment]
an easy way to do it would be to plot voltage angle (this approach is useful in transmission grids)

**Comment by yasirroni** [comment]
> an easy way to do it would be to plot voltage angle (this approach is useful in transmission grids)

Have you implemented it?

**Comment by rbolgaryn** [comment]
no
