### ISSUE TITLE
geopy missing or not available to pandapower

### ISSUE THREAD

**Issue by apigott** [e2nIEE/pandapower#1559]
I saw that issue #963 already asked this but it seems there hasn't been an update in the last year or so. Has there ever been an update to pandapower that reenables geopy plotting? Even the sample network shows up as blank for me, although the non-mapped versions work just fine.

**Comment by jwiemer112** [comment]
You can plot on a map using plotly.  The code mentioned in the linked Issue #963 is functional.
```

from pandapower.plotting.plotly import simple_plotly, pf_res_plotly
from pandapower.networks import mv_oberrhein
net = mv_oberrhein()
pf_res_plotly(net, on_map=True, projection='epsg:31467', map_style='dark')
```

With which network do you have problems? Remember that only networks with real geocoordinates like MV Oberrhein can be plotted on a map.

![grafik](https://user-images.githubusercontent.com/32835953/209146015-373eccd9-9c53-477a-8459-a8ddba8f4b6e.png)
