### ISSUE TITLE
plotting docs are broken

### ISSUE THREAD

**Issue by SteffenMeinecke** [e2nIEE/pandapower#1566]
the docstrings in
`Plotting Networks`: `Create collections` and `Create Colormaps`
`Plotly Network Plots`: `Create & Draw Traces` and `Create Colormaps`
`HTML`
are not displayed at https://pandapower.readthedocs.io/en/v2.9.0/plotting/matplotlib/create_collections.html

**Comment by jkisse** [comment]
fixed by #1840
