### ISSUE TITLE
How to kow the internal construction of ppc (dictionary)-not a bug

### ISSUE THREAD

**Issue by Arjunayodya** [e2nIEE/pandapower#1569]
I am curious to know how the PPC dictionary is constructed, which is used for every further calculation. So I would like to the theory (python implementation). I would be grateful if someone share how to access / how it is constructed

**Comment by rbolgaryn** [comment]
Dear @Arjunayodya ,

the ppc is constructed in the function _pd2ppc

Best regards,
Roman
