### ISSUE TITLE
Is it possible to evaluate PTDF with pandapower?

### ISSUE THREAD

**Issue by zhubangxian** [e2nIEE/pandapower#1572]
I'v already know that it is possible to evaluate PTDF with pypower, but for some reason I have to use pandapower instead of pypower, so is it possible to evaluate PTDF with pandapower?
For example, which function should I use if  I want to calculate the PTDF of the IEEE118 system?
Thanks a lot

**Comment by AnkurArohi** [comment]
Make PTDF.py
You need to give the network object input , branches of intrest which us optional

**Comment by zhubangxian** [comment]
Hi@AnkurArohi,

thank you for your comment. it works
