### ISSUE TITLE
Not a Bug:- Is it possible to perform Network Reduction in pandapower

### ISSUE THREAD

**Issue by AnkurArohi** [e2nIEE/pandapower#1576]
I would like to get some idea about network reduction , is there any module or any test or code snippet where in network reduction has been performed on the basis of voltage level  so to include all elements in the network wchich only belong to one voltage level?
Basically to replace the trafo with a PV gen or PQ sgen node?

Thanks well in advance

**Comment by rbolgaryn** [comment]
we just released this functionality to the develop branch, in pandapower.grid_equivalents

It would be very helpful if you try applying it and let us know your feedback.

Best regards, Roman

**Comment by AnkurArohi** [comment]
@rbolgaryn  Thank you 
What kind of network reductions are supported I mean at what level of granularity?
Are we substituting transformers with network element if yes which one and with what parameters?

It would be nice if you could share PR for this feature

**Comment by rbolgaryn** [comment]
Have a look at the tutorial:

https://github.com/e2nIEE/pandapower/blob/develop/tutorials/grid_equivalents.ipynb

**Comment by AnkurArohi** [comment]
Yes there are issues in understanding what I mean by network reduction and what is the aim in the commit

**Comment by AnkurArohi** [comment]
To understand this better I would request a meeting? what do you say? like online in zoom or any other app, max 30 mins would be enough

**Comment by AnkurArohi** [comment]
But @rbolgaryn  I had a quick look in the grid equivalent script!
Good work!!!

**Comment by SteffenMeinecke** [comment]
closed due to inactivity
