### ISSUE TITLE
Network plots labeling

### ISSUE THREAD

**Issue by buddih09** [e2nIEE/pandapower#1578]
This is a feature request:

I noticed that the current plot options do not allow for printing the values or labels, which is useful in some cases. 
Another useful option is to be able to apply different colors to different nodes and edges based on custom requirements (e.g., nodes where average load > something). Right now, you can only apply a color map based on the voltage or line loading. 

In my specific case, I wanted to highlight some nodes in the single line diagram, but in the end, realized there is no automatic way to do it. 

Will you be open to considering developing this feature in the future?

**Comment by jkisse** [comment]
Hello @buddih09,

have you seen the [plotting tutorial](https://github.com/e2nIEE/pandapower/blob/develop/tutorials/plotting_basic.ipynb)? It provides examples for annotated and highlighted elements.
