### ISSUE TITLE
pandapower says it would be suitable for Python 3.0

### ISSUE THREAD

**Issue by jkisse** [e2nIEE/pandapower#1583]
For example on [pypi](https://pypi.org/project/pandapower/), Python version = 3.0 is listed. Only 3.7 - 3.10 should be listed. There is the same issue for the label in the readme: 
![grafik](https://user-images.githubusercontent.com/44288328/168016766-2134d102-c6f9-46f2-b3d6-0befac2711c9.png)

This is likely related to the regex-expression in [setup.py line 29](https://github.com/e2nIEE/pandapower/blob/develop/setup.py#L29) 
`versions = set(re.findall('3.[7-9]', lines)) | set(re.findall('3.1[0-9]', lines))` and should be easy to fix.

**Comment by rbolgaryn** [comment]
I think we fixed it on develop

**Comment by rbolgaryn** [comment]
https://github.com/e2nIEE/pandapower/pull/1546
