### ISSUE TITLE
How to directly handle the results after using the Timeseries tool and not write them to the hard disk

### ISSUE THREAD

**Issue by EIHABALMUKASHFI** [e2nIEE/pandapower#1584]
Hello everyone,
I'm tring to obtain the active power after implementing timeseries without writing the results into excel in order to save time. I tried net.output_writer.object[0].output["res_bus.p_mw"]  , however, it doesn't work.I got this error 
'pandapowerNet' instance has no attribute 'output_writer'
 Do you have any other method to do this?

**Comment by rbolgaryn** [comment]
you should have the output_writer element table with the OutputWriter object in net after executing the timeseries calculation.

**Comment by EIHABALMUKASHFI** [comment]
I got it , thanks a lot

**Comment by rbolgaryn** [comment]
you are welcome!
