### ISSUE TITLE
PandaPower Toolbox.py get_connected_elements for respect_in_service = True leads to error

### ISSUE THREAD

**Issue by AnkurArohi** [e2nIEE/pandapower#1592]
Pandapower has a bug in the toolbox.py function where in for the respect_in_service = True option as parameter to find all the connected elements to a bus leads to the following error.
This is also the case for simple pandapower networks
Steps to reproduce:-
Load any exemplary pandapower network
Set at the bus of intrest a generator out of service
Call the folloeing function for that bus

elems_dict = pp.get_connected_elements_dict(network , bus, respect_switches=False,respect_in_service=True)

Error
packages/pandapower/toolbox.py", line 2894, in get_connected_elements
connected_elements -= set(element_table[~element_table.in_service].index)
UnboundLocalError: local variable 'element_table' referenced before assignment

**Comment by rbolgaryn** [comment]
Yes please!

**Comment by rbolgaryn** [comment]
You can make a fork of the repository in your GitHub account. Then you can push your changes to your fork of pandapower as a new branch. Afterwards, you can open a pull request and specify your feature-branch as the source branch and "develop" as the desctination branch.

**Comment by rbolgaryn** [comment]
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by AnkurArohi** [comment]
@rbolgaryn 
Done

**Comment by AnkurArohi** [comment]
@rbolgaryn 
Tests are working now

**Comment by AnkurArohi** [comment]
ok, I can try

**Comment by AnkurArohi** [comment]
Thanks @rbolgaryn
