### ISSUE TITLE
How to activate the storage unit in the grid for only  particular timesteps

### ISSUE THREAD

**Issue by EIHABALMUKASHFI** [e2nIEE/pandapower#1613]
Hello everyone, 
I'm working on a project about the effect on electric vehicles (EV) on the grid stability.I have residential loads, PV generation, and EV (V2G and G2V are allowed) .  I modeled EV as a storage unit. However, since the EV is not available during day hours, I am trying to only activate the storage between EV arrival and departure timestep and deactivate it at the rest of the day. Is it possible to do such a thing in pandapower?

**Comment by rbolgaryn** [comment]
Hi @EIHABALMUKASHFI ,

you would need to modify the controller of the storage unit according to what you need.

https://github.com/e2nIEE/pandapower/blob/develop/tutorials/building_a_controller.ipynb

Roman
