### ISSUE TITLE
shunt reactor modelling 

### ISSUE THREAD

**Issue by rauf-cresg** [e2nIEE/pandapower#1615]
It looks like the function _pandapower.create_shunt()_ creates only a shunt capacitor, not a reactor. I tried changing the sign of the value of the q_mvar parameter, but it fails to model the component as a shunt reactor.

**Comment by rbolgaryn** [comment]
Dear @rauf-cresg ,

can you elaborate?

I tried creating the shunt element with positive and negative q_mvar and the results of the power flow calculation are different.

´´´python
import pandapower as pp
import pandapower.networks as nw

net = nw.example_simple()
s_id = pp.create_shunt(net, 4, q_mvar=10)
pp.runpp(net)
net.res_bus.loc[[4]]

#            vm_pu  va_degree  p_mw     q_mvar
# 4     1.019452   1.800451   0.0  10.392832

net.shunt.at[s_id, 'q_mvar'] = -10
pp.runpp(net)
net.res_bus.loc[[4]]

#           vm_pu  va_degree  p_mw     q_mvar
# 4     1.029751    1.77725   0.0 -10.603874

´´´
