### ISSUE TITLE
How to get multiple variable in fledge through MODBUS-C in South Plugin

### ISSUE THREAD

**Issue by ramsingh1995** [e2nIEE/pandapower#1676]
I am working on Raspberry pi and Arduino communicating through modbus over Ethernet. I want to get values of voltages and currents of many buses in the fledge through MODBUS-TCP at the same time. The values of voltages and currents are sensed by voltage and current sensors respectively and have to sent to Arduino and then to fledge through modbus protocol. I am trying to configure the registers in south plugin but unable to get multiple values simultaneously.
Kindly suggest me how get multiple variables in fledge.

**Comment by rbolgaryn** [comment]
This is an Issue board for pandapower. I suggest asking this question in a different forum.
