### ISSUE TITLE
BUG: distributed_slack=True and enforce_q_lims=True cause error in pfsoln

### ISSUE THREAD

**Issue by rbolgaryn** [e2nIEE/pandapower#1689]

**Comment by AnkurArohi** [comment]
#Following

**Comment by rbolgaryn** [comment]
The balance of power does not match anymore if enforce_q_lims = True

**Comment by AnkurArohi** [comment]
intresting, probably the Q limit that is being enforced leads to a changed P calculation and this changed value is then not adjusted in the balance or in NR
