### ISSUE TITLE
How to create dispatchable loads on PP

### ISSUE THREAD

**Issue by Horreyneeyo** [e2nIEE/pandapower#1697]
Hello,

How can I create dispatchable loads on pandapower. On Matlab, it quite easy - use negative generation. How do I do the same in Pandapower.
I tried using the 'controllable' feature on the normal load model. However, the OPF simulation results shows that the load keeps running down to zero (min_mw) .
How do I create dispatchable loads on a PP network?

**Comment by rbolgaryn** [comment]
You can define costs of loads as negative values if you want to maximize loads. 
You can also use sgen elements instead of negative loads.

**Comment by Horreyneeyo** [comment]
Thanks for your kind response.
I have resolved the issue based on your answers
