### ISSUE TITLE
Importing simple_plotly in fresh installation throws exception

### ISSUE THREAD

**Issue by dzimmanck** [e2nIEE/pandapower#170]
In a fresh install, I got the following error when attempting to import simple_plotly 

KeyError: 'axes.color_cycle is not a valid rc parameter. See rcParams.keys() for
 a list of valid parameters.'

**Comment by lthurner** [comment]
what versions are you using of pandapower, plotly and matplotlib?

**Comment by jhmenke** [comment]
The error you describe seems to be a matplotlib error instead of plotly. Can you give us the file and line of the KeyError?

**Comment by dzimmanck** [comment]
Yes, there were a number of issues, but there were all relating to environment.

**Comment by dzimmanck** [comment]
Closing, as this was a general environment issue.
