### ISSUE TITLE
AssertionError for pandapower test

### ISSUE THREAD

**Issue by Horreyneeyo** [e2nIEE/pandapower#1715]
Hi,

I tried testing my pandapower installation package using the pandapower test suite along with the imported pandapower sub-routines
as seen here [https://www.pandapower.org/start/](url)
- import pandapower.test
- pandapower.test.run_all_tests()

However, I am getting an assertion error of 'assert mod not in mods' 
What should I do to ensure everything is installed correctly and all tests should pass

**Comment by SteffenMeinecke** [comment]
Hi @Horreyneeyo 
please post your python package installations (type `pip list` or if you are using anaconda: `conda list`) as well as the assertion error logging message.
