### ISSUE TITLE
OPF not converge with DC lines

### ISSUE THREAD

**Issue by DavidLudl** [e2nIEE/pandapower#1733]
Dear Project Members,

Hello. When I am trying to solve OPF with DC lines, it doesn't converge. I am trying with the 'opf_dcline.ipynb' tutorial, my pandapower version is 2.10.1 and python is 3.9. At first I was thinking the problem was because the power flow in dclines cannot be reversed so I add another dcline with opposite power flow, i.e, one is b2 -> b3 and another is b3 -> b2. But the OPF is still not converge.

I would be appreciate if you can provide another tutorial for OPF with DC lines.

**Comment by SteffenMeinecke** [comment]
Hi @DavidLudl,
thanks for raising this issue. Can you check whether the issue still exist in pandapower version 2.5.0? (To ensure that it is not the same issue like https://github.com/e2nIEE/pandapower/issues/1430)

**Comment by DavidLudl** [comment]
> 

Hi @SteffenMeinecke, I have tried with 2.5.0 and it seems still not converge.

**Comment by SteffenMeinecke** [comment]
ok, thanks for checking. :)
Then we have herewith [another issue](https://github.com/e2nIEE/pandapower/issues?q=is%3Aissue+is%3Aopen+label%3Aopf) on the topic of divergences in OPF.

**Comment by vogt31337** [comment]
@DavidLudl is this still relevant? Has this issue been solved?

**Comment by DavidLudl** [comment]
Hi @vogt31337 . I haven't worked with DC lines for a while but I remember this problem is solved somehow. So I suppose it is not relevent anymore. Thanks.
