### ISSUE TITLE
iteritems is deprecated, use .items instead warning

### ISSUE THREAD

**Issue by fmarten99** [e2nIEE/pandapower#1739]
Hello team pandapower, FYI
in pandapower Version 2.10.1 i get the following warning, probably something needs to be updated:
**pandapower\auxiliary.py:272: FutureWarning: iteritems is deprecated and will be removed in a future version. Use .items instead.**
BR
Frank

**Comment by SteffenMeinecke** [comment]
Hello @fmarten99 ,
thanks for your advice. I checked pandapower for "iteritems". Since such is not included, it was either already replaced or the FutureWarning came from another python package.
