### ISSUE TITLE
Generic Read the Docs URL points to old version

### ISSUE THREAD

**Issue by robbiemorrison** [e2nIEE/pandapower#1743]
The generic documentation URL [https://pandapower.readthedocs.io/](https://pandapower.readthedocs.io/) does not point to the latest version of Read the Docs. 

I noticed because that same generic URL is used on your [wikipedia entry](https://en.wikipedia.org/wiki/Open_energy_system_models#pandapower).

Should be simple to fix?

**Comment by jkisse** [comment]
Thanks for letting us know! It has been fixed now :-)
