### ISSUE TITLE
KeyError('sector') occurres in Studio3T after trying to run timeseries simulation 

### ISSUE THREAD

**Issue by MatijaMilovic** [e2nIEE/pandapower#1749]
PandaHub.py - line 709, in _get_net_from_db_by_id
    if meta["sector"] == "power":
    KeyError: 'sector'

**Comment by jwiemer112** [comment]
This issue is related to pandahub (https://github.com/e2nIEE/pandahub). Please open it there if it isn't resolved already.

From my perspective you should check the pandahub version. it seems like the loaded network was initialized to the DB with another pandahub version that you use.
