### ISSUE TITLE
Bug of plot: wrong direction

### ISSUE THREAD

**Issue by DavidLudl** [e2nIEE/pandapower#1775]
Hello. 

When I using simple_plot and simple_plotly, I find that the output figure is kind of upside down. For example, this is the result of simple plot:
![image](https://user-images.githubusercontent.com/83404150/206705121-b3e97bee-d108-4cfb-8f8f-40d464dab65b.png)
However, the correct picture should be like this:
![image](https://user-images.githubusercontent.com/83404150/206705323-66fa7f6c-419e-4b7d-8676-2b69875d7652.png)
My bus_geodata input format is (lat, lon), where positive lat means Northern Hemisphere and negative is Southern Hemisphere.
It seems the direction is upside down plus horizon flip compared with  map. I don't know if this is error or I should use different geodata input format?

Thank you for your time,
Best regards,

David

**Comment by jkisse** [comment]
Hi,

it seems to me like the `x` and `y` values are reversed. Please try it with longitude values in the `net.bus_geodata.x` column and latitude as `net.bus_geodata.y`. "lat" and "lon" as column names might be misunderstood by the plotting function.

**Comment by DavidLudl** [comment]
Hi,

I tried this method before, by input (lon, lat) format, which is similar with your suggestion. However, another error was rised which said x should with in -90 to 90. Therefore, I suppose net.bus_geodata.x allow only latitude.

Here is the screen shoot:
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/83404150/208088890-924979a3-9413-45a2-a988-91d11cf97081.png">

**Comment by jkisse** [comment]
I tried to reproduce the issue with the following example and `simple_plot` worked, even with x > 90. Could you please provide a minimal example for your case?
```
import pandapower
import pandapower.networks as pn
net = pn.GBnetwork()
net.bus_geodata.x += 90
print(net.bus_geodata.max())
pandapower.plotting.simple_plot(net)
```
pandapower 2.11.0
geopy 2.2.0
Python 3.9.9

**Comment by DavidLudl** [comment]
Hello, 

Thank you for your reply.

I tried with these expressions as yours:

"x = net.bus_geodata.x
y = net.bus_geodata.y
net.bus_geodata.x = y
net.bus_geodata.y = x

plot.simple_plot(net, show_plot=True)"

Then I get the correct output:
![image](https://user-images.githubusercontent.com/83404150/208109293-6789c4b3-3388-416b-bbc8-8c010b9d5370.png)

Thank you for your help.
