### ISSUE TITLE
Patch Size in create_bus_collection

### ISSUE THREAD

**Issue by dlohmeier** [e2nIEE/pandapower#181]
In the plotting function `create_bus_collection` some part of the code does not make sense. It says that the height and width of patches are doubled in case of the "rect" patch type. This leads to the behaviour that for any "rect" bus collection the patches are twice as large as for all other collections (e.g. circles).

Therefore I created a new pull request #180 in order to delete this part of code. For anyone who created such type of bus collections already, this has a major impact on all the new created plots. Therefore this change should be noted when a new pandapower version is released.

**Comment by lthurner** [comment]
see discussion in #180
