### ISSUE TITLE
How are sgens, loads, and storages treated during state estimation?

### ISSUE THREAD

**Issue by dzimmanck** [e2nIEE/pandapower#183]
If a network includes a combination of sgens, loads, storage, and measurements, how are the static elements treated by the estimation module?  Are they ignored, or treated as ideal measurements?

**Comment by lthurner** [comment]
They are ignored. If you want ideal measurements, you will have to create them explicetely

**Comment by dzimmanck** [comment]
OK, thanks.  That answers my question so closing.
