### ISSUE TITLE
Documentation for TDPF-related line parameters

### ISSUE THREAD

**Issue by christian-cahig** [e2nIEE/pandapower#1846]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/e2nIEE/pandapower/issues) for similar reports
* [x] Read the relevant sections of the [documentation](https://pandapower.readthedocs.io/en/latest/about.html) 
* [x] Browse the [tutorials](https://github.com/e2nIEE/pandapower/tree/develop/tutorials) and [tests](https://github.com/e2nIEE/pandapower/tree/develop/pandapower/test) for usefull code snippets and examples of use

## Labels (if access available)
* [x] Choose a `labels` at the right side (e.g. `bug`, `controller`, `OPF`...)

## Description

Hi, I'm new to temperature-dependent power flow (TDPF). From the [TDPF docs](https://pandapower.readthedocs.io/en/latest/powerflow/ac.html#temperature-dependent-power-flow-tdpf), it requires additional `net.line` parameters (e.g., `tdpf`, `outer_diameter_m`, `r_theta_kelvin_per_mw`). However, I cannot seem to find these parameters mentioned in the [Line docs](https://pandapower.readthedocs.io/en/latest/elements/line.html).

**Comment by rbolgaryn** [comment]
Hi @christian-cahig ,

you are right, we will add them to the docstrings. 

In the meantime, please refer to the tutorials for TDPF:

https://github.com/e2nIEE/pandapower/blob/develop/tutorials/temperature_dependent_power_flow.ipynb

Roman
