### ISSUE TITLE
Plotting: Creating Single-Line

### ISSUE THREAD

**Issue by LukasKur** [e2nIEE/pandapower#1862]
Hey guys,

I´m just starting with pandapower, but I don´t find a function for that in the Docs:
Is it possible to plot single-line-diagrams with pandapower (e.g. like in DigSilent Powerfactory)?
I only need the structure of the network, not the information about the geodata.

Something like that would be great:
![image](https://user-images.githubusercontent.com/123761226/216786174-4a9a2cd4-4c2e-4a64-826e-81f1792eeccb.png)

Thanks in advance and kinds regards,
Lukas

**Comment by jwiemer112** [comment]
Hey Lukas, please use the [Issue-Templates](https://github.com/e2nIEE/pandapower/issues/new/choose).

At the moment pandapower offers plotting functions based on **matplotlib** and **plotly**. These visualize the network topology based on geocoordinates.

An exact electrical map of the network cannot be plotted easily at the moment. We are open for suggestions, collaborations and pull requests from the community.

Greetz Jan

**Comment by nicorikken** [comment]
Best free software implementation I've seen so far is in PowSyBl https://github.com/powsybl/powsybl-single-line-diagram-server Could be inspiration for an implementation in Python, or perhaps those developers are willing to collaborate.

**Comment by LukasKur** [comment]
Alright, thanks a lot!
