### ISSUE TITLE
Changes in makeBdc?

### ISSUE THREAD

**Issue by friederikemeier** [e2nIEE/pandapower#189]
Hi,

The following code gives different results in pp1.5 and pp1.6:

`import pandapower as pp
import pandapower.networks
from pandapower.pd2ppc import _pd2ppc
from pandapower.pf import makeBdc
import pandas as pd

net = pp.networks.case14()
pp.rundcpp(net)
net.res_bus["va_degree"].plot()

ppc, ppci = _pd2ppc(net)
bus, branch = ppci["bus"], ppci["branch"]
Bbus, Bf, Pbusinj, Pfinj = makeBdc(bus, branch)

Bbus_real = Bbus.real`

I am generating the Y matrix for the DC model for the IEEE 14 bus system. Until now, the internal and external numeration was identical. And also the units of the matrix seem to have changed. E.g. the first entry was 2138 before and now is 21.38.
Find the different matrices attached.
Version 1.6:
![v16](https://user-images.githubusercontent.com/11868107/46939601-faeedd80-d066-11e8-8781-0a11f5d280b2.png)
Version 1.5:
![v15](https://user-images.githubusercontent.com/11868107/46939602-faeedd80-d066-11e8-8859-ddfa267e24fe.png)

Why is that so? What change from the changelog causes this?

**Comment by wangzhenassd** [comment]
Hi,
I have tried your test case. The problem was on the baseMVA, on PP1.6 it is by default 100.0 and PP1.5 it is 1.0 from the loaded ieee case14. That would explain the exact 100 time difference between the two admittance matrices.
