### ISSUE TITLE
Problem with simple_plotly

### ISSUE THREAD

**Issue by sf-snigdha** [e2nIEE/pandapower#1891]
When I tried to plot my grid with simple_plotly on map , no figure was shown though coordinates were there. There was no error either. I made sure that my line_geodata was in lat/long format and on_map was also set true.

Could you please help with that?

**Comment by jwiemer112** [comment]
Hey,

can you attach a minimal example? Did you specify a mapbox token?

Greetz Jan

**Comment by sf-snigdha** [comment]
Hi,

Sorry I did not create the mapbox token. That's why no plot was seen. But now simple_plotly works on map with the specified mapbox token.

Thanks
