### ISSUE TITLE
Reactive power at PV buses is silently ignored

### ISSUE THREAD

**Issue by eike** [e2nIEE/pandapower#1904]
When connecting both a `gen` and a `load` to a bus and running the power-flow calculation, the `q_mvar` value of the load is silently ignored, as in the following example
```python
import pandapower as pp
net = pp.create_empty_network()
pp.create_buses(net, 2, vn_kv=0.4)
pp.create_line(net, 0, 1, length_km=0.1, std_type="NAYY 4x50 SE")
pp.create_ext_grid(net, 0)
pp.create_load(net, 1, p_mw=0.02, q_mvar=1000)
pp.create_gen(net, 1, p_mw=0.005)
pp.runpp(net)
print(net.res_bus)
```
which produces
```
   vm_pu  va_degree      p_mw    q_mvar
0    1.0   0.000000 -0.024558  0.152371
1    1.0  -3.578301  0.015000 -0.153605
```
(Clearly, the specified `q_mvar` value does not affect the calculation.)

Now, I understand that having both loads and gens at the same bus does not make sense. However, I would expect pandapower to throw an exception in this case, similar to the case where two generators with different `vm_pu` values are connected to the same bus.

**Comment by rbolgaryn** [comment]
Hi @eike ,

can you please add the outputs of net.res_load and net.res_gen?

**Comment by eike** [comment]
Yeah, I should have checked those as well, sorry:
```
    p_mw       q_mvar  va_degree  vm_pu
0  0.005  1000.153605  -3.578301    1.0
   p_mw  q_mvar
0  0.02  1000.0
```
So a voltage-controlled generator will just “eat” the entire reactive power consumption at its bus.

I’m actually not entirely sure how the load flow works in this case. Looking at the internals, the bus is translated into a PV bus, so I don’t get (yet) how pandapower sets a Q value for that bus. (I’m just starting to learn how load-flow calculations work.)

Sorry for wasting your time.

**Comment by AnkurArohi** [comment]
@eike 
So the thing is for a PV bus a load flow solver tries to calculate the values of Q and angle, now for this case, I would actually say that the solver is trying to reduce the amount of reactive power which will flow out of this bus, which is actually a good thing if the solver can do that respecting the voltage limits, as reactive power is better compensated and balanced at local level to improve the power factor and overall transmission efficiency

**Comment by eike** [comment]
@AnkurArohi I don’t think a load-flow solver gets to make any decisions, does it? (I’m not doing an optimal power flow.) It tries to calculate how the power would actually flow in a physical system. So locality of reactive power is good, but it only works because I provided the reactive power locally.

Having played with it some more, I suspect that the result is equivalent to having a PV bus and a PQ bus connected via a very short line. But there must be some shortcut in the calculation, as pandapower does not create a separate PQ bus for the load, if I understand the internal `net._ppc` structure correctly.

What I’m really trying to achieve is to get out the sensitivity matrix. Since I’m doing this with pandapower, I want the results in pandapower terms as well, i.e. I want to see the effect of changing the values at the gen and load elements (not the internal buses). However, my understanding is not yet good enough to say how to handle the case of loads and gens connected to the same bus.

**Comment by AnkurArohi** [comment]
@eike 
Yes indeed power flow is not about taking decisions and I don't mean that here, I simply mean if you have a PV bus the Q value is calculated, this calculation depends on voltage and normally the reactive power based on voltage leads to a local balancing, so I would not wonder If this happens when load and generator are connected to same bus, however if you specify P and Q values for the load, the solver will try to respect it as well and I don't know in detail how it is handled here, but if the load has no Q defined I would actually allow the Q to be taken from the balance at the bus which in this case is the generator Q

**Comment by AnkurArohi** [comment]
What I can suggest you in this case is to model the load in another bus and then you can also define the Q value in that case, hence you will see that the Q at generator bus is calculated considering the whole balance
