### ISSUE TITLE
[Tutorial] diagnostic tutorial is deprecated?

### ISSUE THREAD

**Issue by vogt31337** [e2nIEE/pandapower#198]
Hi,

in the tutorial diagnostic.ipynb are functions mentioned not supported anymore.
For example pp.diagnostic(faulty_net, report_style="compact") <- report_style isn't available, or detailed_report either. 

BR

**Comment by lthurner** [comment]
@julffers?

**Comment by julffers** [comment]
The diagnostic tutorial isn't deprecated but you are right, it seems to be a bit neglected right now. Sorry for that, I'm on it.

**Comment by julffers** [comment]
df15a68475aed5f33b1e665e06d30ad50d716dda
