### ISSUE TITLE
Documentation of Create Functions for elements in latest docs missing

### ISSUE THREAD

**Issue by GoetzLipphardt** [e2nIEE/pandapower#1984]
In the latest documentation of pp the descriptions of the Create Functions for elements under Datastructure and elements are missing. See the following example for the element Empty Network: [latest](https://pandapower.readthedocs.io/en/latest/elements/empty_network.html)

In previous versions of the documentation (example [v2.11.1](https://pandapower.readthedocs.io/en/v2.11.1/elements/empty_network.html)) these descriptions are available.

**Comment by SteffenMeinecke** [comment]
Should be fixed not. Thanks for raising the issue.
