### ISSUE TITLE
enhancements of protection module

### ISSUE THREAD

**Issue by pawellytaev** [e2nIEE/pandapower#1991]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/e2nIEE/pandapower/issues) for similar reports
* [x] Read the relevant sections of the [documentation](https://pandapower.readthedocs.io/en/latest/about.html) 
* [x] Browse the [tutorials](https://github.com/e2nIEE/pandapower/tree/develop/tutorials) and [tests](https://github.com/e2nIEE/pandapower/tree/develop/pandapower/test) for usefull code snippets and examples of use

This issue is a general issue for code enhancements of pandapower.protection which are related to the current state of the module, i.e. not including new features. I see the following points as part of future improvement:

- [ ] removal of unnecessary deepcopy's in the code
- [ ] inclusion of relays as part of the net object (currently it is a list of dictionaries)
- [ ] acceleration of code by replacing loops with vectorized calculations
- [ ] points from the code review here: https://github.com/e2nIEE/pandapower/pull/1790
- [ ] increase of test coverage (>80%?)

feel free to add further points related to the general protection module

**Comment by vogt31337** [comment]
@pawellytaev @gbanerjeefraunhofer could you take a look at this and maybe just close it?

**Comment by gbanerjeefraunhofer** [comment]
This issue is deprecated and already taken care of.
