### ISSUE TITLE
[feature] automatic code style using `black` code formatting tool

### ISSUE THREAD

**Issue by ems-ja** [e2nIEE/pandapower#2051]
### Feature Checklist
* [x] Searched the [issues page](https://github.com/e2nIEE/pandapower/issues) for similar feature requests
* [x] Read the relevant sections of the [documentation](https://pandapower.readthedocs.io/en/latest/about.html) 
* [x] Browse the repository, [tutorials](https://github.com/e2nIEE/pandapower/tree/develop/tutorials) and [tests](https://github.com/e2nIEE/pandapower/tree/develop/pandapower/test) for already existing functionalities

**Describe the solution you'd like**
I like the code to be formatted with the code formatting tool [`black`](https://github.com/psf/black) as the current style is very unreadable and unconsistent.

**Describe alternatives you've considered**
There is no real alternative to `black`. 

**Additional context**
-

## Labels (if access available)
* [x] Choose a `labels` at the right side (e.g. `controller`, `OPF`...)
Not available so none choosen.

**Comment by rbolgaryn** [comment]
What is the status on this @l3s8g ?
