### ISSUE TITLE
[Documentation]: Updating short-circuit documentation

### ISSUE THREAD

**Issue by sarajcev** [e2nIEE/pandapower#2054]
### Issue Report Checklist

* [x] Searched the [issues page](https://github.com/e2nIEE/pandapower/issues) for similar reports
* [x] Read the relevant sections of the [documentation](https://pandapower.readthedocs.io/en/latest/about.html) 
* [x] Browse the [tutorials](https://github.com/e2nIEE/pandapower/tree/develop/tutorials) and [tests](https://github.com/e2nIEE/pandapower/tree/develop/pandapower/test) for usefull code snippets and examples of use

## Labels (if access available)
* [x] Choose a `labels` at the right side (e.g. `bug`, `controller`, `OPF`...)

I was going through the main documentation regarding the short-circuit computation capabilities of the package and I've noticed that it is somewhat lacking in scope and details, and that it could be improved. Perhaps it might benefit users to incorporate some additional information into the main page of the short-circuit documentation? 

I've taken the liberty of creating a PR #2053  to address, to some extent, this lack of information and would appreciate any feedback. Thank you in advance for considering it and, please, feel free to comment and edit the proposed text as seen fit.

CC @rbolgaryn

**Comment by rbolgaryn** [comment]
Thank you for your contribution @sarajcev !
