### ISSUE TITLE
Is it possible to perform online time series simulation?

### ISSUE THREAD

**Issue by tranvary** [e2nIEE/pandapower#2072]
### Issue Report Checklist

* [√] Searched the [issues page](https://github.com/e2nIEE/pandapower/issues) for similar reports
* [√] Read the relevant sections of the [documentation](https://pandapower.readthedocs.io/en/latest/about.html) 
* [√] Browse the [tutorials](https://github.com/e2nIEE/pandapower/tree/develop/tutorials) and [tests](https://github.com/e2nIEE/pandapower/tree/develop/pandapower/test) for usefull code snippets and examples of use

## Labels 
* [ `Time Series Simulation`] 
I notice that a DataSource is needed to perform time series simulation. However, if this data is only available when the power flow calculation of the last time step has finished, can time series simulation still be used? Alternatively, is there another way to achieve this?

**Comment by rbolgaryn** [comment]
Hi @tranvary ,

you can write your own DataSource class - make sure it follows the general structure of the base DataSource class.

Then you can define it to provide data in any way you need.

Best regards,
Roman
