### ISSUE TITLE
[feature] Add documentation of using power-grid-model as calculation core

### ISSUE THREAD

**Issue by TonyXiang8787** [e2nIEE/pandapower#2076]
### Feature Checklist
* [x] Searched the [issues page](https://github.com/e2nIEE/pandapower/issues) for similar feature requests
* [x] Read the relevant sections of the [documentation](https://pandapower.readthedocs.io/en/latest/about.html) 
* [x] Browse the repository, [tutorials](https://github.com/e2nIEE/pandapower/tree/develop/tutorials) and [tests](https://github.com/e2nIEE/pandapower/tree/develop/pandapower/test) for already existing functionalities

**Describe the solution you'd like**

Add documentation of using power-grid-model as calculation core

**Additional context**

The function itself is integrated. We want it to be documented in readthedocs.

## Labels (if access available)
* [x] Choose a `labels` at the right side (e.g. `controller`, `OPF`...)

**Comment by rbolgaryn** [comment]
Closing, the pull request was merged.
