### ISSUE TITLE
Question about create storage

### ISSUE THREAD

**Issue by Ambitioncsy** [e2nIEE/pandapower#2093]
### Feature Checklist

- [X] Searched the [issues page](https://github.com/e2nIEE/pandapower/issues) for similar reports

- [ ] Read the relevant sections of the [documentation](https://pandapower.readthedocs.io/en/latest/about.html)

- [ ] Browse the [tutorials](https://github.com/e2nIEE/pandapower/tree/develop/tutorials) and [tests](https://github.com/e2nIEE/pandapower/tree/develop/pandapower/test) for usefull code snippets and examples of use

### Issue

It reports 'AttributeError: 'Series' object has no attribute 'iteritems'' when I create storage

### Label

- [ ] Relevant labels are selected

**Comment by rbolgaryn** [comment]
Hi @Ambitioncsy it seems like you are using some outdated packages. Try installing pandapower (either from GitHub or with pip) from scratch and updating your packages.
