### ISSUE TITLE
[bug] Unable to convert ENTSO-E CIM data into pandapower

### ISSUE THREAD

**Issue by medhasubramanian** [e2nIEE/pandapower#2110]
### Bug report checklis

- [X] Searched the [issues page](https://github.com/e2nIEE/pandapower/issues) for similar reports

- [X] Read the relevant sections of the [documentation](https://pandapower.readthedocs.io/en/latest/about.html)

- [X] Browse the [tutorials](https://github.com/e2nIEE/pandapower/tree/develop/tutorials) and [tests](https://github.com/e2nIEE/pandapower/tree/develop/pandapower/test) for usefull code snippets and examples of use

- [X] Reproduced the issue after updating with `pip install --upgrade pandapower` (or `git pull`)

- [X] Tried basic troubleshooting (if a bug/error) like restarting the interpreter and checking the pythonpath

### Reproducible Example

```python
import pandapower as pp
from pandapower.converter import from_cim as cim2pp
import os

# folder_path points to the directory where the CIM .zip-Files are stored:
folder_path = os.path.join(os.getcwd())#, 'example_cim')

# cgmes_files is a list containing paths to both files needed for the CIM converter:
cgmes_files = [os.path.join(folder_path, 'combined.zip')]
net = cim2pp.from_cim(file_list=cgmes_files) 

print('Conversion successful')
```

### Issue Description and Traceback

There is a KeyError that is being raised while trying to convert from CIM to PP; shown below.

FutureWarning: In a future version, object-dtype columns with all-bool values will not be included in reductions with bool_only=True. Explicitly cast to bool dtype instead.
  self.net[pp_type] = pd.concat([self.net[pp_type], pd.DataFrame(None, index=[list(range(input_df.index.size))])],
All controlled buses are not valid: controller has no effect
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Cell In[1], line 10
      8 # cgmes_files is a list containing paths to both files needed for the CIM converter:
      9 cgmes_files = [os.path.join(folder_path, 'combined.zip')]
---> 10 net = cim2pp.from_cim(file_list=cgmes_files) 
     12 print('Conversion successful')
in from_cim(file_list, encoding, convert_line_to_switch, line_r_limit, line_x_limit, repair_cim, repair_cim_class, repair_pp, repair_pp_class, **kwargs)
     99 cim_parser.parse_files(file_list=file_list, encoding=encoding, prepare_cim_net=True, set_data_types=True)
    101 time_start_converting = time.time()
--> 102 pp_net = from_cim_dict(cim_parser, convert_line_to_switch=convert_line_to_switch,
    103                        line_r_limit=line_r_limit, line_x_limit=line_x_limit, repair_cim=repair_cim,
    104                        repair_cim_class=repair_cim_class, repair_pp=repair_pp, repair_pp_class=repair_pp_class,
    105                        **kwargs)
    106 time_end_converting = time.time()
    107 logger.info("The pandapower net: \n%s" % pp_net)

, in from_cim_dict(cim_parser, log_debug, convert_line_to_switch, line_r_limit, line_x_limit, repair_cim, repair_cim_class, repair_pp, repair_pp_class, **kwargs)
     43     repair_cim.repair(cim_parser.get_cim_dict(), report_container=cim_parser.get_report_container())
     45 cim_converter = build_pp_net.CimConverter(cim_parser=cim_parser, **kwargs)
---> 46 pp_net = cim_converter.convert_to_pp(convert_line_to_switch=convert_line_to_switch, line_r_limit=line_r_limit,
     47                                      line_x_limit=line_x_limit, log_debug=log_debug, **kwargs)
     49 # repair the output pandapower network
     50 if repair_pp is not None and repair_pp_class is not None:
...
    394     self._check_indexing_error(key)
--> 395     raise KeyError(key)
    396 return super().get_loc(key, method=method, tolerance=tolerance)

KeyError: None

### Expected Behavior

According to the tutorial notebook, it should just print "Conversion successful"

### Installed Versions

* python version: 3.10.10 pandas version:  * networkx version:  * scipy version:  * numpy version:  * packaging version:  * tqdm version:  * deepdiff version:  * Operating System name/version:

python           : 3.11.3.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10

pandas           : 1.5.3
numpy            : 1.24.3
matplotlib       : 3.7.1
scipy            : 1.10.1

### Label

- [X] Relevant labels are selected

**Comment by heckstrahler** [comment]
Fix in pandapower version 3.0
