### ISSUE TITLE
YOUR TITLE

### ISSUE THREAD

**Issue by Aliadavid** [e2nIEE/pandapower#2130]
### Feature Checklist

- [X] Searched the [issues page](https://github.com/e2nIEE/pandapower/issues) for similar reports

- [X] Read the relevant sections of the [documentation](https://pandapower.readthedocs.io/en/latest/about.html)

- [X] Browse the [tutorials](https://github.com/e2nIEE/pandapower/tree/develop/tutorials) and [tests](https://github.com/e2nIEE/pandapower/tree/develop/pandapower/test) for usefull code snippets and examples of use

### Issue

how to run opf with input load data for let say 24 hour timeseries does not take runopf () as input to kwargs

### Label

- [x] Relevant labels are selected

**Comment by pawellytaev** [comment]
Hi @Aliadavid, you can use the time series module for that, but in run_timeseries set the attribute run to pp.runopp. Here's a tutorial that describes that https://github.com/e2nIEE/pandapower/blob/develop/tutorials/timeseries_opf.ipynb
