### ISSUE TITLE
Userdefined Cost and per time step objective result

### ISSUE THREAD

**Issue by Aliadavid** [e2nIEE/pandapower#2141]
### Feature Checklist

- [X] Searched the [issues page](https://github.com/e2nIEE/pandapower/issues) for similar reports

- [X] Read the relevant sections of the [documentation](https://pandapower.readthedocs.io/en/latest/about.html)

- [X] Browse the [tutorials](https://github.com/e2nIEE/pandapower/tree/develop/tutorials) and [tests](https://github.com/e2nIEE/pandapower/tree/develop/pandapower/test) for usefull code snippets and examples of use

### Issue

Can you guide me how to update cost  function like add additional term let say error cost in it 
Secondly how to get per time step cost value for timeseries

### Label

- [X] Relevant labels are selected

**Comment by rbolgaryn** [comment]
Dear @Aliadavid ,

I do not think you can modify the cost functions easily as a user. You will have to use the poly_cost or pwl_cost.

You can use ConstControl to modify the costs for the time steps.

You can use the parameter run=pp.runopf to execute OPF during timeseries simulation.
