### ISSUE TITLE
Understanding internal Ybus matrix dimension

### ISSUE THREAD

**Issue by rahatN-tech** [e2nIEE/pandapower#2144]
### Bug report checklis

- [X] Searched the [issues page](https://github.com/e2nIEE/pandapower/issues) for similar reports

- [X] Read the relevant sections of the [documentation](https://pandapower.readthedocs.io/en/latest/about.html)

- [X] Browse the [tutorials](https://github.com/e2nIEE/pandapower/tree/develop/tutorials) and [tests](https://github.com/e2nIEE/pandapower/tree/develop/pandapower/test) for usefull code snippets and examples of use

- [X] Reproduced the issue after updating with `pip install --upgrade pandapower` (or `git pull`)

- [X] Tried basic troubleshooting (if a bug/error) like restarting the interpreter and checking the pythonpath

### Reproducible Example

```python
import pandapower.networks as nw
net = nw.create_cigre_network_mv(with_der="all")
pp.runpp(net)

ybus = net._ppc["internal"]["Ybus"].todense()
print(ybus.shape)

print(net._pd2ppc_lookups["bus"])
```

### Issue Description and Traceback

i am using network nw.create_cigre_network_mv(with_der="all"), which is a 15 bus system.
i am getting 18X18 ybus matrix through ybus = net._ppc["internal"]["Ybus"].todense()
i have also checked internal bus mapping through print(net._pd2ppc_lookups["bus"]).. which is showing exact bus mapping of 15 buses... so what can be the issue..how to fix this

### Expected Behavior

i should get 15X15 bus matrix

### Installed Versions

* python version: * pandas version:  * networkx version:  * scipy version:  * numpy version:  * packaging version:  * tqdm version:  * deepdiff version:  * Operating System name/version:
i am using latest version

### Label

- [X] Relevant labels are selected

**Comment by SteffenMeinecke** [comment]
Dear @rahatN-tech,
in the cigre MV network, three lines end at open switches. In order to take into account the line impedances of these energized but unloaded lines, auxiliary nodes are added internally at the open ends. Therefore, the internal Ybus matrix has the dimension 18x18, since 18=15+3.
The addition of auxiliary nodes is explained and illustrated in Table II of the IEEE Transactions article http://dx.doi.org/10.1109/TPWRS.2018.2829021.
