### ISSUE TITLE
error when plotting with plotly

### ISSUE THREAD

**Issue by schmocker** [e2nIEE/pandapower#215]
hi,
using pandapower 1.6.0 and plotly 3.4.1 resolves in an error when plotting
```
from pandapower.plotting.plotly import pf_res_plotly
...
pf_res_plotly(net)
```

```
>> if version.parse(__version__) < version.parse("3.1.1"):
>> NameError: name 'version' is not defined
```

**Comment by jhmenke** [comment]
do you have "packaging" installed? (_pip install packaging_)
if not, this is missing in the project requirements.

**Comment by schmocker** [comment]
thats it! thank you

**Comment by schmocker** [comment]
> do you have "packaging" installed? (_pip install packaging_)
> if not, this is missing in the project requirements.

thats it! thank you
