### ISSUE TITLE
My Pandapower missing file of protection

### ISSUE THREAD

**Issue by Adarsh-365** [e2nIEE/pandapower#2174]
### Feature Checklist

- [ ] Searched the [issues page](https://github.com/e2nIEE/pandapower/issues) for similar reports

- [ ] Read the relevant sections of the [documentation](https://pandapower.readthedocs.io/en/latest/about.html)

- [ ] Browse the [tutorials](https://github.com/e2nIEE/pandapower/tree/develop/tutorials) and [tests](https://github.com/e2nIEE/pandapower/tree/develop/pandapower/test) for usefull code snippets and examples of use

### Issue

ok I install panadapower using pip it missing  files which is present in Repository  pandapower/protection

![error](https://github.com/e2nIEE/pandapower/assets/102159256/ec3517a4-e1aa-4389-b65c-210145963dd5)

![error1](https://github.com/e2nIEE/pandapower/assets/102159256/46a62957-66c1-4e67-b033-7e84115771b3)

### Label

- [ ] Relevant labels are selected

**Comment by rbolgaryn** [comment]
Dear @Adarsh-365 ,

pip has only the stable version of pandapower. The features you are mentioning are only part of the develop branch at the moment and will be available in the stable version on pip at a later point. Please install the pandapower develop branch.
