### ISSUE TITLE
SSC case problem 

### ISSUE THREAD

**Issue by frostyduck** [e2nIEE/pandapower#2188]
### Feature Checklist

- [ ] Searched the [issues page](https://github.com/e2nIEE/pandapower/issues) for similar reports

- [ ] Read the relevant sections of the [documentation](https://pandapower.readthedocs.io/en/latest/about.html)

- [ ] Browse the [tutorials](https://github.com/e2nIEE/pandapower/tree/develop/tutorials) and [tests](https://github.com/e2nIEE/pandapower/tree/develop/pandapower/test) for usefull code snippets and examples of use

### Issue

I tried to run one of your tutorial https://github.com/e2nIEE/pandapower/blob/develop/tutorials/FACTS.ipynb (SSC use case (STATCOM))

but I get the following error:

>  pp.create_ssc(net, bus=6, r_ohm=0, x_ohm=5, set_vm_pu=1, controllable=True, in_service=True, vm_internal_pu=1.02, va_internal_degree=0)
> AttributeError: module 'pandapower' has no attribute 'create_ssc'

----------
Python 3.10, Windows 11, pandapower 2.13.1

### Label

- [ ] Relevant labels are selected

**Comment by rbolgaryn** [comment]
Dear @frostyduck ,

please make sure you are using the latest state of pandapower develop branch.
