### ISSUE TITLE
Create Advanced tutorial - create LV switches

### ISSUE THREAD

**Issue by Deki4** [e2nIEE/pandapower#222]
Tried recreating the low voltage network from the advanced tutorial. 
pandapower == 1.5.1
pandas == 0.23.4

This line (In[27] in example) is returning only two swtiches :
`lv_ls = net.line[(net.line.from_bus.isin(lv_buses)) & (net.line.to_bus.isin(lv_buses))]`
net.switch
Out[36]: 
   bus  element            ...            closed                      name
0   12        0            ...              True  Switch MV4 - MV-LV-Trafo
1    0        0            ...              True  Switch LV0 - MV-LV-Trafo

I believe it should be:
`lv_ls = net.line[(net.line.from_bus.isin(lv_buses.index)) & (net.line.to_bus.isin(lv_buses.index))]
`

Thanks

**Comment by lthurner** [comment]
You are right about that, thanks for the feedback. I fixed this in 53d4dc1
