### ISSUE TITLE
AttributeError: 'OCRelay' object has no attribute 'name'

### ISSUE THREAD

**Issue by MatejSpindler** [e2nIEE/pandapower#2234]
Attribute "name" is never set.

It's being used here:
https://github.com/e2nIEE/pandapower/blob/685ca90f4f4e0515152e1e41a7812c5c14cc2df1/pandapower/protection/protection_devices/ocrelay.py#L274

**Comment by gbanerjeefraunhofer** [comment]
Hey @MatejSpindler ,

thanks for raising the issue.
It is taken care of and fixed as well.

I am closing the issue as it is solved.

I wish you all the best in further using and developing the "protection module" in Pandapower.

With best regards,
Gourab
