### ISSUE TITLE
pandas 3.0 support

### ISSUE THREAD

**Issue by KS-HTK** [e2nIEE/pandapower#2246]
### Issue

Issues that needs to be resolved for the support of pandas 3.0:

- [ ] ChainedAssignmentError: behaviour will change in pandas 3.0!
      A typical example is when you are setting values in a column of a DataFrame, like:
      `df["col"][row_indexer] = value`
      Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

**Comment by SteffenMeinecke** [comment]
I hope I fixed all DeprecationWarnings of this type already.

**Comment by SteffenMeinecke** [comment]
From my point of view, this issue can be closed or filled with concrete codings which needs to be updated.

**Comment by KS-HTK** [comment]
> From my point of view, this issue can be closed or filled with concrete codings which needs to be updated.


The Idea was to track all issues related to pandas 3.0. But it seems most are already resolved.
