### ISSUE TITLE
[bug] __format_version__ not increased.

### ISSUE THREAD

**Issue by KS-HTK** [e2nIEE/pandapower#2262]
### Issue Description

The `__format_version__` in `_version.py` has not been increased eventhough the format got changed!

This is an issue in the develop branch **not** in master!

In my fork I made an update to many test cases since I changed the format, so I saved many networks in as files, they contain the current format_version (2.14.0). After merging the current version of develop I got some tests that suddenly failed eventhough my code should not mess with them. So I did a little diging and found that the expected and actual results differ in `net.res_switch_est` DataFrame. This is because the expected result only contains the old columns while the actual result contains the updated columns.

This is because the expected results are loaded form file using the `pandapower.from_json` function and since then format version is the same as the current format verison in `_version.py` the conversion to the newest format is not done. So the network is returned as loaded from file.
The actual results however are a product of a conversion from a different network type. So they are the output of a converter that creates a new pandapowerNet. These then contain all new columns.

If new columns are added `__format_version__` should be incremented at least in the bugfix number. But I would expect that this constitutes at least a minor release as a new format version most likely breaks backwards compatibility. On a bugfix version I would expect I go backwards and forwards without issue. But this is not the case if the format version changes! A 2.13.1 Network should sucessfully load on 2.13.0 but this will not work if new columns are added. So this change should be reflected by an increase of the format verison to at least 2.15.0 in my opinion.

The breaking commit is 516f8af as it changed the format without changeing the format version.

**Comment by rbolgaryn** [comment]
Sorry we forgot to increase the format version when the new columns were added to res_switch
