### ISSUE TITLE
Explanation misaligned for generator input in doc

### ISSUE THREAD

**Issue by miek770** [e2nIEE/pandapower#231]
Hi,

The generator inputs explanation are misaligned in the latest doc: [https://pandapower.readthedocs.io/en/latest/elements/gen.html](https://pandapower.readthedocs.io/en/latest/elements/gen.html)

In the **Input Parameters** table, `rdss` is explained to be *Rated voltage of the generator*, for example.

Also, `xdss` and `rdxx` don't follow the [Unit conventions](https://pandapower.readthedocs.io/en/latest/about/units.html). They could be either in percent or in per unit, so I think they should be renamed to show the unit.

Thanks,

Michel

**Comment by lthurner** [comment]
You are right about both of this, thanks for reporting. I fixed it on the dev_2.0 branch, see: https://pandapower.readthedocs.io/en/dev_2.0/elements/gen.html.

The unit of the resistance/reactance values are per unit, so I added the unit to the parameter name.

**Comment by miek770** [comment]
Great thanks!
