### ISSUE TITLE
test failure: 'csc_matrix' object has no attribute

### ISSUE THREAD

**Issue by quant12345** [e2nIEE/pandapower#2340]
### Feature Checklist

- [X] Searched the [issues page](https://github.com/e2nIEE/pandapower/issues) for similar reports

- [X] Read the relevant sections of the [documentation](https://pandapower.readthedocs.io/en/latest/about.html)

- [X] Browse the [tutorials](https://github.com/e2nIEE/pandapower/tree/develop/tutorials) and [tests](https://github.com/e2nIEE/pandapower/tree/develop/pandapower/test) for usefull code snippets and examples of use

### Issue

When testing I get multiple errors, for example:
```
FAILED pandapower/test/converter/test_from_ppc.py::test_to_and_from_ppc - AttributeError: 'csc_matrix' object has no attribute 'H'
FAILED pandapower/test/loadflow/test_runpp.py::test_bsfw_algorithm_with_branch_loops - AttributeError: 'csc_matrix' object has no attribute 'A'
```

### Label

- [ ] Relevant labels are selected

**Comment by quant12345** [comment]
Figured it out because of the new scipy. In the new .A and
.H attributes were removed. Works since scipy 1.13.0.

**Comment by vogt31337** [comment]
@quant12345 good to know, currently we fixed the scipy version. Do you know if there is a fix to get these matrices again?

**Comment by quant12345** [comment]
> @quant12345 good to know, currently we fixed the scipy version. Do you know if there is a fix to get these matrices again?

@vogt31337 I haven't done this yet, but I plan to try it in a while.
