### ISSUE TITLE
[bug] Wrong usage of transformer impedance correction factor K_T in min case of short-circuit calculation

### ISSUE THREAD

**Issue by envelio-cb** [e2nIEE/pandapower#2384]
### Feature Checklist

- [x] Searched the [issues page](https://github.com/e2nIEE/pandapower/issues) for similar reports

- [x] Read the relevant sections of the [documentation](https://pandapower.readthedocs.io/en/latest/about.html)

- [x] Browse the [tutorials](https://github.com/e2nIEE/pandapower/tree/develop/tutorials) and [tests](https://github.com/e2nIEE/pandapower/tree/develop/pandapower/test) for usefull code snippets and examples of use

### Issue

Pandapower does not follow the VDE0102 norm correctly in the min case for transformers. The impedance correction factor K_T should only be applied in the max case.
(See IEC 60909-0:2016 6.3.3)

Pull request is here: https://github.com/e2nIEE/pandapower/pull/2168

### Label

- [ ] Relevant labels are selected

**Comment by pawellytaev** [comment]
Hi @envelio-cb, thanks for opening this issue and the PR. I'll close this here, so we can communicate on the PR directly
