### ISSUE TITLE
[feature] Make updating of vk and vkr values optional

### ISSUE THREAD

**Issue by vogt31337** [e2nIEE/pandapower#2393]
### Feature Checklist

- [X] Searched the [issues page](https://github.com/e2nIEE/pandapower/issues) for similar feature requests

- [X] Read the relevant sections of the [documentation](https://pandapower.readthedocs.io/en/latest/about.html)

- [X] Browse the repository, [tutorials](https://github.com/e2nIEE/pandapower/tree/develop/tutorials) and [tests](https://github.com/e2nIEE/pandapower/tree/develop/pandapower/test) for already existing functionalities

### Feature Type

- [X] Adding new functionality to pandapower

- [ ] Changing existing functionality in pandapower

- [ ] Removing existing functionality in pandapower

### Problem Description

If you perform a lot of powerflows with trafo3w, which in turn have splinecharacteristics the vk_ and vkr_ values are always recalculated. This takes quite a lot of time and can be unnecesseray. If you for example do a outage analysis which won't change the trafo taps.

### Feature Description

Add a parameter to skip updating the vk_ and vkr_ values.

### Additional Context

If the trafo3w taps doesn't change it is not necesseray to recalculate the vk_ and vkr_ values, since they won't change. And since characteristics can be costly to evaluate it would be better to simply skip this calculation.

### Label

- [X] Relevant labels are selected

**Comment by KS-HTK** [comment]
The PR is merged, is this issue still relevant or can it be closed?
