### ISSUE TITLE
[bug] failure while executing test_from_mpc_m

### ISSUE THREAD

**Issue by quant12345** [e2nIEE/pandapower#2396]
### Bug report checklis

- [X] Searched the [issues page](https://github.com/e2nIEE/pandapower/issues) for similar reports

- [X] Read the relevant sections of the [documentation](https://pandapower.readthedocs.io/en/latest/about.html)

- [ ] Browse the [tutorials](https://github.com/e2nIEE/pandapower/tree/develop/tutorials) and [tests](https://github.com/e2nIEE/pandapower/tree/develop/pandapower/test) for usefull code snippets and examples of use

- [ ] Reproduced the issue after updating with `pip install --upgrade pandapower` (or `git pull`)

- [ ] Tried basic troubleshooting (if a bug/error) like restarting the interpreter and checking the pythonpath

### Reproducible Example

```python
pytest pandapower/test/converter/test_from_mpc.py::test_from_mpc_m
```

### Issue Description and Traceback

I did PR and found in Actions that build (3.11, 1) fails. 
**This PR does not affect this bug in any way, I just mentioned it in it.**
I didn't see this when I ran tests locally. 
Tried running this test: `pytest pandapower/test/converter/test_from_mpc.py::test_from_mpc_m`
It is clear that the test is skipped, so I removed the test decorator and a message appeared that `matpowercaseframes` needs to be installed.

**Update 18.09.2024**

First, error 1 occurred and after it was fixed, error 2. Below is why this happens.

1. `AttributeError: 'bool' object has no attribute 'astype'`

`test_from_mpc_m` calls `from_mpc` -> `from_ppc`. From `from_ppc `is called ` _from_ppc_gen` and fails on the row 135.
`astype` is a numpy attribute. When running the test: `test_from_mpc_m` and then `case24_mat` has the array type `class 'numpy.float64'`, but on `case24_m` it has the `class 'int'` (Python). 

Example to reproduce the error:
```
a = np.bool(bool)
b = bool

print(a.astype(bool))
print(b.astype(bool))
```

2. `TypeError: loop of ufunc does not support argument 0 of type float which has no callable sqrt method`
This happens in `from_ppc.py` row 272(after fixing the first error).

This error is easy to reproduce: `print(np.sqrt(np.array([1., 4.5, 7.0], dtype=object)))`

When generating `ppc` in the `_m2ppc` method, dataframes:` 'bus', 'gen', 'branch', 'gencost'` have column types [Int64](https://pandas.pydata.org/docs/reference/api/pandas.Int64Dtype.html) and  [Float64](https://pandas.pydata.org/docs/reference/api/pandas.Float64Dtype.html) (type names with a capital letter). Numpy does not recognize these types and makes them all of type `object`. The conversion to `numpy` arrays occurs on line 103.  That's why error 2 occurs. Error 1 occurs for the same reason. If we create two arrays with float64 and object types and print out their scalars types, then with an array with object type it will be a Python type, not numpy.

What reproduces the error 1:
```
arr = np.array([0, 1, 0, 1, 1], dtype=np.float64)
arrj = np.array([0, 1, 0, 1, 1], dtype=object)

print('float', type(arr[0]), 'object', type(arrj[0]))# float <class 'numpy.float64'> object <class 'int'>

print(arr[0].astype(bool))
print(arrj[0].astype(bool))
```

Code that produces an array of type object:
```
df = pd.DataFrame({'A':pd.Series([1.2, 3.0, 7.0], dtype=pd.Float64Dtype()),
                   'B': pd.Series([1, 5, 10], dtype=pd.Int64Dtype())})

print(df.dtypes)
```
Output:
```
A    Float64
B      Int64
```
`print(df.values.dtype)# numpy`

Output:

`object`

### Expected Behavior

Work without this error.

### Installed Versions

* python version: 3.12* pandas version:  2.2.2* networkx version: 3.3 * scipy version:  1.13.1* numpy version: 2.1.1 * packaging version:  24.1* tqdm version: 4.66.5 * deepdiff version:  7.0.1* Operating System name/version Ubuntu 24.04:

### Label

- [ ] Relevant labels are selected

**Comment by yasirroni** [comment]
Hi @quant12345, numpy cant't have different dtypes across column by default, unlike pandas. In pandas, we can have a column as bool, another as range (used as index for example), and the other as float. Thus, if we write manually the .m file based on numpy, we normally write something like `1` instead of numpy `1.0`. Thus, I implement `.convert_dtypes()`.

What do you think?

**Comment by quant12345** [comment]
@yasirroni 
I need time, I want to understand this better. Let's take a timeout for now, for a little while?

**Comment by quant12345** [comment]
@yasirroni  @pawellytaev 
I updated the answer. Thoughts?

**Comment by yasirroni** [comment]
@quant12345 after some though, some value such as `gen.PG` might be `Int64` due to how `.m` file parsed. On the other hand, it will most likely to be in `Float64` after run.

Or other example is `gen.QMAX`m where in `case9` it is `Int64` but in `case5` it is `Float64`.

___

My question though, what does pandapower requires?

1. The dtypes to be always consistent
2. dtypes need to be always float
3. dtypes can be mixed of int and float but using numpy dtypes, not the new pandas `Float64Dtype()` and `Int64Dtype()`

**Comment by yasirroni** [comment]
Can you try pandapower compatibility with this function?

```python
def convert_dtypes_numpy_optimized(df):
    df = df.convert_dtypes()

    int_columns = df.select_dtypes(include=['integer']).columns
    df[int_columns] = df[int_columns].astype(np.int64)

    float_columns = df.select_dtypes(include=['float']).columns
    df[float_columns] = df[float_columns].astype(np.float64)

    string_columns = df.select_dtypes(include=['string']).columns
    df[string_columns] = df[string_columns].astype(str)

    bool_columns = df.select_dtypes(include=['boolean']).columns
    df[bool_columns] = df[bool_columns].astype(bool)

    return df
 ```
 
 I will make this optional, but I want to ensure that it also compatible with pandapower.

**Comment by quant12345** [comment]
1. Question 1 implies that the types can be both pandas and numpy? If so, then when converting pandas types to numpy, all types will be object. Of course, this can be processed, but this will be additional overhead. And you need to remember that in numpy this will only be one type.
3. It will still be one type and there is no point in making them different (numpy array is created from several columns of dataframe with different types)

Based on the fact that the tests passed with matpowercaseframes1.0.8, it means everything was fine (the numpy array was float64). But, it is better to get an answer from the creators of pandapower, because if you still need both float and int types, then it will be numpy with the object type inside which are scalar float and int values ​​(it will take a long time to process) or stay on pandas.

To see all this visually, change the code in [_m2ppc](https://github.com/e2nIEE/pandapower/blob/11af12cd3db5a85135c7c022e8f5ac2e7a5b4086/pandapower/converter/matpower/from_mpc.py#L95)
<details>

<summary>_m2ppc(code)</summary>

```
def _m2ppc(mpc_file, casename_mpc_file):
    if not matpowercaseframes_imported:
        raise NotImplementedError(
            "matpowercaseframes is used to convert .m file. Please install that python "
            "package, e.g. via 'pip install matpowercaseframes'.")
    mpc_frames = CaseFrames(mpc_file)
    #'''
    for key in mpc_frames._attributes:
        if isinstance(mpc_frames.__getattribute__(key), pd.DataFrame):
            print(mpc_frames.__getattribute__(key).dtypes)# types of pandas
            print('type array numpy', mpc_frames.__getattribute__(key).values.dtype)
            #print(mpc_frames.__getattribute__(key))# show dataframe
            #print(mpc_frames.__getattribute__(key).values)# show array numpy
        else:
            print('scalar', mpc_frames.__getattribute__(key))
    #'''
    ppc = {key: mpc_frames.__getattribute__(key) if not isinstance(
        mpc_frames.__getattribute__(key), pd.DataFrame) else mpc_frames.__getattribute__(
        key).values for key in mpc_frames._attributes}
    _adjust_ppc_indices(ppc)
    return ppc
```

</details>

and run the test with printing: `pytest pandapower/test/converter/test_from_mpc.py::test_from_mpc_m -s`

And I also want to note if there is a dataframe with column types `float64 `and `int64`:
```
df = pd.DataFrame({'A':pd.Series([1.2, 3.0, 5.0, 7.0], dtype=np.float64),
                   'B': pd.Series([1, 55, 5, 10], dtype=np.int64)})

print(df.dtypes)
```
and when converted to numpy array, the resulting array is of type `np.float64`:

`print(df.values.dtype)# float64`

**Comment by yasirroni** [comment]
@quant12345 Thanks for your reply.

1. I mean does pandapower accept that `gen.QMAX` sometimes `int` but on other time `float`?
3. I mean, does pandapower require matpowercaseframes return dataframe with all identical type, for example all `float` type? Does pandapower accept mix of `float` and `int`? In `1.0.8`, matpowercaseframes return DataFrame that does have mixed numpy types (float and int). Pandapower seems works this way, so that I can assume this to be True. Thus, using the `convert_dtypes_numpy_optimized` will not break pandapower.

___

If pandapower only deals with numpy using df.values, indeed it will be in single dtypes. But, if you interact column by column, for example `mpc.gen['QMAX']` or `df.['QMAX']`, it can return `int` while df.values return `float` dtype.

**Comment by yasirroni** [comment]
Hi @quant12345, can you check to use the latest `v1.0.10`? `v1.0.9` is yanked in PyPI so that user should skip that version automatically.

This issue solved in https://github.com/UGM-EPSLab/matpowercaseframes/pull/11

**Comment by quant12345** [comment]
Hi @yasirroni .  Checked: `pytest pandapower/test/converter/test_from_mpc.py::test_from_mpc_m`
The tests are passing successfully. 

I also looked at Actions fresh PRs that were launched today and there in 'List of installed packages': `matpowercaseframes 1.0.10.`

Should we close the issue?

**Comment by yasirroni** [comment]
Yes, we should close this.

User that want consistency between read using `loadcase` and `parser` can use the `infer_numpy`. Others will use the old functionality. `v1.0.9` also yanked on PyPI.
