### ISSUE TITLE
Any Examle of using Storage controller in time series

### ISSUE THREAD

**Issue by HafizRiaz** [e2nIEE/pandapower#2398]
you can always build your own controller with this functionality, here's a tutorial that explains it: https://github.com/e2nIEE/pandapower/blob/develop/tutorials/building_a_controller.ipynb

Dear pawellytaev, 
Is there any example code where this battery controller is being used. Actually,  i wan to apply storage to an existing time series simulation, what further changes i have to made to incorporate this controller to my simulation. 

_Originally posted by @pawellytaev in https://github.com/e2nIEE/pandapower/issues/2288#issuecomment-2340533308_

**Comment by vogt31337** [comment]
@HafizRiaz, Currently such a controller does not exist. Feel free to provide one via PR.
