### ISSUE TITLE
How to translate Reactive power in SVC definition 

### ISSUE THREAD

**Issue by HafizRiaz** [e2nIEE/pandapower#2402]
### Feature Checklist

- [X] Searched the [issues page](https://github.com/e2nIEE/pandapower/issues) for similar reports

- [X] Read the relevant sections of the [documentation](https://pandapower.readthedocs.io/en/latest/about.html)

- [X] Browse the [tutorials](https://github.com/e2nIEE/pandapower/tree/develop/tutorials) and [tests](https://github.com/e2nIEE/pandapower/tree/develop/pandapower/test) for usefull code snippets and examples of use

### Issue

Dear Authors, I have to use SVC for my time series simulation but the issue is that command to define SVC  "pandapower.create.create_svc(net, bus, x_l_ohm, set_vm_pu, thyristor_firing_angle_degree, name=None, controllable=True, in_service=True, index=None, min_angle_degree=90, max_angle_degree=180, **kwargs)" does not contain Qsvc directly and formula given in the docs contains complex voltage , i am wondering how to translate a real reactive power in terms of complex voltage ? e.g. i have to install 1KVAR svc, how can i define it in terms of above parameters (i guess using, x_cvar_ohm)? correct me if i am wrong please

### Label

- [X] Relevant labels are selected

**Comment by HafizRiaz** [comment]
Ok got it. Thanks

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by pawellytaev** [comment]
Hey, closing this issue then 👍
