### ISSUE TITLE
[bug] CimConverter sets pandas max_columns and max_rows to higher values globaly

### ISSUE THREAD

**Issue by filgalabov** [e2nIEE/pandapower#2467]
### Bug report checklis

- [X] Searched the [issues page](https://github.com/e2nIEE/pandapower/issues) for similar reports

- [X] Read the relevant sections of the [documentation](https://pandapower.readthedocs.io/en/latest/about.html)

- [X] Browse the [tutorials](https://github.com/e2nIEE/pandapower/tree/develop/tutorials) and [tests](https://github.com/e2nIEE/pandapower/tree/develop/pandapower/test) for usefull code snippets and examples of use

- [X] Reproduced the issue after updating with `pip install --upgrade pandapower` (or `git pull`)

- [X] Tried basic troubleshooting (if a bug/error) like restarting the interpreter and checking the pythonpath

### Reproducible Example

```python
import pandas as pd
import numpy as np

# create df 
df = pd.DataFrame(np.random.rand(1000, 500), columns=np.random.randint(100000, 999999, 500).astype(str))

# print works as expected, default df rows and columns
print(df)

# import pandapower (pandapower/converter/cim/cim2pp/build_pp_net.py) 
# sets globaly 'display.max_columns' and 'display.max_rows' to higher values
# This action results too many string transformations on a dataframe level.
# Jupyter instability is the result
import pandapower as pp

# performance issues
print(df)
```

### Issue Description and Traceback

Dear all,

the build_pp_net.py module at pandapower/converter/cim/cim2pp/build_pp_net.py sets globaly two Pandas options:
```
pd.set_option('display.max_columns', 900)
pd.set_option('display.max_rows', 90000)
sc = cim_tools.get_pp_net_special_columns_dict()
```
In some cases, like wider Dataframes, this leads to performance issues due to string transformation in pandas.io.formats.format.py. 
The user can overwrite this settings anyways, but it is not expected that Pandapower is changing them. 

Best
FG

### Expected Behavior

import pandapower should not change display options. Sometimes is difficult to understand where this performance issues are comming from, especially if pandapower is imported indireclty.

Does CimConverter really needs these two diplay options? If this is the case, this should not affect the end-user. 

It seems that all pandapower versions from 2.11.* <> 2.14.* are affected

### Installed Versions

* python v3.10.12: * pandas version: 2.2.2, pandapower 2.14.11

### Label

- [ ] Relevant labels are selected

**Comment by heckstrahler** [comment]
As of the current state of develop branch this is no longer part of build_pp_net.py.
In the upcomming pandapower 3.0 release this should be fixed.
