### ISSUE TITLE
create_gen scaling

### ISSUE THREAD

**Issue by daetzm** [e2nIEE/pandapower#257]
Hi everyone,

I have a short question. What does the scaling factor in create_gen stand for. Is that the ramping coefficient of the generator. As an example a coal power plant has a ramping coefficient of 10%, would that mean that scaling=0.1 or -0.1?

Thank you for your help
Max

**Comment by jhmenke** [comment]
It's just a factor to multiply the p_kw and q_kvar with in a power flow.
For example say that the generator has 1000 kW of power but you want to do a power flow at an operating point of 10 % / 100 kW. Then you do not have to adjust the p_kw and can simply set scaling to 0.1
