### ISSUE TITLE
Include module 'packaging' in the pandapower requirements

### ISSUE THREAD

**Issue by SteffenMeinecke** [e2nIEE/pandapower#276]
There are recurrent issues concerning version handling. This is why I propose to include 'packaging' in the pandapower requirements. Let's consider pandas examples:
Since pandas changes function names like reindex_axis() to reindex(), we have code like

try:
    net["trafo3w"] = net["trafo3w"].append(dd).reindex(...)
except TypeError: # legacy for pandas <0.21
    net["trafo3w"] = net["trafo3w"].append(dd).reindex_axis(...)

This works but using packaging should be more elegante.

from packaging import version
if version.parse(pd.__version__) >= version.parse("0.21.0"):
    net["trafo3w"] = net["trafo3w"].append(dd).reindex(...)
else:
    net["trafo3w"] = net["trafo3w"].append(dd).reindex_axis(...)

Moreover, using packaging enables distinguishing more than 2 version cases without creating try-except-cascades. For example:

if version.parse(pd.__version__) >= version.parse("0.23.0"):
    net["trafo3w"] = net["trafo3w"].append(dd, sort=False).reindex(...)
elif version.parse(pd.__version__) >= version.parse("0.21.0"):
    net["trafo3w"] = net["trafo3w"].append(dd).reindex(...)
else:
    net["trafo3w"] = net["trafo3w"].append(dd).reindex_axis(...)

**Comment by jhmenke** [comment]
packaging is already used to detect plotly - it's optional there, but another reason to include packaging in the requirements

**Comment by lthurner** [comment]
agreed, let's include packaging in the requirements.txt and use it to check versions
