### ISSUE TITLE
CIM/CGMES support

### ISSUE THREAD

**Issue by Haigutus** [e2nIEE/pandapower#278]
While building a simple parser in python for CIM/CGMES - RDF/XML I discovered your project, thus I would like to propose that you add CIM/CGMES support.

Reasoning:
European TSO-s are in a process of moving to CIM16(CGMES) based model data exchange, so there will be a lot of models available in a non vendor locked open format. Most likely, in future studies performed for TSO-s on existing models can be done in an open format.

Links/References

My simple parser RDF->triplestore/graph in pandas - https://github.com/Haigutus/USVDM/tree/master/Tools/RDF_PARSER

General CGMES Documentation - https://www.entsoe.eu/digital/cim/cim-for-grid-models-exchange/

Most interesting ones
UML - https://www.entsoe.eu/Documents/CIM_documents/Grid_Model_CIM/ENTSOE_CGMES_v2.4.15_7Aug2014_XMI.zip
RDFS - https://www.entsoe.eu/Documents/CIM_documents/Grid_Model_CIM/ENTSOE_CGMES_v2.4.15_04Jul2016_RDFS.zip
Sample Models - https://docstore.entsoe.eu/Documents/CIM_documents/Grid_Model_CIM/TestConfigurations_packageCASv2.0.zip

**Comment by Haigutus** [comment]
Just short explanation how my RDF parser works:

1. It parses all the data to pandas dataframe with 4 columns (sort of triplestore)

  ```
path = "CGMES_v2.4.15_RealGridTestConfiguration_v2.zip"
  data = load_all_to_dataframe([path])

```

![image](https://user-images.githubusercontent.com/11408965/64228384-53350500-ceef-11e9-9a8b-473ed1dc6e4d.png)


2. You can then ask a dataframe of all same type elements and its parameters across all [EQ, SSH, TP, SV etc.] instance files, where parameters are columns and index is object ID-s. I belive its hould be quite easy from here to transfrom data to pandapower internal dataframes.

![image](https://user-images.githubusercontent.com/11408965/64228433-7eb7ef80-ceef-11e9-81d4-43e39ecf099d.png)

**Comment by lthurner** [comment]
Sorry about the missing feedback. Do you know about  cimpyorm? This might be interesting for you: https://cimpyorm.readthedocs.io/en/latest/
