### ISSUE TITLE
refactor ppc handling

### ISSUE THREAD

**Issue by rbolgaryn** [e2nIEE/pandapower#282]
Currently, the values from pandapower to ppc are converted as following:

`if "line" in lookup:`
`    f, t = lookup["line"]`
`    ppc["branch"][f:t, [F_BUS, T_BUS, BR_R, BR_X, BR_B, BR_STATUS, RATE_A]] = _calc_line_parameter(net, ppc)`

I suggest that the functions such as _calc_line_parameter(...), that already get ppc as input, write the values in ppc directly without returning them:

`if "line" in lookup:`
`    _calc_line_parameter(net, ppc)`

This way, the code will be more consise and readable, especially because the constants for column indices can be used directly in these functions as well:

before:

`t[:, 2] = line["r_ohm_per_km"].values * length_km / baseR / parallel`

after:

`pcc['line'][index_start:index_end, BR_R] = line["r_ohm_per_km"].values * length_km / baseR / parallel`

**Comment by FlorianShepherd** [comment]
I like the idea. The code is really not that good...
