### ISSUE TITLE
diagnostic.parallel_switches() do not well consider "et"

### ISSUE THREAD

**Issue by SteffenMeinecke** [e2nIEE/pandapower#305]
According to my understanding there are no parallel switches in the attached example script. But the function "parallel_switches(net)" claims something else. @julffers , can you fix it? Should be no big issue.

`import pandapower as pp
from pandapower.diagnostic import parallel_switches

net = pp.create_empty_network()
pp.create_buses(net, 2, 110)
pp.create_bus(net, 20)
pp.create_line(net, 0, 1, 5, "149-AL1/24-ST1A 110.0")
pp.create_transformer(net, 0, 2, "40 MVA 110/20 kV")
pp.create_switch(net, 0, 0, "l")
pp.create_switch(net, 0, 0, "t")
pp.create_load(net, 1, 5)
pp.create_load(net, 2, 5)
pp.create_ext_grid(net, 0)
pp.runpp(net)

assert not len(parallel_switches(net)[0])`

**Comment by julffers** [comment]
Good catch! The implementation did not consider switches with different element_types having the same bus index/element index combination. Was easy to fix though.
