### ISSUE TITLE
Data type of pwl cost points

### ISSUE THREAD

**Issue by friederikemeier** [e2nIEE/pandapower#315]
Hi,

As it is implemented now, the pwl cost points are a tuple.
But: 'tuple' does not support item assignment!

When migrating my code, where I am changing the slope of pwl costs, I now have to convert the tuple to a list, do stuff and then convert it back to a tuple.

Could we consider changing this?
Before we had an array of lists, where item assignment was no problem. I don't know, what's the ideal way, but using a tuple is inefficient for my use case.

**Comment by lthurner** [comment]
Yeah you are right tuples are immutable, which makes it kind of unpractical to change the costs. I don't see why it couldn't be a list of lists.

**Comment by lthurner** [comment]
So we just have to change the documentation for this, right? Already seems to work with lists as it is.
