### ISSUE TITLE
wrong documentation of estimation.remove_bad_data

### ISSUE THREAD

**Issue by marhofmann** [e2nIEE/pandapower#329]
There is an invalid keyword parameter 'chi2_prob_false' for the function 'estimation.remove_bad_data' described in the documentation. On the other hand the parameter 'ref_power' which is a valid parameter for this function is not described in the documentation.

**Comment by marhofmann** [comment]
'ref_power' is also not described in 'estimation.estimate' and 'estimation.chi2_analysis'

**Comment by jhmenke** [comment]
Thanks for the info, i will take a look and correct these mistakes.

**Comment by jhmenke** [comment]
ref_power is not relevant anymore in pp 2.0. i corrected the deprecated parameter.
