### ISSUE TITLE
Tracing upstream and downstream

### ISSUE THREAD

**Issue by GirishVC86** [e2nIEE/pandapower#351]
Are there any functions available for tracing upstream to source or downstream trace from source to sink.

**Comment by lthurner** [comment]
I think you will have to describe more precisly what you mean by that?

**Comment by GirishVC86** [comment]
Tracing is used to find all features connected to the same feeder system. Upstream trace from Load to Source, downstream trace from Source to all connected Load with intermediate elements. If I change the switch position within given network then Line element parameter "From" and "To" does not change.

**Comment by lthurner** [comment]
Check out the topology module, I think it does exactly what you are looking for: https://github.com/e2nIEE/pandapower/blob/develop/tutorials/topology.ipynb

**Comment by lthurner** [comment]
Closed for inactivity, if you have any more questions feel free to reopen.
