### ISSUE TITLE
topology - Why does unsupplied_buses have a parameter in_service only?

### ISSUE THREAD

**Issue by julffers** [e2nIEE/pandapower#357]
The topology function unsupplied_buses has a parameter "in_service_only". If True, unsupplied buses, that are out of service are removed from the returned result. Why does this paramter exist? If a pandapower net and no multigraph are passed to unsupplied buses, create_nx_graph creates a multigraph that does not contain out of service buses anyway.

Is there any reasonable case, where one would pass a net AND a multigraph that does not correctly represent the net and therefore, the out of service buses would have to be removed from the result?

**Comment by lthurner** [comment]
I remember @rbolgaryn requested this feature, but looking at it now I am also not sure why it exists. The implementation is also not very efficient with iterating over the buses and then indexing with .loc. Seems like a functionality that can be deprecated to me.

**Comment by FlorianShepherd** [comment]
Please removetthis feature @julffers
