### ISSUE TITLE
Should estimate_voltage_vector be moved from topology to estimation?

### ISSUE THREAD

**Issue by julffers** [e2nIEE/pandapower#358]
The topology function estimate_voltage_vector is exclusively used by the estimation module and it does nothing topology related. Shouldn't we move it to the estimation module?

**Comment by jhmenke** [comment]
it's a general utility function which could be used by other functions. but if it's not, i don't have a problem with moving it to the estimation modiule.

**Comment by FlorianShepherd** [comment]
please move it to estimation
