### ISSUE TITLE
create logarithmic colormap

### ISSUE THREAD

**Issue by dlohmeier** [e2nIEE/pandapower#360]
There are two convenience functions in plotting.colormaps for creating continuous or discrete colormaps with the respective normalization for the given maximum/minimum values. I recently had to create a logarithmic scale for one of my colormaps, which in general works quite similar to the continuous colormap creation. This is the code I wrote:

    from matplotlib.colors import LogNorm, LinearSegmentedColormap

    def cmap_logarithmic(min_value, max_value, colors):
        num_values = len(colors)
        if num_values < 2:
            raise UserWarning("Cannot create a logarithmic colormap with only %d colors." % num_values)
        if min_value <= 0:
            raise UserWarning("The minimum value must be above 0.")
        if max_value <= min_value:
            raise UserWarning("The upper bound must be larger than the lower bound.")
        values = np.arange(num_values + 1)
        diff = (max_value - min_value) / (num_values - 1)
        values = (np.log(min_value + values * diff) - np.log(min_value))\
                 / (np.log(max_value) - np.log(min_value))
        cmap = LinearSegmentedColormap.from_list("name", list(zip(values, colors)))
        norm = LogNorm(min_value, max_value)
        return cmap, norm

This code gives really nice results. It is rather short and simple, most of the code is just checking of validity. Maybe it should be possible for the user to define his own values which then have to be transformed to the space between 0 and 1, but I guess that most users will happily let the function itself define all the intermediate steps with the same scale as the logarithmic normalization does (that's exactly what is implemented here).
Could this be integrated in pandapower?

**Comment by FlorianShepherd** [comment]
yes nice idea :)
