### ISSUE TITLE
Outdated docstrings in create_sgen and create_gen functions

### ISSUE THREAD

**Issue by gdgarcia** [e2nIEE/pandapower#372]
Some parts of the docstrings of create/create_sgen and create/create_gen functions still refer to sgen and gen as created using the _consumer system_.
But according to the **new documentation**, they are in fact created using the **generator convention** since pandapower 2.0.0, as told in [Unit System and Conventions](https://pandapower.readthedocs.io/en/v2.0.1/about/units.html#conventions)
Is this issue correct? Am I missing something?
If it's correct, I'd like to update the docstrings accordingly.
Thanks.

**Comment by ascheidl** [comment]
hello,

you are correct. Seems like the docstrings are partially not updated yet.

If you want to help to correct the docstrings please make a pull request.

cheers,
alex
