### ISSUE TITLE
current limited voltage source

### ISSUE THREAD

**Issue by hariramtud** [e2nIEE/pandapower#374]
hallo developers,

Is it possible to model a "Current limited voltage source" in padapower ?

**Comment by jurasofish** [comment]
You're perhaps looking for a static generator

**Comment by hariramtud** [comment]
Thanks. I am not looking for a static generator. I am looking for a method to create a DC offset in the LV side of the transformer through a current limited voltage source which will create a Virtual neutral point. I want to model this to find the short circuit level at that point where the current limited voltage source is connected.

**Comment by lthurner** [comment]
sgens can be modeled as a constant current source if you want to assign a fixed current to an element. I don't know how a current limited voltage source would be modeled. What you describe does not sound like anything that is within the IEC 60909 standard, which the pandapower short-circuit module implements. It is detailed [here](https://pandapower.readthedocs.io/en/v2.0.1/shortcircuit/ikss.html#voltage-source-contribution) how the short-circuit current is calculated. I would not know how to implement something like a current limited voltage source in this framework.

**Comment by lthurner** [comment]
Closed for inactivity, please reopen if you want to discuss this furthere or have a specific question.
