### ISSUE TITLE
Finding the Nearest Transformer

### ISSUE THREAD

**Issue by rahulkhatri121** [e2nIEE/pandapower#383]
Hi All ,

I have a network , in which I want to find the effect of adding the sgen element to nearest transformer connected. For that could any one of you have an idea that how I find the nearest transformer(index) which is connected to sgen bus  ?  

Thanks in advance :)

**Comment by ascheidl** [comment]
Hi,

you can use the topology package. See https://pandapower.readthedocs.io/en/v2.0.1/topology.html
or
https://www.youtube.com/watch?v=ubpHrrMA63A&list=PLWIXcESdYmbxuDXSrARFZaqU3qR3JbGR5&index=9

In your case, with
`d = pd.DataFrame([top.calc_distance_to_bus(net, b) for b in net.trafo.lv_bus.values])`

you can find the nearest transformer of bus 123 with `d[123].idxmin()`

cheers
alex

**Comment by rahulkhatri121** [comment]
Hi Alex,

Thanks alot ;)

**Comment by ascheidl** [comment]
had to edit the code ...  first version gave the lv_bus of the transformer ... now it should give the index
