### ISSUE TITLE
Power Flow Not Converging -Matrix is exactly singular

### ISSUE THREAD

**Issue by rahulkhatri121** [e2nIEE/pandapower#392]
Hi All ,

I am trying to simulate a distribution grid, however after creating the network, I am getting the following matrix rank warning error ,

''
C:\Users\r31982\Continuum\anaconda3\lib\site-packages\scipy\sparse\linalg\dsolve\linsolve.py:192: MatrixRankWarning:

Matrix is exactly singular ''

Did anyone else also experience this issue ? Or any help , where I am doing something wrong. 

Thanks :)

**Comment by lthurner** [comment]
Have you tried the diagnostic function: https://pandapower.readthedocs.io/en/v2.0.1/powerflow/diagnostic.html?

**Comment by lthurner** [comment]
Closed for inactivity, please reopen if you have a specific question.
