### ISSUE TITLE
No module

### ISSUE THREAD

**Issue by heinlmic** [e2nIEE/pandapower#393]
Hello,
I have installed latest version of PP and I have tried import module:
`import pandapower.networks as nw`

but I get error
```
import pandapower.networks as nw
ModuleNotFoundError: No module named 'pandapower.networks'; 'pandapower' is not a package
```

What am I doing wrong?

**Comment by lthurner** [comment]
Do you have multiple Python versions installed and maybe installed it in a different python installation / environment?

**Comment by heinlmic** [comment]
Thanks for advice.
Solution was very easy and I am stupid. I named my project pandapower.py and that was the biggest problem.

**Comment by agaa2** [comment]
Can someone help me? I have the same problem ModuleNotFoundError: No module named 'pandapower', In which environment should I install pandapower? I get only python 3, and I installed pandapower in pypsa environment
