### ISSUE TITLE
line impedence

### ISSUE THREAD

**Issue by Prashantgrid** [e2nIEE/pandapower#394]
Dear engineers and developers,

Is there any sophisticated method to calculate the overall line impedence between any two buses.
I need the values of effective line impedence for inverter control.

**Comment by lthurner** [comment]
There is no function that does this, but you can use the topology searches for that. Networkx can find the paths and then you can calculate the impedance from that. This should point you in the right direction:

```
import pandapower.networks as nw
import pandapower.topology as top
import networkx as nx
net = nw.create_cigre_network_hv()
mg = top.create_nxgraph(net)
for path in nx.all_simple_paths(mg, 3, 11):
    lines = top.lines_on_path(mg, path)
    print("path with resistance %.2f"%net.line.r_ohm_per_km.loc[lines].sum())
```

**Comment by lthurner** [comment]
If you do implement a function that calculates the impedance between two buses that would be a very good function to add to the pandapower toolbox. Please feel free to open a pull request if you have implemented that.

**Comment by FlorianShepherd** [comment]
Please feel free to reopen the issue if you have any further questions or open a pull request.
