### ISSUE TITLE
Capital letters in 3ph implementation

### ISSUE THREAD

**Issue by ascheidl** [e2nIEE/pandapower#409]
In 3ph powerflow implementation we use capital letters to refer to the phase, eg "p_A_mw"

Shouldnt we always use lower case letters because special cases aren't special enough to break the rules? On the other hand, practicality beats purity.

**Comment by lthurner** [comment]
I would also argue to keep everything lower case, I don't see why it couldn't be "p_a_mw"

**Comment by lthurner** [comment]
@shankhoghosh  please consider this

**Comment by shankhoghosh** [comment]
Sorry, just saw this in yesterday's meeting. Changed everything to lower case now.
