### ISSUE TITLE
convert argument in the loading functions of the file_io.py module

### ISSUE THREAD

**Issue by gdgarcia** [e2nIEE/pandapower#410]
Hi,

The docstrings of the functions **_from_pickle_**,  **_from_excel_**, **_from_json_**, **_from_json_string_** and **_from_json_dict_** of the module file_io.py are a little bit confusing in regarding the argument *convert* (used, as far I could understand, to control the conversion of the older version format to the new one):

- _from_pickle_,  _from_excel_, _from_json_, _from_json_string_:  *convert* is listed as an output and its role (controlling the conversion of the older version format to the new one) is missing; 

- _from_json_dict_: *convert* is listed as an output, but its not an output nor ans argument of the function;

If my points are correct and I'm not misunderstanding something, I'd like to update the docstrings accordingly.

Thanks!

Glaucon

**Comment by lthurner** [comment]
> If my points are correct and I'm not misunderstanding something, I'd like to update the docstrings accordingly.

Yes you are right about that, a PR would be appreciated
