### ISSUE TITLE
Cost Function n-polynomial

### ISSUE THREAD

**Issue by Misbahrani** [e2nIEE/pandapower#416]
hello
Kindly tell me how to apply the n-polynomial cost function for n=2:
fpol(q)=c2q2+c1q+c0
in the given format
pp.create_polynomial_cost(net, 0, 'sgen', np.array([0,1, 0]) is given
if I go for np.array[1 1 1] then how to incorporate c2, c1, c0

**Comment by lthurner** [comment]
I am assuming this question is answered with #418, if not feel free to reopen.
