### ISSUE TITLE
create_polynomial_cost function error

### ISSUE THREAD

**Issue by Misbahrani** [e2nIEE/pandapower#418]
Hello
I am trying to implement quadratic cost funciton, and m getting following errros:
![image](https://user-images.githubusercontent.com/52325843/60713291-35b8de80-9f32-11e9-89f3-7ea265674140.png)
![error1](https://user-images.githubusercontent.com/52325843/60713330-4ec18f80-9f32-11e9-9867-b9e98f480acb.PNG)
and following:
![image](https://user-images.githubusercontent.com/52325843/60713400-787ab680-9f32-11e9-9e63-154c262e57db.png)

**Comment by friederikemeier** [comment]
Hi, the function was renamed in pandapower 2.0 and it is now created without the numpy array. Please check the documentation of the function!
Thats what it is now:

`create_poly_cost(net, element, et, cp1_eur_per_mw, cp0_eur=0, cq1_eur_per_mvar=0,
                           cq0_eur=0, cp2_eur_per_mw2=0, cq2_eur_per_mvar2=0, type="p", index=None)`

**Comment by lthurner** [comment]
Please see also the documentation that differences between 1.6 and 2.0: https://pandapower.readthedocs.io/en/v2.0.1/about/update.html#cost-functions

**Comment by Misbahrani** [comment]
Okay, thank you so much
