### ISSUE TITLE
Confusing  documentation for signing system

### ISSUE THREAD

**Issue by marhofmann** [e2nIEE/pandapower#431]
Please change the description of the signing system under "Unit System and Conventions"

https://pandapower.readthedocs.io/en/v2.1.0/about/units.html

The signing system of gen, sgen, and ext_grid is described as follows:
"There are three elements that have power values based on the generator viewpoint (positive active power means power consumption), which are (...)"

This is quite confusing and not correct!

I propose to replace "consumption" by "generation"

**Comment by lthurner** [comment]
You are right about that, this has already been fixed in #422 though. Its in the develop docs: https://pandapower.readthedocs.io/en/develop/about/units.html and will be included in the next release.
