### ISSUE TITLE
Calculation of R/X Ration at any Bus

### ISSUE THREAD

**Issue by rahulkhatri121** [e2nIEE/pandapower#440]
Hello Everyone and Pandapower Awesome Developers, 

I am in quest/search of some method to calculate the R/X ratio at any point (say Bus/Node) of pandapower network, which takes care of the equivalent network impedance at that point considering all the lines and transformers. 

If you know , how we can do it , I would be really happy to know :)

Thanks

Cheers,

Rahul

**Comment by lthurner** [comment]
Have you looked into the short-circuit module? It includes a calculation of short-circuit impedances at all buses: https://pandapower.readthedocs.io/en/v2.1.0/shortcircuit/ikss.html#voltage-source-contribution

**Comment by FlorianShepherd** [comment]
If you have any further questions, please reopen!
