### ISSUE TITLE
Pypower treats generators as controllable in the OPF (ppc['gen']). 

### ISSUE THREAD

**Issue by jwiemer112** [e2nIEE/pandapower#457]
There is a workaround to nearly disable this behaviour:

    # GEN
    E = 1e-3 # epsilon as a tolerance
    net.gen['controllable'] = False
    
    # Workaround, because pypower considers gen's as controllable per default
    net.gen['max_p_mw'] = net.gen.p_mw * (1+E)
    net.gen['min_p_mw'] = net.gen.p_mw * (1-E)

As discussed, there should be another implementation to fix this behaviour.

**Comment by SteffenMeinecke** [comment]
Obviously, this issue was solved in the meantime.
