### ISSUE TITLE
[Feature request] pp.create_{buses, lines, ...}_from_dataframe()

### ISSUE THREAD

**Issue by bergkvist** [e2nIEE/pandapower#466]
## How it could work

```py
net = pp.create_empty_network()
pp.create_buses_from_dataframe(net, df_buses)
pp.create_lines_from_dataframe(net, df_lines)
...
pp.runpp(net)
```

The column names of df_buses should match the parameters passed to `pp.create_bus(net, **params)` and so on.

In case a required column is missing, or contains invalid values, an error should be thrown. If some parameters/columns are missing, but has default values, these should be used.

### Creating a large pandapower network from individual components is slow
Running `pp.create_*` for all of my components (which are already stored in dataframes) takes around 6 minutes. In contrast, importing/exporting as json file after creating the network takes less than 1 second! I imagine there must be some room for improvement here, if the components could be created in bulk.

From what I can tell, it seems like `net` is simply a collection of dataframes (buses, lines etc). It also seems like `net` to some extent is aware of which dataframes it contains. Since I haven't inspected the source code, I'm not sure to what extent this is the case.

```py
del net.generator
pp.runpp(net) # This runs into problems because net believes net.generator exists
```

**Comment by friederikemeier** [comment]
Hi! You are so right ;) Actually we are just discussing this as the moment in #444 
So I'm closing this because it's a duplicate. 

Considering your last remark: Yes, it is aware of which dataframes it contains, the base is always an "empty network" with specific empty dataframes.
