### ISSUE TITLE
improvements of the estimation module

### ISSUE THREAD

**Issue by jhmenke** [e2nIEE/pandapower#48]
Some improvements can be made to the estimation module in order to increase reliability:

- [ ] bad data removal (rn_max) is not reliable all the time

I don't expect to work much on this this year though. Any help from potential users is highly appreciated.
The estimation module is still very much usable, but has some limitations.

Also there is some refactoring/testing work, which i plan to do this year:
- [ ] wls_matrix_ops should be refactored to use the ppc and its matrices more
- [ ] writing unit tests for bad data detection, line current measurements from examples in the "Power System State Estimation" book

**Comment by jhmenke** [comment]
the Ybus matrices are the same, so that can be ruled out as the cause of non-convergence

**Comment by lthurner** [comment]
Do we have tests of these cases of non-convergence and other cases that lead to problems? Maybe they could be included in the test suite but skipped for now as known bugs / problems to avoid the test suite failing entirely?

**Comment by jhmenke** [comment]
The only bug was with the phase-shifting transformers, which is now fixed with commit dfa39edc19270bf8.

The rest are inherent limitations of the WLS SE, r_n_max test in their current implementations. Anyone is free to improve them.

**Comment by jhmenke** [comment]
only res_bus_est, res_line_est, res_trafo_est, res_trafo3w_est are explicitly written now. the functionality will stay limited to this for the time being.

**Comment by jhmenke** [comment]
there has not been any interest in optimizing the current estimation module. 
bad data and a line current test are implemented in the dev_2.0 branch, although the number of tests could be improved (as always).

i'm closing this issue due to lack of interest.
