### ISSUE TITLE
How to incorporate start-up & shutdown costs?

### ISSUE THREAD

**Issue by Misbahrani** [e2nIEE/pandapower#480]
Hello,
I want to implement the start-up and shutdown costs of the generators. AS the operational cost estimation using both polynomial and piece-wise linear functions is easily done in pandapower, I was wondering to expand the cost estimation,and want to incorporate startup costs, so at OPF the cheapest generators is turned ON first. Plus i want to incorporate ramp limits and start-up time. How to do that in pandapower framework?
Best regards,
Misbah Rani

**Comment by lthurner** [comment]
Hi, good question, this would indeed be very helpful feature. The reason this is so tricky is that this adds discrete optimization variables to your problem which makes it harder to solve. I don't think this is possible with the PYPOWER OPF that is used in pandapower by default. The best possibility is probably to do this is by going through the PowerModels interface, which allows a pretty modular definition of the optimization problem. Have you checked if this is possible in PowerModels?

**Comment by Misbahrani** [comment]
Thanks for replying. I don't know about powermodels.

**Comment by lthurner** [comment]
You can find a documentation about how to use pandapower with powermodels here: https://pandapower.readthedocs.io/en/v2.1.0/opf/powermodels.html

You can first check out the capabilities of PowerModels here: https://lanl-ansi.github.io/PowerModels.jl/stable/ or if you don't find any information on this open an issue on the powermodels repo: https://github.com/lanl-ansi/PowerModels.jl

**Comment by Misbahrani** [comment]
Okay thanks a lot for helping me, I really appreciate it. I will check them
out.
