### ISSUE TITLE
Bugs in Doku

### ISSUE THREAD

**Issue by fmarten-bit** [e2nIEE/pandapower#483]
Hey,

in der pandapower-Doku müssten folgende Dinge aktualisiert werden:

* In dem Colormap-Beispiel:
https://pandapower.readthedocs.io/en/v2.1.0/plotting/matplotlib/create_colormaps.html
wird "continous" geschrieben, das müsste "continuous" sein. Auch in dem Import-Statement unten bitte nachbessern, da das Code-Beispiel sonst nicht funktioniert.

* In der Doku zu Sgen und Generator steht immer noch, dass Wirk- und Blindleistung negativ sein müssen. Das ist mittlerweile nicht mehr so, glaube ich. Bitte Doku aktualisieren.

Viele Grüße!

**Comment by thomaswolgast** [comment]
Hallo,

soweit ich das überblicke ist der zweite Punkt hier im develop branch bereits behoben und einfach noch nicht online. 
Bezüglich der Schreibfehler ist es wahrscheinlich das einfachste, wenn du sie selbst schnell behebst und ein pull request machst (ist nicht kompliziert).

Viele Grüße!
