### ISSUE TITLE
Single Phase Short Circuit Calculation - zero sequence parameters

### ISSUE THREAD

**Issue by chefPony** [e2nIEE/pandapower#523]
Hello, I am trying to run a single phase short circuit calculation so looking at the tutorial I found :
```
net = ring_network()

#r/x ratio in zero sequence parameters
net.ext_grid["r0x0_max"] = 0.4
net.ext_grid["x0x_max"] = 1.0

#zero sequence line parameters
net.line["r0_ohm_per_km"] = 0.244
net.line["x0_ohm_per_km"] = 0.336
net.line["c0_nf_per_km"] = 2000

#transformer vector group, zero sequence short circuit voltage
#and zero sequence magnetizing impedance
net.trafo["vector_group"] = "Dyn"
net.trafo["vk0_percent"] = 5.
net.trafo["vkr0_percent"] = 0.4
net.trafo["mag0_percent"] = 10
net.trafo["mag0_rx"] = 0.4
net.trafo["si0_hv_partial"] = 0.9

```
1) Not all these parameters are self explicative, and I could not find them in the documentation. In particular in the trafo table I am not able to recognize what `mag0_percent, mag0_rx, si0_hv_partial` are with respect to my network data.

2) Is there a way to create the network object specifying these parameters inside the element's dataframes instead of having to manually insert them directly inside the network? Something like 

```
#line_df is a pandas dataframe containing all the line parameters
line_df["r0_ohm_per_km"] = r0_ohm_per_km_vec
line_df["x0_ohm_per_km"] = x0_ohm_per_km_vec
line_df["c0_nf_per_km"] = c0_nf_per_km

net = pp.create_empty_network()

for _,line_i in line_df.iterrows():
         pp.create_line_from_parameters(net, **line_i)
```
If I do as above `net.line` does not have the `r0_ohm_per_km ,  x0_ohm_per_km, c0_nf_per_km` columns.  In general I think it would be better to have the possibility of adding extra columns to the elements' dataframe and then having them reflected on dataframes inside the network object, even if they store data don't needed for calculation. 
For example:
```
#line_df is a pandas dataframe containing all the line parameters
line_df["foo"] = 0
net = pp.create_empty_network()

for _,line_i in line_df.iterrows():
         pp.create_line_from_parameters(net, **line_i)

net.line['foo'] #should return 0
```

Thanks for your help!

**Comment by lthurner** [comment]
You are right that documentation for unbalanced parameters is still lacking.

You should check out the branch unbalanced_pf_2.0 which contains the most advanced version of the unbalanced developments (not only single phase short circuits but also unbalanced power flow). There is also a documentation of this branch on readthedocs. Some of the parameters are defined there: https://pandapower.readthedocs.io/en/unbalanced_pf_2.0/elements/trafo.html#input-parameters. I hope we can merge the changes into the develop branch soon so they are easier to find.

With regards to adding the parameters you are right that it is not a good practice having to add the parameters directly. The best way to currently do this is by using the add zero impedance function (see an example [in the tests](https://github.com/e2nIEE/pandapower/blob/96e440ffcd54b079d319f88333b590e17922ef61/pandapower/test/shortcircuit/test_1ph.py#L50)). This of course only works if the parameters are stored in the standard type library. I agree that we should allow a more transparent way to add parameters directly in the dataframes. I will open a seperate issue about this.
