### ISSUE TITLE
output writer log of inputs

### ISSUE THREAD

**Issue by FlorianShepherd** [e2nIEE/pandapower#550]
We agreed to change that OutputWriter in timeseries so that it has the following features:

- logging of tables, parts of tables and logging with function evaluations (e.g. pd.min / max) is possible
- per default "res_bus.vm_pu" and "res_line.loading_percent" is logged
- output_writer is stored in net.output_writer and must not be given to run_timeseries()

All of this works. However some things are to keep in mind:

1. Inputs can be defined in several ways, but only the "largest requirement" is stored. For example one wants to store parts of res_line.loading_percent then still *all* loading_percent values are stored, since they are in the defaults. This means that, this:
```
ow = OutputWriter()
ow.log_variable('res_line', 'loading_percent', index=[0, 2, 5]) 
```
is now equal to the old implementation:

```
ow = OutputWriter()
ow.log_variable('res_line', 'loading_percent')
ow.log_variable('res_line', 'loading_percent', index=[0, 2, 5]) 
```
If only `index=[0,2,5]` are to be stored than `OutputWriter` must be initialized like `ow = OutputWriter(log_variables=list())` to log nothing by default and the added variables are logged.

2. multiple output_writer are not possible. Only one output_writer is stored in net. If you "deepcopy" some output_writer, which was done in some tests (see 090cbcb21440aa13cf39fbe92f9ec06069e0acbc), then only the original version in net.output_writer is used. I'd not recommend to allow multiple output_writer in net. This would require to loop over these each time something is saved and may lead to undesired behaviour (like overwriting files by the different output_writers).

**Comment by carolinefernandesfarias** [comment]
Is it possible to store the Dispatch Cost for each time step using the output_writer?
