### ISSUE TITLE
PandaPower way of plotting TCC Curves 

### ISSUE THREAD

**Issue by Muda413** [e2nIEE/pandapower#554]
Hi All,

PandaPower noob here and still trying to wrap my head around how to make the best use of this.

**Is there a function one can call to draw TCC curves to be used for protection coordination analysis / studies?** 

**If no, how can I plot a TCC curve of loads connected to a bus the panda power way?** 

_Like the TCC curve of a section of a network connected to motors, transformers, circuit breakers(switches) and other loads downstream of the bus_

**Comment by lthurner** [comment]
pandapower does have a short-circuit module, but currently no dedicated protection module. So TCC curve plotting is not part of the framework (you would have to implement it yourself).

Finding downstream buses and loads is however easily possible with the topology module: https://pandapower.readthedocs.io/en/v2.1.0/topology.html
