### ISSUE TITLE
OPF verbose bug

### ISSUE THREAD

**Issue by camiloromers** [e2nIEE/pandapower#580]
There's a little bug when your print OPF results, even in the develop version. The number of transformers are not correct. It seems that it takes the same number of lines. Here's the code I am using:

```
import pandapower.networks as ppnw
net = ppnw.case14()
net.poly_cost.loc[0, 'cp1_eur_per_mw'] = 100
net.gen.loc[[1,2,3], 'p_mw'] = [20, 30, 10]
net.gen.loc[[1, 3], 'controllable'] = False
pp.rundcopp(net, verbose=True)
print (net.res_gen)
```

And the results in the summary report (how many?) are incorrect. You might check as well in all tutorials you have and you will see a similar behavior.

**Comment by FlorianShepherd** [comment]
@camiloromers are you using the pp.opf_task(net) function or what do you mean by summary report?

**Comment by FlorianShepherd** [comment]
This report is misleading. 

The "report" function is a legacy from pypower / matpower. The printed results reflect the gens in the internal ppc format, which is the one used by the OPF. The report is not referring to the pandapower elements. 

A quick fix would be to add a notice. However, a report function with the pandapower elements would be nice.

**Comment by camiloromers** [comment]
In every OPF report, the number of transformer are always the same the number of buses. In the current case, should be 5 and not 20. I compared with others grid and the same bug is present.

<img width="654" alt="Screen Shot 2019-12-18 at 4 53 58 PM" src="https://user-images.githubusercontent.com/48441162/71101435-fe27b100-21b6-11ea-9d13-304933d71fd3.png">

**Comment by FlorianShepherd** [comment]
So the values are also wrong for the ppc?
