### ISSUE TITLE
simply_plotly() throws error when trying to create artificial coordinates

### ISSUE THREAD

**Issue by jacksonzche** [e2nIEE/pandapower#619]
Tutorial on 'Plotting Pandapower Networks using Plotly - Plots without geodata' available is broken in version 2.2.0. Simple_plotly() calls create_generic_coordinates() using 'respect_separation_points=bool'. Function is still expecting 'respect_switches=bool' as relevant argument name changes in generic_geodata.py were reverted in Dec 11 2019 commit.

**Comment by FlorianShepherd** [comment]
@dlohmeier do you know the reason for this?

**Comment by dlohmeier** [comment]
Sorry, there was some refactoring going wrong. Should create a hotfix... it should all be fixed in #622 . Can we create a hotfix for this?

**Comment by FlorianShepherd** [comment]
Yes sure, maybe together with the other bugs that @rbolgaryn found. @rbolgaryn Can you give an estimate when you can have a look at the deepcopy problem? What about #609 and #610 is this fixed or not (the PR message looks like you've fixed it)?
