### ISSUE TITLE
Inclusion of data packages for installation

### ISSUE THREAD

**Issue by dlohmeier** [e2nIEE/pandapower#625]
I just came to realize that csv-data is not included in the MANIFEST.in . This leads to the problem that for anyone who installs pandapower via pip, any csv-data is not included in the build and thus e.g. the time_series test would fail, as the data_source is given as .csv file. Are there any oppositions to adding a global-include *.csv to the MANIFEST.in?

**Comment by dlohmeier** [comment]
I added this to PR #627 .

**Comment by FlorianShepherd** [comment]
No I forgot to include that. I thought I'v tested it but apparenlty made a mistake. Thanks @dlohmeier
