### ISSUE TITLE
pandapower 2.2.1 - fix

### ISSUE THREAD

**Issue by FlorianShepherd** [e2nIEE/pandapower#628]
In pandapower 2.2.0 are some issues we need to fix asap. These include:

- https://github.com/e2nIEE/pandapower/issues/625 todo @rbolgaryn ?
- https://github.com/e2nIEE/pandapower/issues/620 fixed by @dlohmeier 
- https://github.com/e2nIEE/pandapower/issues/619 fixed by @dlohmeier 

possibly these:
- https://github.com/e2nIEE/pandapower/issues/610
- https://github.com/e2nIEE/pandapower/issues/609
@rbolgaryn are these fixed or not? You mentioned the PRs which seemed to fix it?

**Comment by dlohmeier** [comment]
#625 is done as well

**Comment by rbolgaryn** [comment]
#609 and #610 are fixed

**Comment by FlorianShepherd** [comment]
great. Thanks guys, then I'll can upload the fix tomorrow :+1:

**Comment by dlohmeier** [comment]
We should include #629 in here. That is also a simple fix.

**Comment by jhmenke** [comment]
#631

**Comment by dlohmeier** [comment]
#608 was fixed by @friederikemeier

**Comment by FlorianShepherd** [comment]
> #631

should be fixed / worked around by: e8556507448037a94127383cbf81900298793614
