### ISSUE TITLE
sphinx-rtd-theme

### ISSUE THREAD

**Issue by SimonRubenDrauz** [e2nIEE/pandapower#629]
At the moment it is not possible to create the pandapower documentation if you haven't installed sphinx-rtd-theme before. Would it be possible to add sphinx-rtd-theme to the setup.py requirements?

**Comment by FlorianShepherd** [comment]
sounds good to me :)

**Comment by SimonRubenDrauz** [comment]
Perfect, I will fix it and make a pull request ;)
