### ISSUE TITLE
Issue with pandapower simulation

### ISSUE THREAD

**Issue by MabroukAhmed** [e2nIEE/pandapower#649]
Hi, 
When I try to run pandapower simulation for a network composed with 9 buses using the following loads for each bus (see photo), I obtained the following error. 
I used the standard network implemented in pandapower:

net = pandapower.networks.four_loads_with_branches_out()

<img width="1200" alt="Screenshot 2020-02-06 at 16 47 57" src="https://user-images.githubusercontent.com/7476584/73991324-a416b280-4900-11ea-93fc-bc46dfb919ad.png">

**Comment by ascheidl** [comment]
Hi,

use pp.diagnostic(net) to get a first guess what might be wrong with your grid in case pp.runpp does not converge.

In your case it shows "overloading" - scaling all loads down by factor 0.1 solves the convergence problem. (The network is a low voltage grid)

Cheers,
alex

**Comment by MabroukAhmed** [comment]
Hi Alex, 

I think that I should scale all load values between 0 and 1 because I have some load values in my database bigger than 3kv.

Thanks, 
Ahmed

**Comment by SteffenMeinecke** [comment]
I don't think that there is a simple way to calculate the maximum load which allowes runpp to converge.
