### ISSUE TITLE
Change generator to static generator bus

### ISSUE THREAD

**Issue by MabroukAhmed** [e2nIEE/pandapower#660]
Hi, 

I'm actually trying to use standard network defined in pandapower library IEEE30 to make time series data simulations:
net = pandapower.networks.case_ieee30()
In this network, the following buses are used to model the grid:
- bus (30 elements)
- load (21 elements)
- gen (5 elements)
- shunt (2 elements)
- ext_grid (1 element)
- line (34 elements)
- trafo (7 elements)
- poly_cost (6 elements)
- bus_geodata (30 elements)
In this case, I would like to know if there is a way (using python script) to convert or change the type of  generator buses to static generator ones?
I tried to set the boolean variable controllable of net.gen to false but it does not work, since the simulations (with different load values) return always the same "vm_pu" values.
Any help please?
Thanks

**Comment by SteffenMeinecke** [comment]
The parameter "controllable" is used for optimal power flow (runopp). If you would like to replace generators by static generators, use the toolbox function replace_gen_by_sgen().

**Comment by SteffenMeinecke** [comment]
If the answers to your issues are sufficient, please close the issues.
