### ISSUE TITLE
convert generator to static generator

### ISSUE THREAD

**Issue by MabroukAhmed** [e2nIEE/pandapower#661]
Hi, 

I'm actually trying to use standard network defined in pandapower library IEEE30 tom make time series data simulations:
net = pandapower.networks.case_ieee30()
In this network, the following buses are used to represent the grid:
- bus (30 elements)
- load (21 elements)
- gen (5 elements)
- shunt (2 elements)
- ext_grid (1 element)
- line (34 elements)
- trafo (7 elements)
- poly_cost (6 elements)
- bus_geodata (30 elements)
For this example, I would like to know if there is a way (using python script) to convert some generator buses to static generator ones?
I tried to set the boolean variable controllable of net.gen to false but it does not work, since the simulations return always the same "vm_pu".
Any help please?
Thanks

**Comment by Amonara** [comment]
Hi,
well you may use straight forward method. Simply make a loop to take variables from gens and transfer them to sgens. Then turn gens out of service.

`buses = nw.gen.bus.values

for i in buses:
    pp.create_sgen(net, bus=net.gen.bus.loc[i], p_mw=net.gen.p_mw.loc[i])
    nw.gen.in_service.loc[i] = False`

**Comment by MabroukAhmed** [comment]
Hi, 

Thank you for the response. However, we don't need to mention the q_mv when we create sgen?

**Comment by Amonara** [comment]
Hi, sorry for late respond. Not necessary. Look at the PP documentation. Q_mvar will be set on 0.
