### ISSUE TITLE
Fail to load .mat file

### ISSUE THREAD

**Issue by mzy2240** [e2nIEE/pandapower#665]
Generate the .m file using PowerWorld and then load the .m file in Matlab to save the workspace as .mat file. (Also rename the workspace to mpc before saving) Then the .mat file still cannot be loaded by pandapower because in the .mat file ncost = 4 instead of 2 or 3. A dirty fix if you only need to run PF is to change the condition ncost == 3 to ncost in [3, 4].

**Comment by mzy2240** [comment]
That is to say, you need to modify the pypower script in the converter folder to support the case where ncost = 4.

**Comment by SteffenMeinecke** [comment]
If it still does not work, please reopen the issue.
