### ISSUE TITLE
Minimal 1ph short circuit current

### ISSUE THREAD

**Issue by chefPony** [e2nIEE/pandapower#668]
Hello,
is this feature gonna be implemented? It would be very useful in my opinion, in many practical application of protection selectivity  and sizing studies the most important short circuit currents to consider are:
- maximal 3ph (implemented)
- minimal 1ph (not implemented yet)

Thanks

**Comment by lthurner** [comment]
Yes thats true. I actually don't remember why this is not possible, maybe there are some exception in the standard for minimum 1ph short circuits? I suggest removing the exception and checking the results of the 1ph minimum SC against a commercial tool. As mentioned in #675 I can't promise to get to it soon, but you are welcome to look into it yourself.
