### ISSUE TITLE
Missing documentation on net.res_line

### ISSUE THREAD

**Issue by bergkvist** [e2nIEE/pandapower#673]
The following result parameters seem to be missing in [the documentation](https://pandapower.readthedocs.io/en/v2.2.1/elements/line.html#result-parameters):

 - vm_from_pu
 - va_from_degree
 - vm_to_pu
 - va_to_degree

This is part of my output from `net.res_line` after running `pandapower.runpp(net)`:
![image](https://user-images.githubusercontent.com/410028/75257804-cc018380-57e5-11ea-8e76-42a083645258.png)

**Comment by lthurner** [comment]
You are right, thanks for spotting this. Can you put in a PR to fix this? You would simply have to add those missing parameters in this .csv file: https://github.com/e2nIEE/pandapower/blob/develop/doc/elements/line_res.csv
