### ISSUE TITLE
Customer user constraints

### ISSUE THREAD

**Issue by fnbillimoria** [e2nIEE/pandapower#678]
Hello - I am new to Pandapower and wish to create custom constraints for power system modelling including inertial constraints which depend on the 'on-status' of the generator?  How would I implement such constraints?  Is there any general ability to create custom constraints in running OPF?  Secondly I also seek to use a module that can cooptimise reserves?  Would paneapower be able to handle this?  Many thanks

**Comment by lthurner** [comment]
Hi, the basic pandapower OPF uses the PYPOWER OPF, which is not very flexible with regards to constraints. pandapower does have an interface to PowerModels, which is more powerful with regards to OPF, so I suggest looking into PowerModels if you have more advanced OPF tasks.
