### ISSUE TITLE
Difference between p_mw in res_bus and net.load

### ISSUE THREAD

**Issue by MabroukAhmed** [e2nIEE/pandapower#686]
I would like to understand the difference between the  p_mw (in net.res_bus) the resulting active power demand [MW] and p_mw (in the net.load) which corresponds to the real power of the load. Do they represent the same thing?

**Comment by lthurner** [comment]
If you have one load at one bus, they represent the same thing. But you can have multiple loads, sgens generators, shunts, xwards etc. at one bus, in which case the bus value is the sum of all connected elements.
