### ISSUE TITLE
Behaviour in case of high static generator production?

### ISSUE THREAD

**Issue by wenglerjoe** [e2nIEE/pandapower#703]
Hello,
I'm currently working on a grid containing many static generators and situations arise, where locally more power is generated by static generators as is consumed by loads for several buses. As I understand it, the loads and static generators get subtracted at the buses, potentially leading to "negative loads" when production of static generators is higher then the loads.
My question is (how) is that case handled in PandaPower? Is this negative load at the bus manually set to 0 or is it transferred into the grid where it can account for loads connected to other buses?

Thank you in advance for any advice on that matter

**Comment by lthurner** [comment]
That seems like a general question about power system analysis. I suggest you look into literature about power flow calculation. 

To answer you question: no, negative load / generation is not set to 0, as that would defeat the purpose of simulating generation units. Statc generation is fed into the grid and flows through the grid. How it flows through the grid depends on the structure of the grid. Look into the concept of slack/swing buses for this. Again, this is not specific to pandapower but how all power system analysis software behaves.
