### ISSUE TITLE
Data Type of Branch data in PyPowerCase after using runpp()

### ISSUE THREAD

**Issue by philbox2** [e2nIEE/pandapower#720]
I noticed that the table defining the branch data in the underlying pypower case format in net["_ppc"] after solving via runpp() (for example for the basic example on the webpage) is complex (https://github.com/e2nIEE/pandapower/blob/8fb6c148d5ad492a1850ea6effbb2afbe8f0f2a6/pandapower/build_branch.py#L41).
Shouldn't all values be real, since they separately define resistance, reactance, capacitance and so on. So dtype should be np.float64, right?

Maybe I am missing something. I have to admit that I don't have a solid electrotechnical background ;)

**Comment by jhmenke** [comment]
Some columns use complex values, e.g. BR_B

https://github.com/e2nIEE/pandapower/blob/701d5033ef8004890c4f02dd086ce6f639bc2d9c/pandapower/build_branch.py#L152
