### ISSUE TITLE
NaN values in res_line_sc

### ISSUE THREAD

**Issue by chefPony** [e2nIEE/pandapower#728]
After release 2.2.2 when running a shortcircuit calculation with:
```sc.calc_sc(net, case='max', branch_results=True)```
the resulting table in `net.res_line_sc`  contains  all the following columns : `p_from_mw | q_from_mvar | p_to_mw | q_to_mvar | pl_mw | ql_mvar | i_from_ka | i_to_ka | i_ka | vm_from_pu | va_from_degree | vm_to_pu | va_to_degree | loading_percent | ikss_ka` .
Only the `ikss_ka` column has values the rest of the table is`NaN`.
Is this expected?

**Comment by lthurner** [comment]
No that is not intended... The reset_result function was refactored before this release, seems like this glitch was introduced with this refactoring. I will look into it
