### ISSUE TITLE
Confusing parameter descriptions in documentation

### ISSUE THREAD

**Issue by akshetty9** [e2nIEE/pandapower#732]
Parameter description is confusing in seveal places in the documentation.  For ex. lines results are described as below. 

i_**from**_ka Current at **to** bus [kA]
i_**to**_ka  Current at **from** bus [kA]
Is this a mistake??

https://pandapower.readthedocs.io/en/v2.2.2/elements/line.html

**Comment by lthurner** [comment]
> Is this a mistake??

Yes it is, obviously it is the other way around... funny that no one every noticed. ;) Do you want to put in a Pull Request?
