### ISSUE TITLE
opf_basic tutorial not converging

### ISSUE THREAD

**Issue by fgfgama** [e2nIEE/pandapower#733]
Hi all,

I'm trying to run the opf_basic.ipynb tutorial
https://github.com/e2nIEE/pandapower/blob/master/tutorials/opf_basic.ipynb

First of all, none of the OPF converges, unless I set init = 'pf'. When I do, I can go all the way until line 18, getting the same results.

However, line 19 (OPF with line constraints) doesn't converge. Not even when setting init = 'pf'.

I'm afraid there might be something wrong with my solver (Three weeks or so ago, I posted about MOSEK, and I changed a couple of lines to make the tests converge, and it worked: https://github.com/e2nIEE/pandapower/issues/694).

I'm not sure where to start posting additional information on what might be wrong (I'm guessing something is wrong, since these are pretty simple networks, and the OPF is still failing to converge).

Thank you very much!

Best,

**Comment by inratkaisija** [comment]
@fgfgama Thanks for reporting this issue. It has nothing to do with the solver you use but is related to the PYPOWER OPF that pandapower runs when you call `runopp()`. When you set the power tolerance to `delta=1e-16` and give it as an input to `runopp()` it works.
