### ISSUE TITLE
pandas 1.0 support

### ISSUE THREAD

**Issue by zainistan** [e2nIEE/pandapower#736]
Hi everyone, I am new here.

Well, I was trying to create a transformer from parameters for 3-phase power flow and I received this error. The line mentioned in the error is: 

and isnan(mag0_rx)and isnan(si0_hv_partial)and isnan(vector_group)):

I looked it up online and I think there is a conflict between the datatype of the vector_group parameter (string) and the isnan function.

I am new to Python so hopefully someone more experienced than me can look into this. Thanks!

**Comment by lthurner** [comment]
Which version of pandas are you using?

**Comment by zainistan** [comment]
> Which version of pandas are you using?

I am using pandas version 1.0.3.

**Comment by lthurner** [comment]
Sorry for the late reply, I lost track of this issue - try downgrading to < 1.0, pandas 1.0 is pretty new and we have not yet updated support for this
