### ISSUE TITLE
Ext Grid Appearance in SimplePlot

### ISSUE THREAD

**Issue by SimonRubenDrauz** [e2nIEE/pandapower#754]
if using simple_plot.py the ext_grid is plotted as yellow square. I would suggest to take a hatched ext_grid instead, as ext_grids are also drawn hatched in PowerFactory and Sincal. 

The changes have been pushed to my fork under following branch:
https://github.com/SimonRubenDrauz/pandapower/tree/hatch

While adapting that, I realized another thing: creating a ext_grid_collection in simple_plot.py calls create_bus_collection, instead of create_ext_grid_collection. Maybe we should adapt this too.

**Comment by FlorianShepherd** [comment]
Would be fine for me and is a good idea I guess. Thanks @SimonRubenDrauz  Would you create a PR?

**Comment by SteffenMeinecke** [comment]
@SimonRubenDrauz how is the status? Is that included in https://github.com/e2nIEE/pandapower/pull/1378 ?

**Comment by rbolgaryn** [comment]
This is the current state:

![grafik](https://user-images.githubusercontent.com/28706693/152501471-ba1ee40d-77e9-47f7-a456-1fde0695376b.png)

So closing the issue
