### ISSUE TITLE
numba and state estimation

### ISSUE THREAD

**Issue by znicoy** [e2nIEE/pandapower#762]
Hi,
do you plan to use numba for the state estimation as well? Or am I overseeing something and it is actually already being used?
Thanks in advance!
Nico

**Comment by wangzhenassd** [comment]
Hi @znicoy ,
currently there is no plan to implement Numba acceleration for state estimation over the vectorized Numpy/Scipy version, since the sparse matrix operation is much more volatile than in powerflow due to the allocation of measurement.

**Comment by znicoy** [comment]
Thanks for your answer! So you think numba will not improve the speed at all in that case? And where do you see the potential to optimize the code?

**Comment by wangzhenassd** [comment]
I think, the potential is mainly on pd2ppc process including the conversion of measurement. The sparse matrix operation performance is mainly limited by the SciPy library.  Is your question rightfully explained?

**Comment by znicoy** [comment]
Yes, thanks!
