### ISSUE TITLE
use of previous results as initial values in state estimation not working correctly?

### ISSUE THREAD

**Issue by znicoy** [e2nIEE/pandapower#763]
Hi,
it seems to me that the initialization of the state estimation with previous results doesn't work correctly. In "pp2eppci", when copying the results with "_copy_power_flow_results", the field "res_bus" will be saved to "res_bus_power_flow" and then be reset. However, in "get_voltage_init_vector" (build_bus.py), you call "res_bus" for the initial values. In my opinion, we should call res_bus_power_flow instead (which works).
Looking forward to your comments.
Nico

**Comment by wangzhenassd** [comment]
Hi @znicoy,
I think you are right, since the latest pandapower release more result tables (3ph) are now available, the initialization with warm start may also be an issue for those calculations.
