### ISSUE TITLE
Accessing  Residual Covariance matrix in State Estimation

### ISSUE THREAD

**Issue by skababji** [e2nIEE/pandapower#768]
Hi,
I can find all needed estimated measurements in  net.res_bus_est and res_line. However, I was wondering if there is a way I can access the Residual Covariance matrix (Omega )? 
Thanks!

**Comment by jhmenke** [comment]
Yes, but not by using the standard estimate function. You can take the relevant code from the estiamte function here: (https://github.com/e2nIEE/pandapower/blob/ec15f866a32801c7690a687712fbc8e7b624463b/pandapower/estimation/state_estimation.py#L80

You need the *se* object in this case to access matrices calculated in the state estimation process.

```
# define parameters like net, tolerance, maximum iterations etc. exactly the same as calling estimate before, then:
se = StateEstimation(net, tolerance, maximum_iterations, algorithm=algorithm)
v_start, delta_start = _initialize_voltage(net, init, calculate_voltage_angles)
results = se.estimate(v_start=v_start, delta_start=delta_start,
                      calculate_voltage_angles=calculate_voltage_angles,
                      zero_injection=zero_injection,
                      fuse_buses_with_bb_switch=fuse_buses_with_bb_switch, **opt_vars)
r_cov = se.r  # also *R_inv*, Gain matrix *Gm*, Hessian *H* are available
```


Let me know if that helps.
