### ISSUE TITLE
Bug in opf_costfcn

### ISSUE THREAD

**Issue by znicoy** [e2nIEE/pandapower#770]
Hi,
this is how the polynomial costs are calculated:
```
    ipol = find(gencost[:, MODEL] == POLYNOMIAL)   ## poly MW and MVAr costs
    xx = r_[ Pg, Qg ] * baseMVA
    if any(ipol):
        f = sum( totcost(gencost[ipol, :], xx[ipol]) )  ## cost of poly P or Q
    else:
        f = 0
```

However, what if "ipol" only points to the first row of gencost? Then the index is 0, and `any(ipol)` will not be satisfied. We should use for example `len(ipol)>0` instead. Or am I missing something?

Nico

**Comment by lthurner** [comment]
You mean if the first one is polynomial, ipol = [0] and then any(ipol) is False? Seems to me you are right about that.... Do you want to put in a Pull Request with the fix?
