### ISSUE TITLE
Plotting Voltage Profile of a Feeder

### ISSUE THREAD

**Issue by na1203132** [e2nIEE/pandapower#785]
Hi,
The function of pp.plotting.plot_voltage_profile(net) seems to be not working with me for some reason. I have tried to call it on a given network such as: 
net = mv_oberrhein()
pp.plotting.plot_voltage_profile(net)

The program runs without any error, but no plot is shown or displayed. 
What could be the issue? 

Thanks in advance.

**Comment by lthurner** [comment]
Try:

>import matplotlib.pyplot as plt
>plt.show()

after the plotting call?

**Comment by na1203132** [comment]
Thank you very much! That solved the issue. 

> Try:
> 
> import matplotlib.pyplot as plt
> plt.show()
> 
> after the plotting call?
