### ISSUE TITLE
changing attribute initial_powerflow in controller

### ISSUE THREAD

**Issue by SimonRubenDrauz** [e2nIEE/pandapower#790]
As pandapipes is based on pandapower I would like to rename the control attribute 'initial_powerflow ' to 'intial_run', in order to prevent deletion of this attribute for each pandapipes controller and change it to initial_pipeflow. Would this be possible?

A solution has been pushed on branch 'initial_powerflow' found in my fork!

**Comment by FlorianShepherd** [comment]
I don't mind changing the name as long as the description is fine. I think it's important to know what it does (run an additional "time consuming" power flow  / pipeflow before each time step). Would you create a PR  @SimonRubenDrauz ?

**Comment by SimonRubenDrauz** [comment]
done. Changes have been implemented!
