### ISSUE TITLE
Estimation results

### ISSUE THREAD

**Issue by bbadetcauk** [e2nIEE/pandapower#803]
Hello,

I think in python file pandapower -> estimation -> results.py there is a baseMVA missing in the calculation.

I think line 22 should be adjusted to this, or similar:

`Sbus = np.multiply(V, np.conj(Ybus * V)) * baseMVA`

Thanks

**Comment by wangzhenassd** [comment]
Hi @bbadetcauk, I think you are right. Thanks a lot for reporting it!
