### ISSUE TITLE
Question: What tools are used for generating the circuit diagrams in the documentation?

### ISSUE THREAD

**Issue by bergkvist** [e2nIEE/pandapower#804]
Example: 
![image](https://user-images.githubusercontent.com/410028/83954708-c6d3bc00-a84b-11ea-81cb-9903c39bda8d.png)

**Comment by lthurner** [comment]
These diagrams are done with ProfiCad: https://www.proficad.com/. The .sxe source files can be found in the doc folder.

**Comment by ve9jonny** [comment]
> These diagrams are done with ProfiCad: https://www.proficad.com/. The .sxe source files can be found in the doc folder.

Did you mean https://github.com/e2nIEE/pandapower/tree/develop/doc as the doc folder. When I looked inside there I could not see .sxe files. Please could you help?
