### ISSUE TITLE
simple_plotly do not return any plot

### ISSUE THREAD

**Issue by bmitrauncc** [e2nIEE/pandapower#810]
The function simple_plotly when called do not return any plot, plotly was installed correctly.
It produces two spacing's on the command line.

**Comment by FlorianShepherd** [comment]
you need matplotlib not plotly for simple_plot()

**Comment by FlorianShepherd** [comment]
Please provide an example.

**Comment by bergkvist** [comment]
Are you using JupyterLab? If so you might need to manually install plotly extensions for jupyterlab. 

See: https://plotly.com/python/getting-started/#jupyterlab-support-python-35

Essentially, try running this:
```sh
jupyter labextension install jupyterlab-plotly@4.8.1
```

**Comment by bmitrauncc** [comment]
I was able to fix the issue with some reinstallations
