### ISSUE TITLE
PowerModels: [Win127 Error] if used in combination with conda

### ISSUE THREAD

**Issue by lschmelting** [e2nIEE/pandapower#820]
**Goal if this issue:**
1. Test a combination of  ![statical linking](https://pyjulia.readthedocs.io/en/latest/troubleshooting.html#your-python-interpreter-is-statically-linked-to-libpython) and debugging the error described below to be able to use conda with PowerModels again.
2. Update the documentation for installation + usage of PowerModels.

**Description:**
In October 2019, i was able to use conda + PowerModels in pandapower with Spyder. Yesterday @SteffenMeinecke noticed he cannot use it as intended:
```
from julia.api import Julia
jl= Julia(compiled_modules=False)
```
works in an anaconda prompt, but fails if executed in spyder ([WinError 127]).  If PowerModels is called via pandapower in an anaconda prompt, the same error occurs (Both with the current code in pandapower/pandapower/opf/run_powermodels.py or by replacing it with the lines above to circumvent the statical linking problem.
Also note that conda is not officially supported by both ![PyCall.jl](https://github.com/JuliaPy/PyCall.jl#python-virtual-environments) and ![PyJulia](https://pyjulia.readthedocs.io/en/latest/usage.html?highlight=conda#virtual-environments), so we are on our own if issues appear at any time.

**Comment by lschmelting** [comment]
Any ideas for improvement for this pull request? #821

**Comment by lschmelting** [comment]
I was able to call PowerModels with the modified Code. It's kind of strange that i had to move `from julia import Main` outside of the try-block to make this work. I also modified the Code so users can use their own sysimage_file (compiled_modules=False is VERY slow)

**Comment by rbolgaryn** [comment]
Hi @lschmelting ,

can the issue be closed?

**Comment by lschmelting** [comment]
The issue can be closed, the PR must be updated before merging.
