### ISSUE TITLE
Load profile at real-time

### ISSUE THREAD

**Issue by kosmylo** [e2nIEE/pandapower#840]
I have studied the example for time series calculations, where the profiles for PV, wind, and residential are known beforehand. My question is if it is possible to change for example the PV or the residential load at real-time based on a probability distribution. For example, inside the for loop to change the load for each step instead of assigning the values before the start of the for loop.

**Comment by FlorianShepherd** [comment]
Not with the default `ConstController` you'd have to implement your own controller, which changes values according to your needs within a time step.
