### ISSUE TITLE
sensitivity analysis

### ISSUE THREAD

**Issue by Homam94** [e2nIEE/pandapower#847]
Hello,
How I can do sensitivity analysis of a distrubition network for example with the help of Ptdf in Pandapower?
Is there any functions that I can use in this case?

**Comment by wangzhenassd** [comment]
Hi @Homam94, 
The ptdf/lodf requires the ppci data structure, which can be aquired by pd2ppc function
you can check out this #784 for the usage of the internal data structure.

**Comment by marinaffc** [comment]
Hi @wangzhenassd , 

thank you for your comment. I have seen that #784 issue, however, same as @Homam94 I am not sure how to use the internal data structure to calculate PTDF. Do you have any available reference?

Thank you very much!

**Comment by rbolgaryn** [comment]
There is a PTDF function in pandapower/pypower. You can give it a try and see if it is helpful for your use-case
Roman
