### ISSUE TITLE
add LV grid for town in MV Oberrhein region

### ISSUE THREAD

**Issue by jkisse** [e2nIEE/pandapower#867]
The low voltage grid from this paper https://www.mdpi.com/1996-1073/13/16/4052 should be added to the networks-module.

**Comment by rbolgaryn** [comment]
Hi @jkisse ,

what is the current status of the issue?

**Comment by jkisse** [comment]
I can do this next week.

**Comment by jkisse** [comment]
I had to do some modifications regarding the substations (add more) so the trafos do not align 100 % with the MV Oberrhein network. 
If anyone is interested in the network file, please let me know.

**Comment by SteffenMeinecke** [comment]
> If anyone is interested in the network file, please let me know.

@jkisse So the LV grid from the paper will be not included to pandapower and we can close this issue? Would be sad for the paper and the community if we don't provide it.

**Comment by pawellytaev** [comment]
This is about the Schutterwald grid right? Thus, I'm closing this issue since it's already in pandapower
