### ISSUE TITLE
Visuization of power grid 

### ISSUE THREAD

**Issue by hitchenzhe** [e2nIEE/pandapower#882]
Dear guys,

This is not a technical question. I want to know, how to visualize the power network if we created a simple network with pandapower? 

In most of cases, you create a network model, run algorithms(powerflow), it's imporatnt to verify your model is correct including topology, elements. How to make this visualized.

**Comment by Stu-emhTrade** [comment]
There are a few ways to do this. The docs explain them and there are numerous, detailed, tutorials in: https://github.com/e2nIEE/pandapower/tree/627582fec0d1f957b2df4a9ee70adedfbf3c6e59/tutorials

[This one](https://github.com/e2nIEE/pandapower/blob/627582fec0d1f957b2df4a9ee70adedfbf3c6e59/tutorials/plotting_basic.ipynb) might be the best place to start.
