### ISSUE TITLE
Can read imax from excel

### ISSUE THREAD

**Issue by maru159** [e2nIEE/pandapower#887]
I used code and excel from youtube to try reading data  but i see max_i_ka can't get data. Anyone know how to fix it 
![image](https://user-images.githubusercontent.com/69780538/90730228-f85c0f80-e2f1-11ea-8b21-b4de0da625c8.png)
![image](https://user-images.githubusercontent.com/69780538/90730276-0873ef00-e2f2-11ea-8cf3-5833d822fdf0.png)

**Comment by lthurner** [comment]
I don't understand the problem, can you please post a reproducable minimal example?

**Comment by lthurner** [comment]
Please reopen if you provide a better description or way to reproduce.
