### ISSUE TITLE
issue on ploting and version

### ISSUE THREAD

**Issue by hitchenzhe** [e2nIEE/pandapower#894]
Dear all

When I run:
`import pandapower as pp`

`print(pp.version)`

It shows <module 'packaging.version' from '/home/zhe/.local/lib/python3.6/site-packages/packaging/version.py'>
And the ploting of network doesn't return any figure.

I use pandapower 2.3.1. Other calculation functions work well.

Best

**Comment by lthurner** [comment]
Try

> import matplotlib.pyplot as plt
> plt.show()

after plotting?

**Comment by hitchenzhe** [comment]
> Try
> 
> > import matplotlib.pyplot as plt
> > plt.show()
> 
> after plotting?

Dear staff,
plt works. But another problem I meet is the plotly doesn.t work:
`simple_plotly(net)`
`pf_res_plotly(net, figsize=2, filename=dnet+'_b1.html')`

It shows following while return nothing
No or insufficient geodata available --> Creating artificial coordinates. This may take some time...

Best

**Comment by lthurner** [comment]
Maybe you don't have all the relevant packages installed. You will need plotly as well as the pacakges necessary to create artificial coordinates: https://pandapower.readthedocs.io/en/v2.3.1/plotting/matplotlib/generic.html

**Comment by hitchenzhe** [comment]
> Maybe you don't have all the relevant packages installed. You will need plotly as well as the pacakges necessary to create artificial coordinates: https://pandapower.readthedocs.io/en/v2.3.1/plotting/matplotlib/generic.html

Yes, I have installed python-igraph but no pycairo(maybe not necessary).

When I run pp.plotting.simple_plotly(net) individually, it returned:


`!pp.plotting.simple_plotly(net)


Figure({
    'data': [{'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [0.0, 0.5, 1.0],
              'y': [0.0, 0.0, 0.0]},
             {'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [1.0, 1.5, 2.0],
              'y': [0.0, -0.375, -0.75]},
             {'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [2.0, 2.5, 3.0],
              'y': [-0.75, -1.0, -1.25]},
             {'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [3.0, 3.5, 4.0],
              'y': [-1.25, -1.25, -1.25]},
             {'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [4.0, 4.5, 5.0],
              'y': [-1.25, -1.25, -1.25]},
             {'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [5.0, 5.5, 6.0],
              'y': [-1.25, -1.5, -1.75]},
             {'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [6.0, 6.5, 7.0],
              'y': [-1.75, -1.75, -1.75]},
             {'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [7.0, 7.5, 8.0],
              'y': [-1.75, -1.75, -1.75]},
             {'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [8.0, 8.5, 9.0],
              'y': [-1.75, -1.75, -1.75]},
             {'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [9.0, 9.5, 10.0],
              'y': [-1.75, -1.75, -1.75]},
             {'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [10.0, 10.5, 11.0],
              'y': [-1.75, -1.75, -1.75]},
             {'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [11.0, 11.5, 12.0],
              'y': [-1.75, -1.75, -1.75]},
             {'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [12.0, 12.5, 13.0],
              'y': [-1.75, -1.75, -1.75]},
             {'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [13.0, 13.5, 14.0],
              'y': [-1.75, -1.75, -1.75]},
             {'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [14.0, 14.5, 15.0],
              'y': [-1.75, -1.75, -1.75]},
             {'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [15.0, 15.5, 16.0],
              'y': [-1.75, -1.75, -1.75]},
             {'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [16.0, 16.5, 17.0],
              'y': [-1.75, -1.75, -1.75]},
             {'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [1.0, 1.5, 2.0],
              'y': [0.0, 0.375, 0.75]},
             {'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [2.0, 2.5, 3.0],
              'y': [0.75, 0.75, 0.75]},
             {'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [3.0, 3.5, 4.0],
              'y': [0.75, 0.75, 0.75]},
             {'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [4.0, 4.5, 5.0],
              'y': [0.75, 0.75, 0.75]},
             {'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [2.0, 2.5, 3.0],
              'y': [-0.75, -0.5, -0.25]},
             {'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [3.0, 3.5, 4.0],
              'y': [-0.25, -0.25, -0.25]},
             {'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [4.0, 4.5, 5.0],
              'y': [-0.25, -0.25, -0.25]},
             {'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [5.0, 5.5, 6.0],
              'y': [-1.25, -1.0, -0.75]},
             {'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [6.0, 6.5, 7.0],
              'y': [-0.75, -0.75, -0.75]},
             {'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [7.0, 7.5, 8.0],
              'y': [-0.75, -0.75, -0.75]},
             {'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [8.0, 8.5, 9.0],
              'y': [-0.75, -0.75, -0.75]},
             {'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [9.0, 9.5, 10.0],
              'y': [-0.75, -0.75, -0.75]},
             {'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [10.0, 10.5, 11.0],
              'y': [-0.75, -0.75, -0.75]},
             {'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [11.0, 11.5, 12.0],
              'y': [-0.75, -0.75, -0.75]},
             {'hoverinfo': 'text',
              'line': {'color': 'rgb(128, 128, 128)', 'width': 1},
              'mode': 'lines',
              'name': 'lines',
              'type': 'scatter',
              'x': [12.0, 12.5, 13.0],
              'y': [-0.75, -0.75, -0.75]},
             {'hoverinfo': 'text',
              'marker': {'color': 'rgb(128, 128, 128)', 'size': 1, 'symbol': 'circle'},
              'mode': 'markers',
              'name': 'edge_center',
              'text': array(['Index: 0<br />Name: None<br />Length: 1.0 km<br />R: 0.092 Ohm<br />X: 0.047 Ohm<br />',
                             'Index: 1<br />Name: None<br />Length: 1.0 km<br />R: 0.493 Ohm<br />X: 0.251 Ohm<br />',
                             'Index: 2<br />Name: None<br />Length: 1.0 km<br />R: 0.366 Ohm<br />X: 0.186 Ohm<br />',
                             'Index: 3<br />Name: None<br />Length: 1.0 km<br />R: 0.381 Ohm<br />X: 0.194 Ohm<br />',
                             'Index: 4<br />Name: None<br />Length: 1.0 km<br />R: 0.819 Ohm<br />X: 0.707 Ohm<br />',
                             'Index: 5<br />Name: None<br />Length: 1.0 km<br />R: 0.187 Ohm<br />X: 0.619 Ohm<br />',
                             'Index: 6<br />Name: None<br />Length: 1.0 km<br />R: 0.711 Ohm<br />X: 0.235 Ohm<br />',
                             'Index: 7<br />Name: None<br />Length: 1.0 km<br />R: 1.03 Ohm<br />X: 0.74 Ohm<br />',
                             'Index: 8<br />Name: None<br />Length: 1.0 km<br />R: 1.044 Ohm<br />X: 0.74 Ohm<br />',
                             'Index: 9<br />Name: None<br />Length: 1.0 km<br />R: 0.197 Ohm<br />X: 0.065 Ohm<br />',
                             'Index: 10<br />Name: None<br />Length: 1.0 km<br />R: 0.374 Ohm<br />X: 0.124 Ohm<br />',
                             'Index: 11<br />Name: None<br />Length: 1.0 km<br />R: 1.468 Ohm<br />X: 1.155 Ohm<br />',
                             'Index: 12<br />Name: None<br />Length: 1.0 km<br />R: 0.542 Ohm<br />X: 0.713 Ohm<br />',
                             'Index: 13<br />Name: None<br />Length: 1.0 km<br />R: 0.591 Ohm<br />X: 0.526 Ohm<br />',
                             'Index: 14<br />Name: None<br />Length: 1.0 km<br />R: 0.746 Ohm<br />X: 0.545 Ohm<br />',
                             'Index: 15<br />Name: None<br />Length: 1.0 km<br />R: 1.289 Ohm<br />X: 1.721 Ohm<br />',
                             'Index: 16<br />Name: None<br />Length: 1.0 km<br />R: 0.732 Ohm<br />X: 0.574 Ohm<br />',
                             'Index: 17<br />Name: None<br />Length: 1.0 km<br />R: 0.164 Ohm<br />X: 0.156 Ohm<br />',
                             'Index: 18<br />Name: None<br />Length: 1.0 km<br />R: 1.504 Ohm<br />X: 1.355 Ohm<br />',
                             'Index: 19<br />Name: None<br />Length: 1.0 km<br />R: 0.41 Ohm<br />X: 0.478 Ohm<br />',
                             'Index: 20<br />Name: None<br />Length: 1.0 km<br />R: 0.709 Ohm<br />X: 0.937 Ohm<br />',
                             'Index: 21<br />Name: None<br />Length: 1.0 km<br />R: 0.451 Ohm<br />X: 0.308 Ohm<br />',
                             'Index: 22<br />Name: None<br />Length: 1.0 km<br />R: 0.898 Ohm<br />X: 0.709 Ohm<br />',
                             'Index: 23<br />Name: None<br />Length: 1.0 km<br />R: 0.896 Ohm<br />X: 0.701 Ohm<br />',
                             'Index: 24<br />Name: None<br />Length: 1.0 km<br />R: 0.203 Ohm<br />X: 0.103 Ohm<br />',
                             'Index: 25<br />Name: None<br />Length: 1.0 km<br />R: 0.284 Ohm<br />X: 0.145 Ohm<br />',
                             'Index: 26<br />Name: None<br />Length: 1.0 km<br />R: 1.059 Ohm<br />X: 0.934 Ohm<br />',
                             'Index: 27<br />Name: None<br />Length: 1.0 km<br />R: 0.804 Ohm<br />X: 0.701 Ohm<br />',
                             'Index: 28<br />Name: None<br />Length: 1.0 km<br />R: 0.507 Ohm<br />X: 0.258 Ohm<br />',
                             'Index: 29<br />Name: None<br />Length: 1.0 km<br />R: 0.974 Ohm<br />X: 0.963 Ohm<br />',
                             'Index: 30<br />Name: None<br />Length: 1.0 km<br />R: 0.31 Ohm<br />X: 0.362 Ohm<br />',
                             'Index: 31<br />Name: None<br />Length: 1.0 km<br />R: 0.341 Ohm<br />X: 0.53 Ohm<br />'],
                            dtype=object),
              'type': 'scatter',
              'x': [0.5],
              'y': [0.0]},
             {'hoverinfo': 'text',
              'marker': {'color': 'rgb(255, 255, 0)', 'size': 20.0, 'symbol': 'square'},
              'mode': 'markers',
              'name': 'external_grid',
              'text': array(['Index: 0<br />Name: None<br />V_m: 1.0 p.u.<br />V_a: 0.0 °<br />'],
                            dtype=object),
              'type': 'scatter',
              'x': [0.0],
              'y': [0.0]},
             {'hoverinfo': 'text',
              'marker': {'color': 'rgb(0, 0, 255)', 'size': 10, 'symbol': 'circle'},
              'mode': 'markers',
              'name': 'buses',
              'text': array(['Index: 0<br />Name: 1<br />V_n: 12.66 kV<br />',
                             'Index: 1<br />Name: 2<br />V_n: 12.66 kV<br />Load: 0.100 MW<br />',
                             'Index: 2<br />Name: 3<br />V_n: 12.66 kV<br />Load: 0.090 MW<br />',
                             'Index: 3<br />Name: 4<br />V_n: 12.66 kV<br />Load: 0.120 MW<br />',
                             'Index: 4<br />Name: 5<br />V_n: 12.66 kV<br />Load: 0.060 MW<br />',
                             'Index: 5<br />Name: 6<br />V_n: 12.66 kV<br />Load: 0.060 MW<br />',
                             'Index: 6<br />Name: 7<br />V_n: 12.66 kV<br />Load: 0.200 MW<br />',
                             'Index: 7<br />Name: 8<br />V_n: 12.66 kV<br />Load: 0.200 MW<br />',
                             'Index: 8<br />Name: 9<br />V_n: 12.66 kV<br />Load: 0.060 MW<br />',
                             'Index: 9<br />Name: 10<br />V_n: 12.66 kV<br />Load: 0.060 MW<br />',
                             'Index: 10<br />Name: 11<br />V_n: 12.66 kV<br />Load: 0.045 MW<br />',
                             'Index: 11<br />Name: 12<br />V_n: 12.66 kV<br />Load: 0.060 MW<br />',
                             'Index: 12<br />Name: 13<br />V_n: 12.66 kV<br />Load: 0.060 MW<br />',
                             'Index: 13<br />Name: 14<br />V_n: 12.66 kV<br />Load: 0.120 MW<br />',
                             'Index: 14<br />Name: 15<br />V_n: 12.66 kV<br />Load: 0.060 MW<br />',
                             'Index: 15<br />Name: 16<br />V_n: 12.66 kV<br />Load: 0.060 MW<br />',
                             'Index: 16<br />Name: 17<br />V_n: 12.66 kV<br />Load: 0.060 MW<br />',
                             'Index: 17<br />Name: 18<br />V_n: 12.66 kV<br />Load: 0.090 MW<br />',
                             'Index: 18<br />Name: 19<br />V_n: 12.66 kV<br />Load: 0.090 MW<br />',
                             'Index: 19<br />Name: 20<br />V_n: 12.66 kV<br />Load: 0.090 MW<br />',
                             'Index: 20<br />Name: 21<br />V_n: 12.66 kV<br />Load: 0.090 MW<br />',
                             'Index: 21<br />Name: 22<br />V_n: 12.66 kV<br />Load: 0.090 MW<br />',
                             'Index: 22<br />Name: 23<br />V_n: 12.66 kV<br />Load: 0.090 MW<br />',
                             'Index: 23<br />Name: 24<br />V_n: 12.66 kV<br />Load: 0.420 MW<br />',
                             'Index: 24<br />Name: 25<br />V_n: 12.66 kV<br />Load: 0.420 MW<br />',
                             'Index: 25<br />Name: 26<br />V_n: 12.66 kV<br />Load: 0.060 MW<br />',
                             'Index: 26<br />Name: 27<br />V_n: 12.66 kV<br />Load: 0.060 MW<br />',
                             'Index: 27<br />Name: 28<br />V_n: 12.66 kV<br />Load: 0.060 MW<br />',
                             'Index: 28<br />Name: 29<br />V_n: 12.66 kV<br />Load: 0.120 MW<br />',
                             'Index: 29<br />Name: 30<br />V_n: 12.66 kV<br />Load: 0.200 MW<br />',
                             'Index: 30<br />Name: 31<br />V_n: 12.66 kV<br />Load: 0.150 MW<br />',
                             'Index: 31<br />Name: 32<br />V_n: 12.66 kV<br />Load: 0.210 MW<br />',
                             'Index: 32<br />Name: 33<br />V_n: 12.66 kV<br />Load: 0.060 MW<br />'],
                            dtype=object),
              'type': 'scatter',
              'x': [0.0, 1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0,
                    12.0, 13.0, 14.0, 15.0, 16.0, 17.0, 2.0, 3.0, 4.0, 5.0, 3.0,
                    4.0, 5.0, 6.0, 7.0, 8.0, 9.0, 10.0, 11.0, 12.0, 13.0],
              'y': [0.0, 0.0, -0.75, -1.25, -1.25, -1.25, -1.75, -1.75, -1.75,
                    -1.75, -1.75, -1.75, -1.75, -1.75, -1.75, -1.75, -1.75, -1.75,
                    0.75, 0.75, 0.75, 0.75, -0.25, -0.25, -0.25, -0.75, -0.75,
                    -0.75, -0.75, -0.75, -0.75, -0.75, -0.75]}],
    'layout': {'autosize': True,
               'height': 102.94117647058823,
               'hovermode': 'closest',
               'margin': {'b': 5, 'l': 5, 'r': 5, 't': 5},
               'showlegend': True,
               'template': '...',
               'title': {'font': {'size': 16}},
               'width': 700.0,
               'xaxis': {'showgrid': False, 'showticklabels': False, 'zeroline': False},
               'yaxis': {'showgrid': False, 'showticklabels': False, 'zeroline': False}}
})`

**Comment by rbolgaryn** [comment]
Hi @hitchenzhe ,

can you proviede a small example?

**Comment by hitchenzhe** [comment]
> Hi @hitchenzhe ,
> 
> can you proviede a small example?

I just can not use plotly, I don know why, but matplot works

**Comment by rbolgaryn** [comment]
Does this code work for you?

```python
import pandapower.networks as nw
from pandapower.plotting.plotly.simple_plotly import simple_plotly
from plotly.offline import plot
net = nw.mv_oberrhein()
fig = simple_plotly(net)
plot(fig)
```

**Comment by seilsepour** [comment]
Hi there
I have problem with simple_plotly too.
I can not run the above code. It resurns the following error:

```
WARNING:pandapower.auxiliary:numba cannot be imported and numba functions are disabled.
Probably the execution is slow.
Please install numba to gain a massive speedup.
(or if you prefer slow execution, set the flag numba=False to avoid this warning!)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-66-e049a360e961>](https://localhost:8080/#) in <cell line: 5>()
      3 from plotly.offline import plot
      4 net = nw.mv_oberrhein()
----> 5 fig = simple_plotly(net)
      6 plot(fig)

6 frames
[/usr/local/lib/python3.10/dist-packages/pandas/core/generic.py](https://localhost:8080/#) in blk_func(values)
   1556                 # [ExtensionArray, ndarray[Any, Any]]"; expected
   1557                 # "_SupportsPos[ndarray[Any, dtype[Any]]]"
-> 1558                 return operator.pos(values)  # type: ignore[arg-type]
   1559 
   1560         new_data = self._mgr.apply(blk_func)

TypeError: bad operand type for unary +: 'str'

```

**Comment by seilsepour** [comment]
Hi @rbolgaryn,
can you help me? this is my code:
```
from pandapower.plotting.plotly import simple_plotly
simple_plotly(net) 
```
I got this error:
```
from pandapower.plotting.plotly import simple_plotly
net.sgen.scaling = 1
marker_trace = pplotly.create_weighted_marker_trace(net, "sgen", column_to_plot="p_mw", marker_scaling=200, color="green", patch_type="circle-open")
#simple_plotly(net, bus_size=0.25, additional_traces=[marker_trace])
simple_plotly(net)
```
