### ISSUE TITLE
Dead wiki link: Short-Circuit currents

### ISSUE THREAD

**Issue by bergkvist** [e2nIEE/pandapower#896]
https://pandapower.readthedocs.io/en/v2.3.1/shortcircuit/currents.html

![image](https://user-images.githubusercontent.com/410028/91310903-b976ff80-e7b2-11ea-8dc8-e71a729424d6.png)

---

http://www.openelectrical.org/wiki/index.php?title=According_to_the_IEC_60909

![image](https://user-images.githubusercontent.com/410028/91310818-a19f7b80-e7b2-11ea-98c0-290370683e0c.png)

**Comment by rbolgaryn** [comment]
The website of openelectrical is being re-developed, that must be the reason why it is not accessible at the moment.
