### ISSUE TITLE
On reading

### ISSUE THREAD

**Issue by hitchenzhe** [e2nIEE/pandapower#898]
anyone knows how to show the specific data from net structure?
For example

`net.load
Out[15]: 
                  name  bus   p_mw  ...  max_p_mw   subnet  min_q_mvar
0      LV6.305 Load 16    2  0.011  ...       NaN  LV6.305         NaN
1      LV6.305 Load 24   11  0.003  ...       NaN  LV6.305         NaN
2      LV6.305 Load 36    5  0.003  ...       NaN  LV6.305         NaN
3       LV6.305 Load 7   17  0.005  ...       NaN  LV6.305         NaN
4      LV6.305 Load 33    3  0.008  ...       NaN  LV6.305         NaN
..                 ...  ...    ...  ...       ...      ...         ...
244  MV3.101 MV Load 1  258  0.470  ...       NaN  MV3.101         NaN
245  MV3.101 MV Load 2  241  0.270  ...       NaN  MV3.101         NaN
246  MV3.101 MV Load 3  189  0.390  ...       NaN  MV3.101         NaN
247  MV3.101 MV Load 4  185  0.190  ...       NaN  MV3.101         NaN
248  MV3.101 MV Load 5  216  0.210  ...       NaN  MV3.101         NaN

[249 rows x 17 columns]`

I want to know the value in a specific line or column, how to do?It doesn show in variable explorer in spyder

Best

**Comment by lthurner** [comment]
The data structure is a pandas DataFrame, you can check the pandas documentation on how to access data in DataFrames: https://pandas.pydata.org/pandas-docs/stable/user_guide/10min.html
