### ISSUE TITLE
OPF with timeseries module returns wrong convergence message

### ISSUE THREAD

**Issue by christoph-weyhing** [e2nIEE/pandapower#911]
To me there seems to be an issue in the timeseries module, when OPFs shall be solved.

If I try to solve an OPF with the run_timeseries function pandapower returns "LoadflowNotConverged at time step 0". When I run the same OPF with the function runopp the OPF does convergence. The weird thing is, that the results of the not converged OPF with run_timeseries are exactly the same as they are for the OPF with the runopp function. So it seems to me, that pandapower finds the right solution with both methods, but for run_timeseries it displays a wrong convergence message.

Below you find some code to reproduce the bug. 

`import pandapower as pp
import numpy as np

net = pp.create_empty_network()

#create buses
bus1 = pp.create_bus(net, vn_kv=220.)
bus2 = pp.create_bus(net, vn_kv=110.)
bus3 = pp.create_bus(net, vn_kv=110.)
bus4 = pp.create_bus(net, vn_kv=110.)

#create 220/110 kV transformer
pp.create_transformer(net, bus1, bus2, std_type="100 MVA 220/110 kV")

#create 110 kV lines
pp.create_line(net, bus2, bus3, length_km=70., std_type='149-AL1/24-ST1A 110.0')
pp.create_line(net, bus3, bus4, length_km=50., std_type='149-AL1/24-ST1A 110.0')
pp.create_line(net, bus4, bus2, length_km=40., std_type='149-AL1/24-ST1A 110.0')

#create loads
pp.create_load(net, bus2, p_mw=60, controllable=False)
pp.create_load(net, bus3, p_mw=70, controllable=False)
pp.create_load(net, bus4, p_mw=10, controllable=False)

#create generators
eg = pp.create_ext_grid(net, bus1, min_p_mw=-1000, max_p_mw=1000)
g0 = pp.create_gen(net, bus3, p_mw=80, min_p_mw=0, max_p_mw=80,  vm_pu=1.01, controllable=True)
g1 = pp.create_gen(net, bus4, p_mw=100, min_p_mw=0, max_p_mw=100, vm_pu=1.01, controllable=True)

#create cost functions
costeg = pp.create_poly_cost(net, 0, 'ext_grid', cp1_eur_per_mw=10)
costgen1 = pp.create_poly_cost(net, 0, 'gen', cp1_eur_per_mw=10)
costgen2 = pp.create_poly_cost(net, 1, 'gen', cp1_eur_per_mw=10)

#Run OPF with timeseries module
from pandapower.timeseries.run_time_series import run_timeseries
time_steps = range(1)
run_timeseries(net, time_steps, continue_on_divergence=True, verbose=True, recycle=False,
               run=pp.runopp, delta=1e-16)

#Print timeseries results
print("Bus results timeseries: \n",net.res_bus,"\n")
print("Gen results timeseries: \n",net.res_gen,"\n")

#Run OPF with runopp
pp.runopp(net, verbose=True, delta=1e-16)

#Print runopp results
print("Bus results runopp: \n",net.res_bus,"\n")
print("Gen results runopp: \n",net.res_gen,"\n")`

**Comment by friederikemeier** [comment]
Thanks for reporting this! It is indeed a bug! 
The run_control function checks for the variable net["converged"], but if you are using an OPF, it should check for net["OPF_converged"]. I'll make a fix!
