### ISSUE TITLE
Removing net reference from JSONSerialiazable / Controller Class

### ISSUE THREAD

**Issue by lthurner** [e2nIEE/pandapower#916]
The fact that the controller objects have a reference to the net, and are themselves stored in the net leads to a circular reference. We have made many complicated approaches to work around this circular reference, especially in deepcopies and JSON serialization. 

I propose to remove this circular reference by removing the reference to net in the controller class (and other JSONSerializable objects).

A first refactored version of this can be found on the clean_control branch. The basic control functionality still works fine. Some tests in timeseries and auxiliary are still failing: https://travis-ci.org/github/e2nIEE/pandapower/branches

**Comment by rbolgaryn** [comment]
This seems done. Can the issue be closed, @lthurner ?

**Comment by lthurner** [comment]
Yes can be closed
