### ISSUE TITLE
How to prevent generator from exceeding limit?

### ISSUE THREAD

**Issue by zachoooo** [e2nIEE/pandapower#927]
Lets say you have a super simple network with one bus to which you connect a 20MW load and another bus with a 1MW generator. This is obviously a huge gap and the generator couldn't possibly provide that much power, but when I run this power flow, the generator says that it is producing the power it needs. What am I doing wrong? Shouldn't the generator fail or automatically shutoff? Shouldn't the wire also melt from being way over it's rated load? How can I model situations like this accurately?

```
import pandapower as pp
net = pp.create_empty_network()
b1 = pp.create_bus(net, vn_kv=20.)
b2 = pp.create_bus(net, vn_kv=20.)
pp.create_line(net, from_bus=b1, to_bus=b2, length_km=2.5, std_type="NAYY 4x50 SE")
pp.create_gen(net, bus=b1, p_mw=1,  slack=True, controllable=True)
pp.create_load(net, bus=b2, p_mw=20)
pp.runpp(net)

net.res_bus
      vm_pu  va_degree      p_mw    q_mvar
0  1.000000   0.000000 -21.92989 -0.189083
1  0.911951  -0.658767  20.00000  0.000000

net.res_line
   p_from_mw  q_from_mvar  p_to_mw     q_to_mvar    pl_mw   ql_mvar  i_from_ka   i_to_ka      i_ka  vm_from_pu  va_from_degree  vm_to_pu  va_to_degree  loading_percent
0   21.92989     0.189083    -20.0  2.997602e-15  1.92989  0.189083   0.633085  0.633093  0.633093         1.0             0.0  0.911951     -0.658767       445.840313

net.res_load

   p_mw  q_mvar
0  20.0     0.0

net.res_gen

       p_mw    q_mvar  va_degree  vm_pu
0  21.92989  0.189083        0.0    1.0
```

**Comment by lthurner** [comment]
What you want is an OPF instead of a power flow, please look into the OPF tutorials to get an idea about how to use it.
