### ISSUE TITLE
`simple_plotly` doesn't show my 3w transformer

### ISSUE THREAD

**Issue by miek770** [e2nIEE/pandapower#932]
I have a network with a 3-winding transformer (created with `create_transformer3w_from_parameters`). The power flow and 3-phase short circuit work fine, but the 3-w transformer doesn't appear on the plot generated by `simple_plotly`. The 2-w transformers do appear as bold green lines.

Using pandapower version 2.4.0 on Python 3.8.3 and Jupyter Lab 2.1.5. I unfortunately can't share the network (confidential project), but it should be easy to reproduce using one of pandapower's examples.

**Comment by rbolgaryn** [comment]
Hi @miek770 ,

at the moment, it is not implemented. The function to create trafo3w_trace is missing in simple_plotly.py. 
Would you be interested to implement this feature?
The approach would be similar to the function create_trafo_trace in plotting.plotly.traces.py, also you can take a look at the implementation of matplotlib trafo3w collections: plotting.colections.py -> create_trafo3w_collection.
