### ISSUE TITLE
List available of all py-Documents that tell the code for the different devices?

### ISSUE THREAD

**Issue by Marahop** [e2nIEE/pandapower#964]
Hi all!
I am a total beginner, therefore this question...
I am looking for the documents that show me the code for the calculation of lines, buses, tranformers,...
I would like to see how they have been prorgrammed and enter some transformer specification. The end goal is to see how the power loss has changed with different types of transformers.
I do not know how to start...
Could someone help me out here? Thank you very much. Very appreciated!!
Marahop

**Comment by rbolgaryn** [comment]
Hi @Marahop ,

you can start by going through tutorials: pandapower/tutorials

Roman
