### ISSUE TITLE
Can we set q_mvar for generators like p_mv before OPF?

### ISSUE THREAD

**Issue by TravisCao** [e2nIEE/pandapower#975]

**Comment by rbolgaryn** [comment]
Do you mean static generators or synchronous generators?

**Comment by rbolgaryn** [comment]
Do you mean static generators or synchronous generators?

**Comment by rbolgaryn** [comment]
Too unspecific for an answer at the moment, can be reopened if we get more details.

**Comment by TravisCao** [comment]
I mean for the OPF,  I want to compute the value of the Lagrangian function (generator dispatch cost plus the violation of constraints) of OPF given P and Q of the generators (we set it, not from the result of the runopp(net)). However, in the documentation, it seems that there are no way that we can set the Q for generators before the runopp() function being invoked.  Can we set the Q (q_mvar) for generators?
