### ISSUE TITLE
Does Pandapower have functions for line and bus admittance matrix?

### ISSUE THREAD

**Issue by lvzhibai** [e2nIEE/pandapower#985]
Hello, does pandapower have functions to calculate line admittance matrix and bus admittance matrix? 
In net.line there are only basic data of capacitances and reactances.

**Comment by rbolgaryn** [comment]
Hi @lvzhibai ,

take a look in the file pandapower.pypower.makeYbus.py

Roman

**Comment by ascheidl** [comment]
also we have a tutorial on the internal data structure https://github.com/e2nIEE/pandapower/blob/master/tutorials/internal_datastructure.ipynb
