### ISSUE TITLE
Installation instructions in docs are deprecated and must be updated

### ISSUE THREAD

**Issue by rbolgaryn** [e2nIEE/pandapower#995]
The installation instructions should be updated.

**Comment by SteffenMeinecke** [comment]
I didn't notice any large issues when I flew over it. So it should not be a big thing. Or has it already been fixed?
Who has access to the docs? @jkupka @lthurner @rbolgaryn ?

**Comment by KS-HTK** [comment]
I can not find any Installation Instructions in [ReadTheDocs](https://pandapower.readthedocs.io/en/latest/). So either they should be added back in or this issue can be closed.
As for the Instructions on the [pandapower Homepage](https://www.pandapower.org/start/), they seem up to date.
