### ISSUE TITLE
Add pandapower to conda?

### ISSUE THREAD

**Issue by rbolgaryn** [e2nIEE/pandapower#996]
Would mean more work to maintain pandapower, since it would need to be built for all the supported platforms. This could be implemented with a script which is executed every time pandapower is released.

The biggest advantage would be that all the dependencies that are required for pandapower would be installed, too, and conda would resolve dependencies at installation. 

Adding pandapower to conda would potentially make it more accessible to people.

At the same time, sometimes conda does not resolve dependencies very well. We need to collect feedback about problems that users face while using conda.

We need to decide if the advantages outweigh the increased effort to maintain pandapower.

**Comment by jwiemer112** [comment]
https://anaconda.org/conda-forge/pandapower
