### ISSUE TITLE
Unclear comments in create_measurement()

### ISSUE THREAD

**Issue by FrankYinXF** [e2nIEE/pandapower#998]
The comments (line 3310 in pandapower/create.py) in create_measurement() say 
"**value** (float) - Measurement value. Units are "MW" for P, "MVar" for Q, "p.u." for V,
        "kA" for I. Generation is a positive bus power consumption, injection negative"

"Generation is a positive bus power consumption, injection negative"
So, what does this mean? Please re-comment this function, and place a clear one.

**Comment by wangzhenassd** [comment]
Hi, I will have a look on that.

**Comment by wangzhenassd** [comment]
Fixed by #1003
