### ISSUE TITLE
The signing (positive and negative) of measurements conflicts with create_measurement()

### ISSUE THREAD

**Issue by FrankYinXF** [e2nIEE/pandapower#999]
At line 40 in pandapower/doc/estimation.rst, it says **"Generated power is positive, consumed power is negative."**

However, if add measurement in the state estimation example (pandapower/tutorials/state_estimation.ipynb) according to this rule,  it will generate an unreasonable result that is not consistent with the results in this example. 

Please check what is wrong.

**Comment by wangzhenassd** [comment]
Hi,
thanks a lot for identify this issue. I will correct this.
